import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { getProductById } from "@/content/products";
import styles from "../guide.module.css";
import compare from "./compare.module.css";

const slug="w-vs-wh",publishedAt="2026-08-21",siteUrl=process.env.NEXT_PUBLIC_SITE_URL??"https://carganomada.com";
const title="W vs Wh: diferencia entre potencia y energía";
const seoTitle="W vs Wh en una power station | Carga Nómada";
const description="Entiende la diferencia entre W y Wh en una power station: qué aparatos puede alimentar, cuánto pueden durar y cómo comparar modelos.";
export const metadata:Metadata={title:{absolute:seoTitle},description,alternates:{canonical:`/guias/${slug}`},openGraph:{type:"article",url:`/guias/${slug}`,title:seoTitle,description,siteName:"Carga Nómada",locale:"es_ES",publishedTime:publishedAt,modifiedTime:publishedAt},twitter:{card:"summary",title:seoTitle,description}};
const f1200=getProductById("fossibot-f1200")!,f1800=getProductById("fossibot-f1800")!;

export default function Guide(){const canonical=`${siteUrl}/guias/${slug}`;const schema={"@context":"https://schema.org","@graph":[{"@type":"BreadcrumbList","@id":`${canonical}#breadcrumb`,itemListElement:[{"@type":"ListItem",position:1,name:"Inicio",item:siteUrl},{"@type":"ListItem",position:2,name:"Guías",item:`${siteUrl}/guias`},{"@type":"ListItem",position:3,name:title,item:canonical}]},{"@type":"Article","@id":`${canonical}#article`,mainEntityOfPage:canonical,headline:title,description,datePublished:publishedAt,dateModified:publishedAt,inLanguage:"es",isAccessibleForFree:true,author:{"@id":`${siteUrl}#organization`},publisher:{"@id":`${siteUrl}#organization`},breadcrumb:{"@id":`${canonical}#breadcrumb`}}]};return <><main className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/>
<header className={styles.hero}><div className="container"><nav className={styles.breadcrumb} aria-label="Migas de pan"><Link href="/">Inicio</Link><span>/</span><Link href="/guias">Guías</Link><span>/</span><span>W vs Wh</span></nav><p className={styles.kicker}>Guía básica · Potencia y energía</p><h1>W vs Wh: diferencia entre potencia y energía</h1><p className={styles.lead}>Los W indican cuánta potencia entrega o consume un equipo en un momento dado. Los Wh indican cuánta energía almacena o utiliza durante un periodo. En una power station, los W responden “¿puede encenderlo?” y los Wh “¿durante cuánto tiempo?”.</p><div className={styles.byline}><span>Equipo editorial de Carga Nómada</span><span>Publicado y revisado el 21 de agosto de 2026</span></div></div></header>
<div className="container"><section className={styles.quick} aria-labelledby="resumen"><div><p className={styles.kicker}>En pocas palabras</p><h2 id="resumen">Dos cifras, dos decisiones</h2></div><div className={styles.formula} role="img" aria-label="Vatios multiplicados por horas es igual a vatios hora"><span>W · potencia</span><i/><span>horas · tiempo</span><b>×</b><strong>Wh · energía</strong></div><p>Necesitas suficiente potencia para alimentar el aparato y suficiente energía para mantenerlo. Cumplir solo una condición no basta.</p></section><div className={styles.layout}><article className={styles.article}>
<section id="comparacion"><p className={styles.index}>01 · La diferencia esencial</p><h2>W es potencia; Wh es energía</h2><div className={compare.grid}><article><span>W</span><strong>Potencia</strong><p>Indica el ritmo instantáneo al que un aparato usa energía o una estación puede entregarla.</p><b>Pregunta: ¿puede con esta carga?</b></article><article><span>Wh</span><strong>Energía</strong><p>Indica la cantidad almacenada o consumida al mantener una potencia durante un tiempo.</p><b>Pregunta: ¿cuánto puede durar?</b></article></div><p>La analogía del depósito ayuda si se usa con cuidado: los Wh son el tamaño del depósito y los W, la rapidez con la que sale la energía. Pero una power station también tiene límites electrónicos; no basta con tener un depósito grande si el inversor no soporta el caudal necesario.</p></section>
<section id="w"><p className={styles.index}>02 · Potencia</p><h2>Qué te dicen los W</h2><p>Los vatios aparecen tanto en los aparatos como en la salida de la estación. Una cafetera de 1.200 W pide aproximadamente esa potencia mientras calienta. Si la estación solo entrega 1.000 W continuos, no debes contar con que funcione aunque la batería tenga miles de Wh.</p><p>Distingue potencia continua y pico. La continua puede mantenerse; el pico cubre demandas breves, habituales al arrancar motores y compresores. Un pico de 2.400 W no convierte una salida de 1.200 W en una fuente capaz de sostener 2.000 W.</p><aside className={styles.callout}><strong>Para validar una carga</strong><p>Suma los W de todos los aparatos que funcionarán a la vez y comprueba también los arranques. Deja margen en lugar de diseñar tu rutina pegada al límite.</p></aside></section>
<section id="wh"><p className={styles.index}>03 · Energía</p><h2>Qué te dicen los Wh</h2><p>Los Wh se leen <strong>vatios hora</strong>, no “vatios por hora”. Describen capacidad o consumo acumulado. Una luz de 10 W encendida cinco horas utiliza 50 Wh. Un portátil que promedia 60 W durante tres horas utiliza 180 Wh. Una power station de 1.024 Wh almacena nominalmente más energía que esos consumos, pero no la entrega íntegra por las pérdidas.</p><p>Si quieres profundizar solo en capacidad nominal, energía útil y dimensionamiento, consulta la guía sobre <Link href="/guias/wh-power-station">qué son los Wh en una power station</Link>.</p></section>
<section id="formula"><p className={styles.index}>04 · Relacionar las unidades</p><h2>Las dos fórmulas que necesitas</h2><div className={styles.equation}><small>De potencia y tiempo a energía</small><code>W × horas = Wh consumidos</code><code>60 W × 3 h = 180 Wh</code><p>Calcula así la energía necesaria para un periodo.</p></div><div className={styles.equation}><small>De energía a duración</small><code>Wh útiles ÷ W = horas aproximadas</code><code>870 Wh ÷ 60 W ≈ 14,5 h</code><p>870 Wh son el resultado orientativo de aplicar un 85 % a 1.024 Wh nominales. No es una eficiencia universal.</p></div></section>
<section id="escenarios"><p className={styles.index}>05 · Cuatro combinaciones</p><h2>Mucha o poca potencia no implica mucha o poca capacidad</h2><div className={styles.tableWrap}><table><thead><tr><th>Configuración</th><th>Qué permite</th><th>Límite probable</th></tr></thead><tbody><tr><td>Pocos W · pocos Wh</td><td>Electrónica ligera durante poco tiempo</td><td>No admite cargas exigentes</td></tr><tr><td>Muchos W · pocos Wh</td><td>Enciende aparatos potentes</td><td>La batería puede agotarse pronto</td></tr><tr><td>Pocos W · muchos Wh</td><td>Mantiene cargas pequeñas muchas horas</td><td>No puede con aparatos potentes</td></tr><tr><td>Muchos W · muchos Wh</td><td>Más cargas y autonomía</td><td>Mayor peso, coste y recarga</td></tr></tbody></table></div><p>Esta matriz evita una compra habitual: elegir el número mayor sin mirar qué mide. Dos modelos pueden tener 1.024 Wh y salidas continuas distintas; o compartir potencia de salida y ofrecer capacidades muy diferentes.</p></section>
<section id="ejemplos"><p className={styles.index}>06 · Ejemplos prácticos</p><h2>Cómo cambia la decisión según el aparato</h2><div className={styles.exampleGrid}><article><span>Portátil</span><strong>60 W</strong><code>3 h = 180 Wh</code><p>Exige poca potencia y acumula consumo con el tiempo.</p></article><article><span>Cafetera</span><strong>1.000 W</strong><code>5 min ≈ 83 Wh</code><p>Exige mucha potencia, pero poca energía si se usa brevemente.</p></article><article><span>Router</span><strong>10 W</strong><code>24 h = 240 Wh</code><p>Una carga pequeña puede acumular bastante energía.</p></article><article><span>Calefactor</span><strong>2.000 W</strong><code>1 h = 2.000 Wh</code><p>Demanda mucha potencia y mucha energía.</p></article></div><p>Son ejemplos editoriales con consumos constantes. Los aparatos reales varían según modelo, modo y condiciones. Mide el consumo cuando la compra dependa de la estimación.</p></section>
<section id="comprar"><p className={styles.index}>07 · Llevarlo a una compra</p><h2>Qué debes mirar primero</h2><ol className={styles.steps}><li><strong>Haz una lista de aparatos.</strong><span>Anota W de funcionamiento, posibles picos y horas.</span></li><li><strong>Comprueba potencia simultánea.</strong><span>Así determinas los W continuos que necesitas.</span></li><li><strong>Calcula energía diaria.</strong><span>Multiplica W por horas y suma todos los Wh.</span></li><li><strong>Añade pérdidas y margen.</strong><span>No trates la capacidad nominal como energía íntegra.</span></li><li><strong>Revisa recarga y peso.</strong><span>Una batería mayor debe poder recuperarse y transportarse.</span></li></ol><p>En la <Link href="/reviews/fossibot-f1200-review">review de la {f1200.name}</Link> analizamos {f1200.capacityWh.toLocaleString("es-ES")} Wh con {f1200.continuousOutputWatts.toLocaleString("es-ES")} W para camping. La <Link href="/reviews/fossibot-f1800-review">review de la {f1800.name}</Link> conserva {f1800.capacityWh.toLocaleString("es-ES")} Wh pero eleva la salida a {f1800.continuousOutputWatts.toLocaleString("es-ES")} W: un ejemplo claro de cómo más W no significan más Wh.</p></section>
<section id="errores"><p className={styles.index}>08 · Evita estas trampas</p><h2>Errores frecuentes con W y Wh</h2><div className={styles.mistakes}><div><strong>Comparar números sin unidades</strong><p>1.200 W y 1.024 Wh no compiten: miden cosas diferentes.</p></div><div><strong>Usar el pico como continuo</strong><p>El pico solo cubre demandas breves.</p></div><div><strong>Calcular duración sin pérdidas</strong><p>La capacidad nominal no llega completa al aparato.</p></div><div><strong>Olvidar la simultaneidad</strong><p>Los W de los equipos activos se suman.</p></div></div></section>
<section id="faq" className={styles.faq}><p className={styles.index}>09 · Preguntas frecuentes</p><h2>Dudas sobre W vs Wh</h2><details><summary>¿Cuál es la diferencia entre W y Wh?</summary><p>Los W miden potencia instantánea; los Wh miden energía acumulada durante un periodo.</p></details><details><summary>¿2.000 Wh son 2.000 W durante una hora?</summary><p>Es una equivalencia ideal. En la práctica habrá pérdidas y la estación debe poder entregar 2.000 W continuos.</p></details><details><summary>¿Más W significan más autonomía?</summary><p>No. Más W permiten alimentar cargas más potentes. La autonomía depende principalmente de Wh útiles y consumo.</p></details><details><summary>¿Qué miro para una nevera?</summary><p>Comprueba sus W y pico de arranque para saber si la estación puede alimentarla, y sus Wh diarios para estimar duración. La guía sobre <Link href="/guias/que-puedo-conectar-power-station">qué puedes conectar a una power station</Link> desarrolla la compatibilidad.</p></details><details><summary>¿Qué cifra importa más?</summary><p>Ambas. Los W determinan si funciona; los Wh, cuánto dura. La prioridad depende de tus aparatos y horas de uso.</p></details></section>
<section id="siguiente"><p className={styles.index}>10 · Siguiente paso</p><h2>Aplica ambas cifras</h2><div className={styles.nextGrid}><div><h3>Calcula duración</h3><Link href="/guias/calcular-autonomia-power-station">Calcular autonomía →</Link></div><div><h3>Valida tus cargas</h3><Link href="/guias/que-puedo-conectar-power-station">Qué puedes conectar →</Link></div></div></section>
<section className={styles.sources}><p className={styles.index}>11 · Metodología</p><h2>Cómo se han preparado los ejemplos</h2><p>Los consumos son supuestos editoriales orientativos y el 85 % es una simplificación explícita, no una eficiencia universal. Para productos concretos utilizamos fichas verificadas; para tus aparatos, prevalecen etiqueta, manual y medición.</p></section>
</article><aside className={styles.aside} aria-label="Contenido"><span>En esta guía</span><a href="#comparacion">La diferencia</a><a href="#w">Qué son W</a><a href="#wh">Qué son Wh</a><a href="#formula">Fórmulas</a><a href="#escenarios">Escenarios</a><a href="#ejemplos">Ejemplos</a><a href="#comprar">Antes de comprar</a><a href="#faq">Preguntas</a></aside></div></div></main><SiteFooter/></>}
