import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { getProductById } from "@/content/products";
import styles from "../use-case.module.css";

const slug="trabajo-remoto",publishedAt="2026-08-22",siteUrl=process.env.NEXT_PUBLIC_SITE_URL??"https://carganomada.com";
const title="Qué power station necesitas para trabajar en remoto";
const description="Calcula la power station para trabajo remoto según portátil, monitor, router, Starlink, Wh por jornada, USB-C y días entre recargas.";
export const metadata:Metadata={title:{absolute:"Power station para trabajo remoto | Carga Nómada"},description,alternates:{canonical:`/usos/${slug}`},openGraph:{type:"article",url:`/usos/${slug}`,title,description,siteName:"Carga Nómada",locale:"es_ES",publishedTime:publishedAt,modifiedTime:publishedAt},twitter:{card:"summary",title,description}};
const f1200=getProductById("fossibot-f1200")!,f1800=getProductById("fossibot-f1800")!,f2400=getProductById("fossibot-f2400")!;const n=(v:number|undefined)=>v?.toLocaleString("es-ES")??"no declarado";

export default function RemoteWorkPage(){const canonical=`${siteUrl}/usos/${slug}`;const schema={"@context":"https://schema.org","@graph":[{"@type":"BreadcrumbList","@id":`${canonical}#breadcrumb`,itemListElement:[{"@type":"ListItem",position:1,name:"Inicio",item:siteUrl},{"@type":"ListItem",position:2,name:"Usos",item:`${siteUrl}/usos`},{"@type":"ListItem",position:3,name:"Trabajo remoto",item:canonical}]},{"@type":"Article","@id":`${canonical}#article`,mainEntityOfPage:canonical,headline:title,description,datePublished:publishedAt,dateModified:publishedAt,inLanguage:"es",isAccessibleForFree:true,author:{"@id":`${siteUrl}#organization`},publisher:{"@id":`${siteUrl}#organization`},breadcrumb:{"@id":`${canonical}#breadcrumb`}}]};return <><main className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/>
<header className={styles.hero}><div className="container"><nav className={styles.breadcrumb} aria-label="Migas de pan"><Link href="/">Inicio</Link><span>/</span><Link href="/usos">Usos</Link><span>/</span><span>Trabajo remoto</span></nav><p className={styles.kicker}>Caso de uso 04 · Trabajo remoto</p><h1>{title}</h1><p className={styles.lead}>Calcula la energía de una jornada completa, no solo la potencia del cargador. Suma portátil, monitor, conectividad, móvil y accesorios durante sus horas reales; después decide cuántas jornadas quieres cubrir y cómo recargarás.</p><div className={styles.heroFacts}><span>Wh por jornada</span><span>USB-C PD</span><span>Continuidad</span></div><div className={styles.byline}><span>Equipo editorial de Carga Nómada</span><span>Publicado y revisado el 22 de agosto de 2026</span></div></div></header>
<div className="container"><section className={styles.quick}><div><p className={styles.kicker}>Respuesta rápida</p><h2>Diseña para terminar la jornada</h2></div><ol><li><span>01</span>Mide cada equipo trabajando</li><li><span>02</span>Multiplica W por horas</li><li><span>03</span>Suma Wh por jornada</li><li><span>04</span>Multiplica por jornadas</li><li><span>05</span>Añade reserva y recarga</li></ol><p>La elección depende sobre todo de Wh por jornada, potencia y compatibilidad de salidas, jornadas entre recargas y una vía realista para recuperar energía.</p></section></div>
<article>
<section className={styles.section}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>01 · La unidad útil</p><h2>Tu presupuesto energético es una jornada</h2><p>Un cargador de 100 W puede entregar hasta esa potencia, pero el portátil no consume 100 W constantes. CPU/GPU, brillo, carga de batería, videollamadas y periféricos cambian la media.</p></div><div className={styles.priorityGrid}><article><span>CONSUMO</span><strong>W × h</strong><p>Potencia media editorial o medida durante horas reales.</p></article><article><span>JORNADA</span><strong>Wh</strong><p>Suma de portátil, pantalla, internet y accesorios.</p></article><article><span>RESERVA</span><strong>20 %</strong><p>Colchón editorial, no una pérdida universal del sistema.</p></article><article><span>RECARGA</span><strong>balance</strong><p>Lo recuperado durante o después modifica la batería necesaria.</p></article></div><p className={styles.text}>Consulta <Link href="/guias/w-vs-wh">la diferencia entre W y Wh</Link> si necesitas separar potencia instantánea y energía acumulada.</p></div></section>
<section className={`${styles.section} ${styles.scenarios}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>02 · Tres puestos de trabajo</p><h2>De un portátil ligero a dos jornadas conectadas</h2><p>Todos los consumos son hipótesis editoriales trazables. Sustitúyelos por datos de tu equipo o mediciones en una jornada representativa.</p></div><div className={styles.scenarioGrid}>
<Scenario no="01" label="Trabajo ligero · 1 jornada" name="Portátil, móvil y hotspot" energy="303" margin="364" power="≈65 W" lines={["Portátil: 40 W × 6 h = 240 Wh","Móvil: 1 carga × 15 Wh = 15 Wh","Hotspot: 8 W × 6 h = 48 Wh"]} total="Total 303 Wh; con 20 % = 363,6 Wh." note="USB-C compatible y portabilidad. Los modelos de 1.024 Wh del catálogo están sobredimensionados para este ejemplo; una batería menor puede ser más proporcionada."/>
<Scenario no="02" label="Jornada conectada · 8 horas" name="Portátil, monitor y router" energy="761" margin="913" power="≈115 W" lines={["Portátil: 55 W × 8 h = 440 Wh","Monitor: 30 W × 7 h = 210 Wh","Router: 12 W × 8 h = 96 Wh","Móvil: 1 carga × 15 Wh = 15 Wh"]} total="Total 761 Wh; con 20 % = 913,2 Wh." note="Wh por jornada, USB-C potente y reserva. Una estación de 1.024 Wh queda cerca del presupuesto con margen: no añadas otras cargas sin recalcular."/>
<Scenario wide no="03" label="Starlink y creación · 2 jornadas" name="Portátil, monitor, conexión y cámara" energy="2.600" margin="3.120" power="≈180 W" lines={["Portátil: 65 W × 8 h × 2 = 1.040 Wh","Monitor: 35 W × 7 h × 2 = 490 Wh","Starlink: 60 W × 8 h × 2 = 960 Wh","Móvil: 15 Wh × 2 = 30 Wh","Baterías de cámara: 2 × 20 Wh × 2 = 80 Wh"]} total="Total 2.600 Wh; con 20 % = 3.120 Wh. Una jornada = 1.300 Wh; con margen = 1.560 Wh." note="Capacidad y recarga entre jornadas. Usamos 60 W para Starlink solo como hipótesis editorial: modelo, actividad, alimentación, configuración y condiciones cambian su consumo."/>
</div><aside className={styles.notice}><strong>Una jornada frente a dos</strong><p>Si tu puesto consume 761 Wh por jornada, dos jornadas suman 1.522 Wh antes de reserva. Multiplica primero y aplica después el mismo margen; no des por hecho que una cifra nominal equivale a energía garantizada.</p></aside></div></section>
<section className={styles.section}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>03 · Así construimos una jornada</p><h2>Cada fila debe poder medirse</h2><p>Ejemplo de la jornada conectada. Las cifras no declaran consumos universales.</p></div><div className={styles.weightBoard}><div><span>Equipo</span><span>Potencia/energía usada</span><span>Tiempo</span><span>Wh/jornada</span></div><div><strong>Portátil</strong><span>55 W medios</span><span>8 h</span><span>440 Wh</span></div><div><strong>Monitor</strong><span>30 W medios</span><span>7 h</span><span>210 Wh</span></div><div><strong>Router</strong><span>12 W medios</span><span>8 h</span><span>96 Wh</span></div><div><strong>Móvil</strong><span>15 Wh por carga</span><span>1 carga</span><span>15 Wh</span></div></div><p className={styles.text}>Una videollamada o renderizado puede elevar el consumo del portátil respecto a tareas ligeras. No diseñes justo al límite: mide con brillo, periféricos y carga de trabajo parecidos a los reales.</p></div></section>
<section className={`${styles.section} ${styles.models}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>04 · La conexión clave</p><h2>USB-C no basta: importan vatios, PD y cable</h2><p>El puerto, el perfil Power Delivery, el cable y el portátil deben ser compatibles. Si lo son, alimentar directamente por USB-C simplifica el puesto y evita ocupar una toma AC, sin prometer un ahorro fijo.</p></div><div className={styles.modelGrid}><article><span>F1200</span><h3>Hasta 100 W</h3><p>Incluye un USB-C de hasta 100 W y otro de hasta 20 W. Verifica que el portátil acepte el perfil disponible.</p></article><article><span>F1800</span><h3>2 × 140 W PD 3.0</h3><p>Permite dos salidas USB-C de hasta 140 W según catálogo, útil para portátil y otro equipo compatible.</p></article><article><span>F2400</span><h3>100 W + 3 × 20 W</h3><p>Combina un USB-C de hasta 100 W con tres de hasta 20 W para periféricos y móviles.</p></article></div></div></section>
<section className={styles.section}><div className="container"><div className={styles.split}><div><p className={styles.index}>05 · Continuidad</p><h2>Capacidad nominal no significa jornada garantizada</h2></div><div><p>Reserva energía para variaciones, conversión, otras cargas y un cierre seguro del trabajo. El margen editorial del 20 % hace visible esa prudencia, pero no sustituye una medición.</p><p>Si la misma estación alimenta nevera, luces o sistemas de una furgoneta, suma el presupuesto laboral y el doméstico. Esta página calcula el puesto; el caso de <Link href="/usos/camper">power station para camper</Link> calcula la vida diaria del vehículo.</p><p>Algunos modelos declaran función UPS, pero no los presentes como sustitutos automáticos de un SAI profesional para servidores, equipos médicos o infraestructura crítica.</p></div></div></div></section>
<section className={styles.section}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>06 · Durante y después del trabajo</p><h2>La recarga cambia el balance, no el consumo</h2><p>Si gastas 600 Wh durante la jornada y recuperas 300 Wh solares reales en ese periodo, la descarga neta cambia. Esa producción debe medirse o estimarse con prudencia: no es constante ni garantizada.</p></div><div className={styles.priorityGrid}><article><span>RED</span><strong>previsible</strong><p>Recarga antes o después cuando dispones de una toma compatible.</p></article><article><span>SOLAR</span><strong>variable</strong><p>Depende de panel, entrada, orientación, sombra y condiciones.</p></article><article><span>VEHÍCULO</span><strong>en ruta</strong><p>Sirve si el trabajo forma parte de un viaje y el sistema es compatible.</p></article><article><span>RESERVA</span><strong>final</strong><p>No planifiques llegar al 0 % en mitad de una entrega o llamada.</p></article></div><p className={styles.text}>La <Link href="/guias/placas-solares-power-station">guía de placas solares</Link> desarrolla compatibilidad y estimación sin convertir esta página en una guía solar.</p></div></section>
<section className={`${styles.section} ${styles.models}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>07 · Modelos según la jornada</p><h2>La comodidad no siempre añade autonomía</h2><p>F1200 y F1800 almacenan los mismos 1.024 Wh. La diferencia para trabajar está en potencia, USB-C y velocidad de recarga, no en más horas nominales.</p></div><div className={styles.modelGrid}><Model p={f1200} tag="UNA JORNADA MODERADA" body="1.024 Wh, 1.200 W, 11,5 kg y USB-C de 100 W. Puede encajar con la jornada conectada si el consumo real deja reserva." limit="Para portátil y hotspot ligeros es grande; para dos jornadas conectadas, insuficiente sin recarga."/><Model p={f1800} tag="MÁS PUERTOS Y RECARGA" body="Mantiene 1.024 Wh, pero ofrece 1.800 W, dos USB-C de 140 W y entrada solar máxima de 500 W." limit="No dura más que F1200 por capacidad nominal: ambas almacenan 1.024 Wh."/><Model p={f2400} tag="DOS JORNADAS EXIGENTES" body="2.048 Wh y 2.400 W aportan más reserva cuando hay monitor, Starlink u otras cargas compartidas." limit="22 kg son excesivos para alimentar solo un portátil; el escenario Starlink de dos jornadas aún exige recarga."/></div></div></section>
<section className={`${styles.section} ${styles.dark}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>08 · Errores frecuentes</p><h2>Lo que puede cortar la jornada</h2></div><div className={styles.checkGrid}>{[["Mirar el cargador","Su máximo no es el consumo constante del portátil."],["Olvidar las horas","Los W solo se convierten en energía al multiplicar por tiempo."],["Contar todos los Wh","La capacidad nominal no garantiza energía íntegra para cargas."],["Ignorar el monitor","Puede cambiar mucho el presupuesto diario."],["Fijar Starlink en 60 W","Es una hipótesis, no una cifra universal."],["Compartir sin sumar","Nevera y luces compiten con el puesto de trabajo."],["Comprar 2 kWh por defecto","Un portátil ligero puede necesitar bastante menos."],["Confiar en cualquier USB-C","Valida PD, perfil, potencia y cable."],["Esperar sol perfecto","La producción cambia durante la jornada."],["Trabajar sin reserva","Un cálculo al límite no absorbe tareas exigentes."]].map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,"0")}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
<section className={`${styles.section} ${styles.faq}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>09 · Preguntas frecuentes</p><h2>Dudas sobre energía para trabajar</h2></div><Faq q="¿Cuántos Wh necesito para trabajar con un portátil?" a="Multiplica su potencia media durante tu trabajo por las horas y añade móvil, internet y accesorios. El ejemplo ligero suma 303 Wh en una jornada antes del margen."/><Faq q="¿Cuánto dura una power station con un portátil?" a="Depende de capacidad utilizable y consumo real, no solo de los W del cargador. Usa una medición con tu carga de trabajo para estimarlo."/><Faq q="¿Qué power station necesito para Starlink?" a="Suma el consumo medido de tu modelo a portátil, monitor y demás equipos. Aquí usamos 60 W únicamente como hipótesis editorial."/><Faq q="¿Puedo alimentar portátil y monitor a la vez?" a="Sí si las salidas soportan su potencia conjunta y tienes energía suficiente para las horas previstas. Comprueba AC, USB-C y cables."/><Faq q="¿Es mejor USB-C o enchufe AC?" a="USB-C puede simplificar el puesto si potencia, PD, perfil y cable son compatibles. AC sigue siendo necesario para equipos sin entrada USB-C adecuada."/><Faq q="¿Puedo usar la misma estación para camper y trabajo?" a="Sí, pero debes sumar ambos presupuestos energéticos y las cargas simultáneas. No reserves toda la capacidad nominal al trabajo."/></div></section>
<section className={`${styles.section} ${styles.cta}`}><div className="container"><p className={styles.kicker}>Tu jornada, tus equipos</p><h2>Calcula tu puesto de trabajo</h2><p>Añade portátil, monitor, conexión y accesorios con sus horas reales. Después decide cuántas jornadas necesitas cubrir.</p><Link href="/encontrar-power-station">Calcular mi power station →</Link></div></section>
<section className={styles.sources}><div className="container"><p className={styles.index}>10 · Metodología</p><h2>Datos de catálogo frente a supuestos</h2><p>Capacidad, potencia, peso, USB-C, solar y funciones proceden de <code>src/content/products.ts</code>, con fuentes de fabricante verificadas el 20 de agosto de 2026. Consumos, horas, jornadas, simultaneidad y margen del 20 % son hipótesis editoriales, no pruebas físicas.</p></div></section>
</article></main><SiteFooter/></>}
function Scenario({no,label,name,energy,margin,power,lines,total,note,wide=false}:{no:string;label:string;name:string;energy:string;margin:string;power:string;lines:string[];total:string;note:string;wide?:boolean}){return <article className={`${styles.scenarioCard} ${wide?styles.scenarioWide:""}`}><header><span>{no}</span><div><p>{label}</p><h3>{name}</h3></div></header><div className={styles.scenarioBody}><dl><div><dt>Energía calculada</dt><dd>≈{energy} Wh</dd></div><div><dt>Plan con margen</dt><dd>≈{margin} Wh</dd></div><div><dt>Potencia simultánea</dt><dd>{power}</dd></div></dl><div className={styles.math}>{lines.map(x=><code key={x}>{x}</code>)}<span>{total}</span></div><p><strong>Prioriza:</strong> {note}</p></div></article>}
function Model({p,tag,body,limit}:{p:typeof f1200;tag:string;body:string;limit:string}){return <article><span>{tag}</span><h3>{p.name}</h3><div className={styles.modelSpecs}><strong>{n(p.capacityWh)} Wh</strong><strong>{n(p.continuousOutputWatts)} W</strong><strong>{n(p.weightKg)} kg</strong></div><p>{body}</p><p className={styles.limit}><b>Límite:</b> {limit}</p><Link href={`/reviews/${p.slug}-review`}>Ver análisis de la {p.model} →</Link></article>}
function Faq({q,a}:{q:string;a:string}){return <details><summary>{q}</summary><p>{a}</p></details>}
