import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { getProductById } from "@/content/products";
import styles from "../use-case.module.css";

const slug = "camping";
const publishedAt = "2026-08-22";
const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://carganomada.com";
const title = "Qué power station necesitas para camping";
const seoTitle = "Power station para camping: qué necesitas | Carga Nómada";
const description = "Elige una power station para camping según tus aparatos, días, nevera, potencia, recarga y peso. Tres escenarios con cálculos transparentes.";

export const metadata: Metadata = {
  title: { absolute: seoTitle },
  description,
  alternates: { canonical: `/usos/${slug}` },
  openGraph: { type: "article", url: `/usos/${slug}`, title: seoTitle, description, siteName: "Carga Nómada", locale: "es_ES", publishedTime: publishedAt, modifiedTime: publishedAt },
  twitter: { card: "summary", title: seoTitle, description },
};

const f1200 = getProductById("fossibot-f1200")!;
const f1800 = getProductById("fossibot-f1800")!;
const f2400 = getProductById("fossibot-f2400")!;
const number = (value: number | undefined) => value?.toLocaleString("es-ES") ?? "no declarado";
const density = (capacity: number | undefined, weight: number | undefined) => capacity && weight ? `${Math.round(capacity / weight)} Wh/kg` : "no calculable";

export default function CampingUsePage() {
  const canonical = `${siteUrl}/usos/${slug}`;
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "BreadcrumbList", "@id": `${canonical}#breadcrumb`, itemListElement: [
      { "@type": "ListItem", position: 1, name: "Inicio", item: siteUrl },
      { "@type": "ListItem", position: 2, name: "Usos", item: `${siteUrl}/usos` },
      { "@type": "ListItem", position: 3, name: "Camping", item: canonical },
    ] },
    { "@type": "Article", "@id": `${canonical}#article`, mainEntityOfPage: canonical, headline: title, description, datePublished: publishedAt, dateModified: publishedAt, inLanguage: "es", isAccessibleForFree: true, author: { "@id": `${siteUrl}#organization` }, publisher: { "@id": `${siteUrl}#organization` }, breadcrumb: { "@id": `${canonical}#breadcrumb` } },
  ] };

  return <><main className={styles.page}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
    <header className={styles.hero}><div className="container">
      <nav className={styles.breadcrumb} aria-label="Migas de pan"><Link href="/">Inicio</Link><span>/</span><Link href="/usos">Usos</Link><span>/</span><span>Camping</span></nav>
      <p className={styles.kicker}>Caso de uso 01 · Camping</p>
      <h1>Qué power station necesitas para camping</h1>
      <p className={styles.lead}>No existe una capacidad única para camping. Móvil y luces necesitan mucho menos que una nevera funcionando durante tres días. Elige desde tus aparatos, las horas de uso, la potencia simultánea, la recarga disponible y el peso que realmente quieres mover.</p>
      <div className={styles.heroFacts}><span>2–3 días</span><span>3 escenarios</span><span>Wh frente a kg</span></div>
      <div className={styles.byline}><span>Equipo editorial de Carga Nómada</span><span>Publicado y revisado el 22 de agosto de 2026</span></div>
    </div></header>

    <div className="container"><section className={styles.quick} aria-labelledby="respuesta-rapida"><div><p className={styles.kicker}>Respuesta rápida</p><h2 id="respuesta-rapida">Empieza por la escapada, no por la batería</h2></div><ol><li><span>01</span>Suma los consumos</li><li><span>02</span>Multiplícalos por horas y días</li><li><span>03</span>Comprueba W y arranques</li><li><span>04</span>Decide si podrás recargar</li><li><span>05</span>Equilibra capacidad y peso</li></ol><p>Los escenarios siguientes son ejemplos editoriales. Sustituye cada supuesto por la etiqueta o medición de tus aparatos antes de comprar.</p></section></div>

    <article>
      <section className={styles.section} id="necesidades"><div className="container"><div className={styles.sectionHead}><p className={styles.index}>01 · Lo que cambia la decisión</p><h2>La nevera y los días pesan más que el número de enchufes</h2><p>Para camping importa tanto lo que consumes como lo lejos que debes transportar la estación. Una salida de fin de semana junto al coche no plantea lo mismo que una tienda alejada de la parcela.</p></div><div className={styles.priorityGrid}><article><span>ENERGÍA</span><strong>Wh</strong><p>Cuántas cargas, horas de luz o ciclos de nevera puedes sostener.</p></article><article><span>POTENCIA</span><strong>W</strong><p>Si la estación puede alimentar lo que coincide y soportar un arranque.</p></article><article><span>TRANSPORTE</span><strong>kg</strong><p>Lo que tendrás que descargar, mover, guardar y volver a cargar.</p></article><article><span>RECARGA</span><strong>sol / red</strong><p>Si sales con toda la energía o puedes reponer parte durante la estancia.</p></article></div><p className={styles.text}>Comprueba siempre la potencia de cada aparato y su salida compatible. La guía sobre <Link href="/guias/que-puedo-conectar-power-station">qué puedes conectar a una power station</Link> desarrolla picos, simultaneidad y puertos sin duplicarlos aquí.</p></div></section>

      <section className={`${styles.section} ${styles.scenarios}`} id="escenarios"><div className="container"><div className={styles.sectionHead}><p className={styles.index}>02 · Tres formas de acampar</p><h2>Escenarios de camping, no tallas universales</h2><p>Cada tarjeta convierte una rutina posible en un cálculo visible. No son mediciones ni garantías de autonomía.</p></div><div className={styles.scenarioGrid}>
        <article className={styles.scenarioCard}><header><span>01</span><div><p>Camping ligero · 2 días</p><h3>Móvil, cámara y luces</h3></div></header><div className={styles.scenarioBody}><dl><div><dt>Aparatos</dt><dd>2 móviles, luz LED y cámara</dd></div><div><dt>Energía calculada</dt><dd>≈154 Wh</dd></div><div><dt>Plan con margen</dt><dd>≈185 Wh</dd></div><div><dt>Potencia simultánea</dt><dd>≈25 W</dd></div></dl><div className={styles.math}><code>(2 × 15 Wh × 2 días) + (8 W × 4 h × 2) + (15 Wh × 2)</code><span>= 154 Wh; añadimos un 20 % editorial</span></div><p><strong>Prioriza:</strong> poco peso, USB-C, luz integrada y sencillez. Una estación de 1 kWh cubre este ejemplo con mucho margen; si solo llevas USB, una batería más pequeña que las disponibles en este catálogo podría ser más proporcionada.</p></div></article>
        <article className={styles.scenarioCard}><header><span>02</span><div><p>Camping con nevera · 2 días</p><h3>Frío continuo, móvil y luces</h3></div></header><div className={styles.scenarioBody}><dl><div><dt>Aparatos</dt><dd>Nevera 12 V, 2 móviles y luz</dd></div><div><dt>Energía calculada</dt><dd>≈824 Wh</dd></div><div><dt>Plan con margen</dt><dd>≈990 Wh</dd></div><div><dt>Potencia simultánea</dt><dd>≈100 W + arranque</dd></div></dl><div className={styles.math}><code>(350 Wh/día × 2) + (30 Wh/día × 2) + (8 W × 4 h × 2)</code><span>= 824 Wh; nevera y clima reales pueden cambiarlo mucho</span></div><p><strong>Prioriza:</strong> salida 12 V regulada, consumo medido en 24 horas, margen para el compresor y una vía de recarga. Aquí 1.024 Wh nominales ya no sobran: valida energía utilizable y considera solar o red.</p></div></article>
        <article className={`${styles.scenarioCard} ${styles.scenarioWide}`}><header><span>03</span><div><p>Más comodidad · 2 días</p><h3>Nevera, portátil y café puntual</h3></div></header><div className={styles.scenarioBody}><dl><div><dt>Aparatos</dt><dd>Nevera, portátil, 2 móviles, 2 luces y cafetera</dd></div><div><dt>Energía calculada</dt><dd>≈1.445 Wh</dd></div><div><dt>Plan con margen</dt><dd>≈1.734 Wh</dd></div><div><dt>Potencia simultánea</dt><dd>≈1.150 W</dd></div></dl><div className={styles.math}><code>Nevera: 350 Wh/día × 2 días = 700 Wh</code><code>Portátil: 65 W × 3 h/día × 2 días = 390 Wh</code><code>Móviles: 2 × 15 Wh × 2 días = 60 Wh</code><code>Luces: 2 × 8 W × 4 h/día × 2 días = 128 Wh</code><code>Cafetera: 1.000 W × 5/60 h × 2 días ≈ 166,7 Wh</code><span>Total ≈ 1.444,7 Wh; con un margen editorial del 20 % ≈ 1.733,6 Wh. Redondeamos a 1.445 Wh y 1.734 Wh.</span></div><p><strong>Prioriza:</strong> más Wh, potencia continua con holgura, simultaneidad y recarga rápida. La cafetera exige W altos durante pocos minutos; no confundas esa potencia con el consumo diario.</p></div></article>
      </div><aside className={styles.notice}><strong>Cómo leer los números</strong><p>Los Wh de móviles representan energía por carga; la nevera usa un supuesto diario porque el compresor trabaja por ciclos. El margen del 20 % es una decisión editorial para estos ejemplos, no una pérdida universal del sistema. Usa la <Link href="/guias/calcular-autonomia-power-station">guía de autonomía</Link> para adaptar el cálculo.</p></aside></div></section>

      <section className={styles.section} id="peso"><div className="container"><div className={styles.sectionHead}><p className={styles.index}>03 · La diferencia frente a una camper</p><h2>Más batería no siempre mejora tu camping</h2><p>En una tienda puedes tener que sacar la estación del coche, llevarla hasta la parcela y guardarla cada noche. El salto de capacidad se paga también en kilos.</p></div><div className={styles.weightBoard}><div><span>Modelo</span><span>Capacidad</span><span>Peso</span><span>Wh nominales/kg</span></div>{[f1200,f1800,f2400].map(product=><div key={product.id}><strong>{product.model}</strong><span>{number(product.capacityWh)} Wh</span><span>{number(product.weightKg)} kg</span><span>{density(product.capacityWh,product.weightKg)}</span></div>)}</div><p className={styles.text}>La relación Wh/kg solo ayuda a comparar transporte y almacenamiento nominal: no describe energía AC utilizable, ergonomía del asa ni facilidad para recorrer terreno irregular. La F2400 duplica la capacidad de F1200 y F1800, pero también sube a {number(f2400.weightKg)} kg.</p></div></section>

      <section className={`${styles.section} ${styles.models}`} id="modelos"><div className="container"><div className={styles.sectionHead}><p className={styles.index}>04 · Modelos según el escenario</p><h2>Tres decisiones distintas dentro del catálogo</h2><p>No hay un ganador general: cada modelo resuelve una tensión diferente entre transporte, potencia, capacidad y recarga.</p></div><div className={styles.modelGrid}>
        <article><span>BASE EQUILIBRADA</span><h3>{f1200.name}</h3><div className={styles.modelSpecs}><strong>{number(f1200.capacityWh)} Wh</strong><strong>{number(f1200.continuousOutputWatts)} W</strong><strong>{number(f1200.weightKg)} kg</strong></div><p>Tiene sentido para un fin de semana moderado con nevera eficiente, luces y electrónica si verificas el consumo. Sus {number(f1200.charging?.maxSolarInputWatts ?? 0)} W solares son una recarga pausada.</p><p className={styles.limit}><b>Límite:</b> no es la opción proporcionada para el escenario USB ligero y puede quedarse corta en tres días con nevera sin recarga.</p><Link href="/reviews/fossibot-f1200-review">Leer la review F1200 para camping →</Link></article>
        <article><span>MÁS POTENCIA Y RECARGA</span><h3>{f1800.name}</h3><div className={styles.modelSpecs}><strong>{number(f1800.capacityWh)} Wh</strong><strong>{number(f1800.continuousOutputWatts)} W</strong><strong>{number(f1800.weightKg)} kg</strong></div><p>Mantiene la capacidad de la F1200, pero eleva potencia, entrada solar a {number(f1800.charging?.maxSolarInputWatts ?? 0)} W y ofrece dos USB-C de hasta 140 W. Encaja si llevas portátil, café puntual o recargas con buen sol.</p><p className={styles.limit}><b>Límite:</b> más W no significan más horas; sigue almacenando {number(f1800.capacityWh)} Wh.</p><Link href="/reviews/fossibot-f1800-review">Leer la review F1800 →</Link></article>
        <article><span>CAPACIDAD ANTES QUE PESO</span><h3>{f2400.name}</h3><div className={styles.modelSpecs}><strong>{number(f2400.capacityWh)} Wh</strong><strong>{number(f2400.continuousOutputWatts)} W</strong><strong>{number(f2400.weightKg)} kg</strong></div><p>Sus {number(f2400.capacityWh)} Wh dan margen al escenario cómodo y a estancias con nevera donde no quieres depender tanto de recargar. También soporta cargas simultáneas más exigentes.</p><p className={styles.limit}><b>Límite:</b> {number(f2400.weightKg)} kg exigen una parcela accesible y un lugar estable; para móvil y luces está claramente sobredimensionada.</p><Link href="/reviews/fossibot-f2400-review">Leer la review F2400 →</Link></article>
      </div></div></section>

      <section className={styles.section} id="recarga"><div className="container"><div className={styles.split}><div><p className={styles.index}>05 · Red, coche o sol</p><h2>Cuándo merece la pena llevar placa solar</h2></div><div><p>Para dos noches, una batería dimensionada con margen puede evitar desplegar paneles. El solar gana sentido con nevera, varios días, buen acceso al sol y un campamento relativamente fijo.</p><p>Los vatios nominales del panel no son producción constante, y el panel debe ser eléctricamente compatible. Revisa la guía de <Link href="/guias/placas-solares-power-station">placas solares para power stations</Link> antes de elegir cables o combinar paneles.</p><p>La recarga desde vehículo puede ayudar durante desplazamientos, pero no presupongas potencia ni funcionamiento con el motor apagado: consulta vehículo, estación y accesorios.</p></div></div></div></section>

      <section className={`${styles.section} ${styles.dark}`} id="prioridades"><div className="container"><div className={styles.sectionHead}><p className={styles.index}>06 · Lista corta</p><h2>Prioriza esto antes de comprar</h2></div><div className={styles.checkGrid}><article><span>01</span><h3>Consumo diario de la nevera</h3><p>Busca Wh/24 h medidos en condiciones parecidas, no multipliques su potencia máxima por todo el día.</p></article><article><span>02</span><h3>Peso que moverás</h3><p>Simula el trayecto desde el coche. Capacidad inútil también ocupa espacio y añade esfuerzo.</p></article><article><span>03</span><h3>Salida 12 V y USB-C</h3><p>Conexiones directas pueden simplificar cables; valida tensión, potencia y protocolo de cada aparato.</p></article><article><span>04</span><h3>Potencia simultánea</h3><p>Suma lo que coincidirá. Una cafetera puede compartir momento con nevera, portátil y cargadores.</p></article><article><span>05</span><h3>Plan de recarga</h3><p>Red antes de salir, coche en ruta o solar en parcela: define cuál existe de verdad.</p></article><article><span>06</span><h3>Protección ambiental</h3><p>No asumas resistencia al agua. Mantén estación, conectores y cables secos y ventilados.</p></article></div></div></section>

      <section className={styles.section} id="errores"><div className="container"><div className={styles.sectionHead}><p className={styles.index}>07 · Errores frecuentes</p><h2>Lo que suele desajustar el cálculo</h2></div><div className={styles.mistakes}><div><strong>Elegir “por si acaso”</strong><p>Duplicar capacidad puede duplicar peso sin aportar valor a una escapada corta.</p></div><div><strong>Usar consumos genéricos</strong><p>Nevera, portátil y cafetera cambian mucho según modelo, modo y temperatura.</p></div><div><strong>Olvidar los días</strong><p>La misma carga diaria requiere mucha más energía al pasar de una a tres noches.</p></div><div><strong>Mirar solo Wh</strong><p>La capacidad no garantiza que la salida soporte una cafetera o un pico de compresor.</p></div><div><strong>Confiar en sol perfecto</strong><p>Nubes, sombra, orientación y límites de entrada reducen la recuperación real.</p></div><div><strong>Confundir portátil con impermeable</strong><p>Transportable no significa que pueda quedarse expuesta a lluvia, polvo o calor.</p></div></div></div></section>

      <section className={`${styles.section} ${styles.faq}`} id="faq"><div className="container"><div className={styles.sectionHead}><p className={styles.index}>08 · Preguntas frecuentes</p><h2>Dudas sobre power stations para camping</h2></div><details><summary>¿Cuántos Wh necesito para un fin de semana de camping?</summary><p>Depende de los aparatos y horas. En nuestros ejemplos, móvil, cámara y luces rondan 154 Wh en dos días, mientras nevera, móviles y luces rondan 824 Wh antes del margen. Sustituye cada supuesto por tus consumos.</p></details><details><summary>¿Puede una power station alimentar una nevera portátil?</summary><p>Sí, si la salida es compatible y soporta consumo y arranque. Para autonomía, usa el consumo medido en Wh durante 24 horas, porque el compresor funciona por ciclos.</p></details><details><summary>¿Merece la pena llevar una placa solar?</summary><p>Suele aportar más en estancias largas, con nevera y una parcela soleada. Para un fin de semana con batería suficiente puede añadir peso y montaje sin ser necesaria.</p></details><details><summary>¿Qué potencia necesito para una cafetera de camping?</summary><p>Comprueba la potencia eléctrica de entrada de tu cafetera y suma las cargas que coincidan. En el ejemplo usamos 1.000 W durante cinco minutos, pero tu modelo puede ser muy distinto.</p></details><details><summary>¿Qué peso es razonable para camping?</summary><p>No hay un máximo universal. Considera distancia desde el coche, terreno y quién la moverá. En este catálogo, los modelos analizados van de 11,25 a 22 kg.</p></details></div></section>

      <section className={`${styles.section} ${styles.cta}`} id="calcular"><div className="container"><p className={styles.kicker}>Tu camping, tus números</p><h2>¿No te reconoces en estos escenarios?</h2><p>Añade tus propios aparatos, horas y días. La calculadora te ayuda a comparar el consumo con modelos del catálogo sin convertir un ejemplo editorial en una regla.</p><Link href="/encontrar-power-station">Calcular mi power station para camping →</Link></div></section>

      <section className={styles.sources}><div className="container"><p className={styles.index}>09 · Fuentes y metodología</p><h2>Qué es dato y qué es supuesto</h2><p>Capacidad, potencia, peso, entrada solar y puertos proceden de <code>src/content/products.ts</code>, cuyas fuentes de fabricante fueron verificadas el 20 de agosto de 2026. Los consumos, horas, días y margen del 20 % son supuestos editoriales creados para comparar escenarios; no proceden de pruebas físicas. Antes de elegir, usa etiquetas, manuales o mediciones de tus aparatos.</p></div></section>
    </article>
  </main><SiteFooter /></>;
}
