import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import styles from "../guide.module.css";
import anatomy from "./anatomy.module.css";

const slug="que-es-una-power-station", publishedAt="2026-08-21";
const siteUrl=process.env.NEXT_PUBLIC_SITE_URL??"http://localhost:3000";
const title="Qué es una power station y para qué sirve";
const seoTitle="Qué es una power station y cómo funciona | Carga Nómada";
const description="Descubre qué es una power station, cómo almacena y entrega energía, para qué sirve y qué debes mirar antes de elegir una estación portátil.";
export const metadata:Metadata={title:{absolute:seoTitle},description,alternates:{canonical:`/guias/${slug}`},openGraph:{type:"article",url:`/guias/${slug}`,title:seoTitle,description,siteName:"Carga Nómada",locale:"es_ES",publishedTime:publishedAt,modifiedTime:publishedAt},twitter:{card:"summary",title:seoTitle,description}};

export default function Guide(){const canonical=`${siteUrl}/guias/${slug}`;const schema={"@context":"https://schema.org","@graph":[{"@type":"BreadcrumbList","@id":`${canonical}#breadcrumb`,itemListElement:[{"@type":"ListItem",position:1,name:"Inicio",item:siteUrl},{"@type":"ListItem",position:2,name:"Guías",item:`${siteUrl}/guias`},{"@type":"ListItem",position:3,name:title,item:canonical}]},{"@type":"Article","@id":`${canonical}#article`,mainEntityOfPage:canonical,headline:title,description,datePublished:publishedAt,dateModified:publishedAt,inLanguage:"es",isAccessibleForFree:true,author:{"@id":`${siteUrl}#organization`},publisher:{"@id":`${siteUrl}#organization`},breadcrumb:{"@id":`${canonical}#breadcrumb`}}]};return <><main className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/>
<header className={styles.hero}><div className="container"><nav className={styles.breadcrumb} aria-label="Migas de pan"><Link href="/">Inicio</Link><span>/</span><Link href="/guias">Guías</Link><span>/</span><span>Qué es una power station</span></nav><p className={styles.kicker}>Guía básica · Desde cero</p><h1>Qué es una power station y para qué sirve</h1><p className={styles.lead}>Una power station es una batería portátil que almacena electricidad y la entrega mediante enchufes, USB y salidas de 12 V. Puedes cargarla desde la red, el vehículo o placas solares y utilizarla donde no tienes un enchufe cerca.</p><div className={styles.byline}><span>Equipo editorial de Carga Nómada</span><span>Publicado y revisado el 21 de agosto de 2026</span></div></div></header>
<div className="container"><section className={styles.quick} aria-labelledby="resumen"><div><p className={styles.kicker}>En pocas palabras</p><h2 id="resumen">Energía guardada, lista para llevar</h2></div><div className={styles.formula} role="img" aria-label="Batería más control y protección más salidas eléctricas"><span>Batería</span><i/><span>Control y protección</span><b>+</b><strong>salidas eléctricas</strong></div><p>No genera energía por sí sola. Primero debes cargarla; después actúa como una reserva silenciosa y transportable para equipos compatibles.</p></section><div className={styles.layout}><article className={styles.article}>
<section id="definicion"><p className={styles.index}>01 · La idea esencial</p><h2>Una batería portátil con algo más que USB</h2><p>La forma más sencilla de entenderla es imaginar una batería externa grande, pero preparada para más aparatos. Además de cargar un móvil, puede ofrecer enchufes AC, USB-C potentes y tomas de 12 V. Dentro integra batería, electrónica de control, protecciones y un inversor para crear corriente alterna.</p><p>“Power station”, “estación de energía portátil” y “estación eléctrica portátil” suelen describir la misma categoría. El nombre no garantiza una capacidad o potencia concreta: una unidad para camping ligero y otra destinada a una instalación off-grid trabajan a escalas muy distintas.</p></section>
<section id="partes"><p className={styles.index}>02 · Por dentro</p><h2>Las piezas que hacen el trabajo</h2><div className={anatomy.grid}><article><strong>Batería</strong><p>Almacena energía, medida normalmente en Wh.</p></article><article><strong>BMS</strong><p>Supervisa batería, temperatura y límites.</p></article><article><strong>Inversor</strong><p>Alimenta los enchufes de corriente alterna.</p></article><article><strong>Cargadores</strong><p>Gestionan red, vehículo y entrada solar.</p></article><article><strong>Salidas</strong><p>Reparten energía mediante AC, USB y DC.</p></article><article><strong>Pantalla</strong><p>Muestra carga, entrada y consumo estimado.</p></article></div><p>Una batería grande con un inversor pequeño tendrá mucha energía, pero no podrá sostener aparatos potentes. Un inversor enorme con poca batería podrá encender una carga exigente, aunque durante poco tiempo.</p></section>
<section id="funciona"><p className={styles.index}>03 · El ciclo</p><h2>Cómo funciona una power station</h2><ol className={styles.steps}><li><strong>Recibe energía.</strong><span>La cargas desde un enchufe, vehículo o panel compatible.</span></li><li><strong>La almacena.</strong><span>La batería conserva esa energía en corriente continua.</span></li><li><strong>La controla.</strong><span>El BMS vigila temperatura, voltaje y corriente.</span></li><li><strong>La entrega.</strong><span>USB y DC usan corriente continua; el inversor alimenta AC.</span></li></ol><p>En cada conversión se pierde una parte de la energía como calor. Por eso la capacidad nominal no llega completa a tus aparatos y la autonomía cambia según la salida, el consumo y las condiciones.</p></section>
<section id="usos"><p className={styles.index}>04 · Usos reales</p><h2>Para qué sirve</h2><div className={styles.tableWrap}><table><thead><tr><th>Situación</th><th>Equipos habituales</th><th>Qué calcular</th></tr></thead><tbody><tr><td>Camping</td><td>Luces, móvil, cámara, nevera</td><td>Wh diarios y peso</td></tr><tr><td>Camper</td><td>Portátil, router y Starlink</td><td>Recarga y puertos</td></tr><tr><td>Caravana</td><td>Varios aparatos</td><td>Simultaneidad</td></tr><tr><td>Emergencia</td><td>Router, luces y esenciales</td><td>Prioridades y duración</td></tr><tr><td>Trabajo móvil</td><td>Electrónica o herramientas</td><td>Potencia y picos</td></tr></tbody></table></div><p>Son escenarios, no garantías. Para un equipo concreto revisa nuestra guía sobre <Link href="/guias/que-puedo-conectar-power-station">qué puedes conectar a una power station</Link>.</p></section>
<section id="diferencias"><p className={styles.index}>05 · No es lo mismo</p><h2>Power station, power bank y generador</h2><h3>Power bank</h3><p>Suele centrarse en USB y electrónica pequeña. Una power station añade más capacidad, enchufes AC, salidas DC y refrigeración para cargas mayores. Mira las especificaciones, no solo el nombre comercial.</p><h3>Generador de combustible</h3><p>La power station no quema combustible durante el uso: es silenciosa en comparación y no produce gases de escape. A cambio, su energía es limitada y necesita recarga. Un generador puede seguir produciendo con combustible, pero añade ruido, mantenimiento y emisiones y nunca debe usarse en interiores.</p><h3>Batería auxiliar fija</h3><p>Una instalación fija se adapta mejor al vehículo, pero exige diseño y montaje. La power station reúne los componentes en una caja transportable y simplifica el inicio, aunque ofrece menos libertad para reparar o ampliar piezas.</p></section>
<section id="cifras"><p className={styles.index}>06 · Antes de comparar</p><h2>Las cifras que importan</h2><ul className={styles.factorList}><li><strong>Wh:</strong> energía almacenada y duración posible.</li><li><strong>W continuos:</strong> consumo que puede sostener.</li><li><strong>W de pico:</strong> margen breve para arranques.</li><li><strong>Entradas:</strong> forma y velocidad de recarga.</li><li><strong>Salidas:</strong> compatibilidad con aparatos y cables.</li><li><strong>Peso:</strong> determina si será portátil en tu rutina.</li></ul><aside className={styles.callout}><strong>No confundas capacidad y potencia</strong><p>Los Wh se parecen al tamaño del depósito; los W describen el ritmo al que utilizas la energía.</p></aside></section>
<section id="limites"><p className={styles.index}>07 · Expectativas realistas</p><h2>Qué no puede hacer</h2><p>No ofrece energía infinita ni admite cualquier aparato. Calefactores, placas y cafeteras pueden exigir mucha potencia o agotar pronto la batería. Bombas y neveras pueden tener picos aunque después consuman poco.</p><p>Tampoco trates cualquier función UPS como garantía para equipos críticos. Comprueba compatibilidad y certificaciones. Instalaciones fijas, equipos médicos y conexiones a viviendas requieren documentación vigente y profesionales cualificados.</p></section>
<section id="errores"><p className={styles.index}>08 · Evita estas trampas</p><h2>Errores frecuentes al elegir</h2><div className={styles.mistakes}><div><strong>Comprar por W máximos</strong><p>Mucha potencia no compensa poca batería.</p></div><div><strong>Ignorar el peso</strong><p>“Portátil” puede significar decenas de kilos.</p></div><div><strong>Calcular un aparato</strong><p>Router, luces y cargadores también consumen.</p></div><div><strong>Confiar en ideales</strong><p>Autonomía y carga solar varían.</p></div></div></section>
<section id="comprar"><p className={styles.index}>09 · Decisión</p><h2>Qué significa esto al comprar</h2><p>Lista tus aparatos, apunta sus W y horas de uso, suma los Wh diarios y comprueba qué funcionará a la vez. Decide cuándo podrás recargar y busca margen razonable, sin comprar capacidad solo por miedo.</p><p>Para camping puedes ver la <Link href="/reviews/fossibot-f1200-review">review de la FOSSiBOT F1200</Link>. Si trabajas conectado y valoras más entrada solar, consulta la <Link href="/reviews/fossibot-f1800-review">review de la FOSSiBOT F1800</Link>.</p></section>
<section id="faq" className={styles.faq}><p className={styles.index}>10 · Preguntas frecuentes</p><h2>Dudas básicas</h2><details><summary>¿Genera electricidad?</summary><p>No. Almacena energía de la red, vehículo o paneles y la entrega después.</p></details><details><summary>¿Puede usarse dentro de casa?</summary><p>No produce gases durante el uso, pero debe estar seca, ventilada y dentro de las condiciones del fabricante.</p></details><details><summary>¿Cuánto dura?</summary><p>Depende de Wh, consumo y pérdidas. Usa nuestra <Link href="/guias/calcular-autonomia-power-station">guía de autonomía</Link>.</p></details><details><summary>¿Puede cargarse con placas?</summary><p>Sí, si son compatibles. Consulta la guía de <Link href="/guias/placas-solares-power-station">placas solares</Link>.</p></details></section>
<section id="siguiente"><p className={styles.index}>11 · Siguiente paso</p><h2>Convierte la idea en números</h2><div className={styles.nextGrid}><div><h3>Sigue aprendiendo</h3><Link href="/guias/calcular-autonomia-power-station">Calcular autonomía →</Link></div><div><h3>Mira cómo se aplica</h3><Link href="/reviews">Explorar las reviews →</Link></div></div></section>
<section className={styles.sources}><p className={styles.index}>12 · Metodología</p><h2>Cómo se ha preparado</h2><p>Separamos conceptos generales de prestaciones de modelos. Para productos concretos usamos fichas verificadas y declaramos los cálculos como estimaciones. El manual vigente prevalece en instalaciones y usos críticos.</p></section>
</article><aside className={styles.aside} aria-label="Contenido"><span>En esta guía</span><a href="#definicion">Definición</a><a href="#partes">Sus partes</a><a href="#funciona">Cómo funciona</a><a href="#usos">Usos</a><a href="#diferencias">Diferencias</a><a href="#cifras">Cifras</a><a href="#limites">Límites</a><a href="#faq">Preguntas</a></aside></div></div></main><SiteFooter/></>}
