import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { getProductById } from "@/content/products";
import styles from "../guide.module.css";
import solar from "./solar.module.css";

const slug = "placas-solares-power-station";
const publishedAt = "2026-08-21";
const modifiedAt = "2026-08-22";
const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
const title = "Cómo elegir placas solares para una power station";
const seoTitle = "Placas solares para power station: guía | Carga Nómada";
const description = "Aprende a elegir placas solares compatibles con tu power station: potencia, voltaje, amperios, conectores, tiempos de carga y seguridad.";

export const metadata: Metadata = { title: { absolute: seoTitle }, description, alternates: { canonical: `/guias/${slug}` }, openGraph: { type: "article", url: `/guias/${slug}`, title: seoTitle, description, siteName: "Carga Nómada", locale: "es_ES", publishedTime: publishedAt, modifiedTime: modifiedAt }, twitter: { card: "summary", title: seoTitle, description } };
const f1200 = getProductById("fossibot-f1200")!;
const f1800 = getProductById("fossibot-f1800")!;
const f2400 = getProductById("fossibot-f2400")!;

export default function SolarPanelsGuide() {
  const canonical = `${siteUrl}/guias/${slug}`;
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "BreadcrumbList", "@id": `${canonical}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Inicio", item: siteUrl }, { "@type": "ListItem", position: 2, name: "Guías", item: `${siteUrl}/guias` }, { "@type": "ListItem", position: 3, name: title, item: canonical }] },
    { "@type": "Article", "@id": `${canonical}#article`, mainEntityOfPage: canonical, headline: title, description, datePublished: publishedAt, dateModified: modifiedAt, inLanguage: "es", isAccessibleForFree: true, author: { "@id": `${siteUrl}#organization` }, publisher: { "@id": `${siteUrl}#organization` }, breadcrumb: { "@id": `${canonical}#breadcrumb` } },
  ] };
  return <><main className={styles.page}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
    <header className={styles.hero}><div className="container"><nav className={styles.breadcrumb} aria-label="Migas de pan"><Link href="/">Inicio</Link><span>/</span><Link href="/guias">Guías</Link><span>/</span><span>Placas solares</span></nav><p className={styles.kicker}>Guía práctica · Energía solar</p><h1>Cómo elegir placas solares para una power station</h1><p className={styles.lead}>Una placa es compatible cuando su voltaje, corriente, potencia, polaridad y conector encajan con la entrada solar de la power station. Los vatios del panel no bastan: comprueba primero los límites eléctricos y calcula después cuánto podrás recuperar con el sol disponible.</p><div className={styles.byline}><span>Equipo editorial de Carga Nómada</span><span>Publicado el 21 y revisado el 22 de agosto de 2026</span></div></div></header>
    <div className="container"><section className={styles.quick} aria-labelledby="respuesta-solar"><div><p className={styles.kicker}>En pocas palabras</p><h2 id="respuesta-solar">Comprueba el panel en este orden</h2></div><ol className={solar.checker} aria-label="Pasos para comprobar la compatibilidad de un panel solar"><li><span>01</span>Voc bajo el voltaje máximo</li><li><span>02</span>Vmp dentro del rango solar</li><li><span>03</span>Corriente compatible</li><li><span>04</span>Potencia admitida</li><li><span>05</span>Conector y polaridad correctos</li></ol><p>No conectes un panel solo porque anuncia menos vatios que la entrada solar. Superar el voltaje máximo puede dañar el equipo; sigue siempre el manual del fabricante.</p></section>
    <div className={styles.layout}><article className={styles.article}>
      <section id="como-funciona"><p className={styles.index}>01 · Desde cero</p><h2>Cómo llega la energía solar a tus aparatos</h2><p>El panel convierte la luz en corriente continua. Esa energía entra en el controlador MPPT de la power station, que busca un punto de trabajo eficiente y adapta la entrada para cargar la batería. Cuando conectas un aparato AC, el inversor vuelve a transformar la energía. Cada etapa tiene límites y pérdidas.</p><div className={solar.flow} role="img" aria-label="Recorrido de la energía desde el panel solar hasta los aparatos"><span>Panel<small>produce DC</small></span><b>→</b><span>MPPT<small>gestiona</small></span><b>→</b><span>Batería<small>almacena Wh</small></span><b>→</b><span>Inversor<small>convierte a AC</small></span><b>→</b><span>Aparatos<small>consumen W</small></span></div><p>El MPPT está integrado en muchas estaciones actuales, pero no elimina la necesidad de respetar su ficha eléctrica. Tampoco crea energía cuando el panel está sombreado: optimiza lo que recibe dentro de su rango.</p></section>
      <section id="compatibilidad"><p className={styles.index}>02 · Los datos decisivos</p><h2>Qué comprobar antes de conectar un panel</h2><p>En la power station busca el rango de tensión de entrada, el voltaje máximo, la corriente máxima, la potencia solar máxima y el tipo de conector. En la etiqueta o ficha del panel busca Voc, Vmp, Imp, Isc, potencia nominal, conectores y polaridad.</p><ol className={styles.steps}><li><strong>Rango de tensión solar.</strong><span>El Vmp del conjunto debe entrar en la ventana de funcionamiento y su Voc no debe superar el máximo, incluso con frío.</span></li><li><strong>Corriente máxima.</strong><span>Compara Imp e Isc del conjunto con las condiciones y límites declarados para cada entrada.</span></li><li><strong>Potencia solar máxima.</strong><span>Indica los vatios que la estación puede aprovechar, no una producción constante.</span></li><li><strong>Conector y polaridad.</strong><span>MC4, XT60, Anderson u otros formatos necesitan el cable correcto y una polaridad verificada.</span></li></ol><aside className={styles.callout}><strong>El orden importa</strong><p>Primero voltios, después amperios, luego vatios y finalmente conector. Un adaptador solo cambia la conexión física; no vuelve compatible un panel que eléctricamente no lo es.</p></aside><p>Un conjunto puede sumar más potencia nominal que la entrada puede aprovechar, pero no asumas que ese sobredimensionado es seguro. Solo debe plantearse cuando el fabricante lo permita y la configuración completa respete tensión, corriente y demás condiciones del manual.</p></section>
      <section id="etiqueta"><p className={styles.index}>03 · Leer la etiqueta</p><h2>Voc, Vmp, Isc e Imp sin complicarte</h2><p><strong>Voc</strong> es la tensión de circuito abierto y la referencia crítica para no superar el máximo de entrada. <strong>Vmp</strong> es la tensión aproximada cuando el panel trabaja cerca de su punto de máxima potencia. <strong>Isc</strong> es la corriente de cortocircuito e <strong>Imp</strong>, la corriente de trabajo óptimo. En términos sencillos, V es tensión, A es corriente y W es potencia; cerca del punto de trabajo, V × A ≈ W.</p><div className={styles.tableWrap}><table><thead><tr><th>Dato</th><th>Dónde mirarlo</th><th>Para qué sirve</th></tr></thead><tbody><tr><td>Voc</td><td>Panel</td><td>Comprobar el voltaje máximo con margen</td></tr><tr><td>Vmp</td><td>Panel</td><td>Comprobar el rango de funcionamiento</td></tr><tr><td>Isc / Imp</td><td>Panel</td><td>Validar la corriente del conjunto</td></tr><tr><td>W nominales</td><td>Panel</td><td>Conocer la potencia pico, no la energía diaria</td></tr><tr><td>Rango solar</td><td>Power station</td><td>Conocer la tensión de trabajo aceptada</td></tr><tr><td>A máximos</td><td>Power station</td><td>Conocer la corriente admitida</td></tr><tr><td>W solares máximos</td><td>Power station</td><td>Conocer la potencia que puede aprovechar</td></tr></tbody></table></div><p>Dos configuraciones pueden sumar los mismos W y trabajar a tensiones muy diferentes: una puede ser compatible y otra superar la entrada. Además, el voltaje suele aumentar con el frío. No diseñes una serie pegada al máximo usando únicamente el Voc en condiciones estándar; consulta el coeficiente de temperatura del panel y el manual de la estación.</p></section>
      <section id="serie-paralelo"><p className={styles.index}>04 · Combinar paneles</p><h2>Serie y paralelo cambian cosas distintas</h2><p>Con paneles iguales <strong>en serie</strong>, se suman los voltajes y la corriente se mantiene aproximadamente. <strong>En paralelo</strong>, se mantiene el voltaje y se suman las corrientes. La opción correcta es la que deja todo el conjunto dentro de la ventana de entrada.</p><div className={styles.exampleGrid}><article><span>Dos paneles en serie</span><strong>≈ 40 V · 5 A</strong><code>20 V + 20 V; corriente ≈ 5 A</code><p>Potencia ideal total: unos 200 W.</p></article><article><span>Dos paneles en paralelo</span><strong>≈ 20 V · 10 A</strong><code>voltaje ≈ 20 V; 5 A + 5 A</code><p>Potencia ideal total: unos 200 W.</p></article></div><p>Son ejemplos didácticos con dos paneles iguales de 20 V y 5 A, no instrucciones para un modelo real. No mezcles paneles distintos sin entender sus curvas. En serie, una sombra puede condicionar la cadena; en paralelo necesitas cables y conectores preparados para más corriente. Una instalación fija requiere protecciones y cálculo profesional.</p></section>
      <section id="tiempo"><p className={styles.index}>05 · Cálculo orientativo</p><h2>Cuánto tarda en cargar con placas solares</h2><p>Divide la energía que necesitas reponer entre la potencia solar media que realmente entra. No uses automáticamente los vatios nominales del panel: rara vez se mantienen durante toda la jornada.</p><div className={styles.equation}><small>Estimación de carga</small><code>Wh que debes reponer ÷ W solares medios = horas útiles</code><code>1.024 Wh ÷ 160 W ≈ 6,4 horas</code><p>Ejemplo simplificado. No incluye la reducción al final de la carga, consumos simultáneos ni otras pérdidas.</p></div><p>Si un panel de 200 W entrega una media de 140 W durante cuatro horas útiles, aporta unos 560 Wh antes de pérdidas adicionales. Orientación, sombras, nubes, temperatura, estación del año y suciedad cambian el resultado. Si alimentas una nevera mientras cargas, resta su consumo de la entrada para conocer el balance neto.</p></section>
      <section id="modelos"><p className={styles.index}>06 · Aplicado a tres tamaños</p><h2>Entradas solares de 200 y 500 W</h2><p>La F1200 admite hasta {f1200.charging?.maxSolarInputWatts?.toLocaleString("es-ES")} W solares. El fabricante declara unas 6,5 horas del 0 al 100 % a 200 W bajo sol óptimo y orientación ideal: es una referencia oficial, no una promesa diaria. Consulta la <Link href="/reviews/fossibot-f1200-review">review de la FOSSiBOT F1200 para camping</Link>.</p><p>La F1800 sube a {f1800.charging?.maxSolarInputWatts?.toLocaleString("es-ES")} W y conserva {f1800.capacityWh.toLocaleString("es-ES")} Wh. Su tiempo oficial es de unas dos horas a 500 W en condiciones ideales. Esa entrada puede recuperar antes la batería si los paneles y el sol se acercan a ese valor.</p><p>La F2400 combina {f2400.capacityWh.toLocaleString("es-ES")} Wh con hasta {f2400.charging?.maxSolarInputWatts?.toLocaleString("es-ES")} W solares. El fabricante declara unas cuatro horas a 500 W en condiciones ideales. La <Link href="/reviews/fossibot-f2400-review">review de la FOSSiBOT F2400 para caravana</Link> muestra por qué una batería mayor necesita planificación.</p><p>El catálogo no almacena aún los rangos de voltaje y corriente de estos modelos. Debes validarlos en el manual vigente antes de elegir o combinar paneles.</p></section>
      <section id="real"><p className={styles.index}>07 · El mundo real</p><h2>Por qué 200 W no son siempre 200 W</h2><ul className={styles.factorList}><li><strong>Ángulo:</strong> el panel rinde mejor cuando recibe el sol de forma directa.</li><li><strong>Sombras:</strong> una rama o una parte de la baca puede reducir mucho la producción; el efecto exacto depende del panel, la electrónica y la configuración.</li><li><strong>Temperatura:</strong> el calor suele reducir la potencia de la célula.</li><li><strong>Nubes y estación:</strong> alteran potencia instantánea y horas útiles.</li><li><strong>Cables:</strong> longitud, sección y conexiones provocan caídas.</li><li><strong>Potencia aprovechable:</strong> incluso una configuración eléctricamente compatible queda limitada por la entrada solar máxima.</li></ul><p>Mide los Wh recuperados durante varios días, no solo el máximo de W visto unos segundos. La energía diaria dice si repones lo gastado; el pico únicamente confirma un momento favorable.</p><h3>Panel plegable o panel rígido</h3><p>Un panel plegable es portátil, se guarda con facilidad y permite corregir su orientación, pero hay que desplegarlo cada vez y soporta más manipulación. Un panel rígido encaja mejor en una instalación permanente correctamente diseñada, aunque exige resolver fijación, cableado, protección e integración. El formato no sustituye la comprobación eléctrica.</p></section>
      <section id="errores"><p className={styles.index}>08 · Evita estas trampas</p><h2>Errores frecuentes con placas solares</h2><div className={styles.mistakes}><div><strong>Elegir solo por vatios</strong><p>Dos conjuntos de 400 W pueden tener voltajes y corrientes distintos.</p></div><div><strong>Superar el Voc máximo</strong><p>Calcula también el aumento de tensión provocado por el frío.</p></div><div><strong>Sumar mal varios paneles</strong><p>La serie suma tensión; el paralelo aumenta la corriente del conjunto.</p></div><div><strong>Confiar en MC4 o un adaptador</strong><p>Que encaje no demuestra compatibilidad ni polaridad correcta.</p></div><div><strong>Esperar potencia constante</strong><p>Wp describe condiciones estándar, no todas las horas reales.</p></div><div><strong>Dejar la estación al sol</strong><p>El panel necesita luz; la batería debe mantenerse dentro de su temperatura y ventilación admitidas.</p></div><div><strong>Ponerlo tras un cristal</strong><p>Ventanas y parabrisas reducen irradiación y pueden concentrar calor.</p></div><div><strong>Olvidar lo que consumes</strong><p>Si entran 180 W y usas 100 W, el balance para cargar ronda 80 W.</p></div></div></section>
      <section id="elegir"><p className={styles.index}>09 · Antes de comprar</p><h2>Qué panel necesitas realmente</h2><p>Empieza por tu energía diaria. Si gastas 600 Wh y esperas cuatro horas solares útiles, necesitas una media neta de 150 W solo para equilibrar el día. Como existe variabilidad y pérdidas, necesitarás margen o adaptar hábitos cuando haga mal tiempo.</p><ol className={styles.steps}><li><strong>Calcula tus Wh diarios.</strong><span>Usa nuestra guía de <Link href="/guias/calcular-autonomia-power-station">autonomía</Link>.</span></li><li><strong>Define dónde y cuándo viajas.</strong><span>Invierno, latitud y sombra reducen las horas útiles.</span></li><li><strong>Valida la entrada.</strong><span>Confirma MPPT, voltaje máximo, corriente, potencia y conectores.</span></li><li><strong>Elige portátil o fijo.</strong><span>Un panel plegable se orienta; uno rígido encaja mejor en instalaciones permanentes.</span></li><li><strong>Comprueba cables.</strong><span>Polaridad, longitud, sección y resistencia exterior importan.</span></li></ol><p>Después revisa <Link href="/guias/que-puedo-conectar-power-station">qué aparatos puedes conectar</Link>: un buen balance solar no compensa una salida insuficiente.</p></section>
      <section id="seguridad"><p className={styles.index}>10 · Uso responsable</p><h2>Seguridad y cuidado del equipo</h2><p>Mantén conectores secos, limpios y sin tensión mecánica. Protege los cables de bordes, pisadas y calor. No coloques la estación a pleno sol solo porque el panel deba estar fuera: la batería necesita ventilación y respetar su temperatura de trabajo.</p><p>Una serie de alta tensión o una instalación fija exige protecciones, estructura y conocimientos eléctricos. Si no puedes verificar Voc, corriente, polaridad o puesta a tierra, detente y consulta al fabricante o a un instalador cualificado.</p></section>
      <section id="faq" className={styles.faq}><p className={styles.index}>11 · Preguntas frecuentes</p><h2>Dudas sobre placas solares y power stations</h2><details><summary>¿Puedo conectar cualquier placa solar a una power station?</summary><p>No. Deben coincidir tensión, corriente, potencia, conector y polaridad con los límites indicados en el manual.</p></details><details><summary>¿Puedo instalar más vatios que la entrada máxima?</summary><p>Solo si el fabricante lo autoriza y voltaje y corriente siguen dentro de sus condiciones. Nunca superes el voltaje máximo confiando en que la estación recortará potencia.</p></details><details><summary>¿Puedo conectar dos placas solares?</summary><p>Sí, si la configuración completa respeta voltaje, corriente, potencia, conectores y polaridad. Recuerda que la serie suma tensión y el paralelo suma corriente.</p></details><details><summary>¿Cuánto tarda la carga solar?</summary><p>Divide los Wh que debes reponer entre la potencia solar media real y ajusta por pérdidas, consumo simultáneo y reducción al final de carga.</p></details><details><summary>¿Puedo usar paneles de otra marca?</summary><p>La marca no decide por sí sola la compatibilidad. Comprueba todas las especificaciones eléctricas, el conector y la polaridad, y sigue los accesorios admitidos por el fabricante.</p></details><details><summary>¿Puedo cargar y usar la estación a la vez?</summary><p>Algunos modelos lo permiten. Comprueba el manual y recuerda que el consumo activo reduce la energía neta que llega a la batería.</p></details></section>
      <section id="siguiente"><p className={styles.index}>12 · Siguiente paso</p><h2>Cierra tu balance energético</h2><div className={styles.nextGrid}><div><h3>Sigue aprendiendo</h3><p>Calcula consumo y cargas antes de dimensionar paneles.</p><Link href="/guias/calcular-autonomia-power-station">Calcular autonomía →</Link></div><div><h3>Mira cómo se aplica</h3><p>Contrasta entrada solar, capacidad y escenario.</p><Link href="/reviews">Explorar las reviews →</Link></div></div></section>
      <section id="metodologia" className={styles.sources}><p className={styles.index}>13 · Fuentes y metodología</p><h2>De dónde salen los datos</h2><p>Las capacidades, entradas solares máximas y tiempos oficiales proceden de las fichas de fabricante de la <a href={f1200.source.url}>FOSSiBOT F1200</a>, la <a href={f1800.source.url}>FOSSiBOT F1800</a> y la <a href={f2400.source.url}>FOSSiBOT F2400</a>, verificadas en el catálogo del proyecto el 20 de agosto de 2026. Los cálculos son ejemplos editoriales orientativos. Antes de montar paneles, prevalecen el manual vigente, la etiqueta del panel y la normativa aplicable.</p></section>
    </article><aside className={styles.aside} aria-label="Contenido de la guía"><span>En esta guía</span><a href="#como-funciona">Cómo funciona</a><a href="#compatibilidad">Compatibilidad</a><a href="#etiqueta">La etiqueta</a><a href="#serie-paralelo">Serie o paralelo</a><a href="#tiempo">Tiempo de carga</a><a href="#modelos">Ejemplos</a><a href="#errores">Errores</a><a href="#faq">Preguntas</a></aside></div></div>
  </main><SiteFooter/></>;
}
