"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { applianceDailyWh, dailyWh, estimatedDays, minimumNominalWh, powerAssessment, productFit, recommendedWh, sortProductsByFit, tripWh, type CalculatorProduct, type PowerAssessment } from "@/lib/autonomy-calculator";
import styles from "./autonomy-calculator.module.css";

type Mode="need"|"duration";
type Item={id:string;name:string;watts:string;hours:string;quantity:string;measured:boolean;measuredWh:string;preset:boolean};
const presets=[{name:"Nevera portátil",watts:"45",hours:"8"},{name:"Portátil",watts:"60",hours:"4"},{name:"Starlink",watts:"70",hours:"6"},{name:"Móvil",watts:"15",hours:"2"},{name:"Luces",watts:"20",hours:"5"},{name:"Cafetera",watts:"1000",hours:"0,1"},{name:"Router",watts:"15",hours:"12"}] as const;
const parse=(value:string)=>{const number=Number(value.replace(",","."));return Number.isFinite(number)?number:0};
const format=(value:number,digits=0)=>new Intl.NumberFormat("es-ES",{maximumFractionDigits:digits}).format(value);
const makeItem=(preset?:typeof presets[number]):Item=>({id:`item-${Date.now()}-${Math.random()}`,name:preset?.name??"Otro aparato",watts:preset?.watts??"",hours:preset?.hours??"",quantity:"1",measured:false,measuredWh:"",preset:Boolean(preset)});
const statusLabel={good:"Buen encaje",tight:"Ajustada",short:"Se queda corta",more:"Más margen"} as const;

export function AutonomyCalculator({products}: {products:CalculatorProduct[]}){
 const [mode,setMode]=useState<Mode>("need"),[items,setItems]=useState<Item[]>([]),[days,setDays]=useState("2"),[usable,setUsable]=useState("85"),[reserve,setReserve]=useState("15"),[selected,setSelected]=useState(products[0]?.id??"manual"),[manual,setManual]=useState(false),[manualCapacity,setManualCapacity]=useState("1500"),[manualPower,setManualPower]=useState("");
 const resultRef=useRef<HTMLHeadingElement>(null);
 const values=useMemo(()=>items.map(item=>({watts:parse(item.watts),hoursPerDay:parse(item.hours),quantity:parse(item.quantity),measuredDailyWh:item.measured?parse(item.measuredWh):null})),[items]);
 const daily=dailyWh(values),powerState=powerAssessment(values),simultaneous=powerState.knownSimultaneousWatts,dayCount=parse(days),usableFraction=parse(usable)/100,reserveFraction=parse(reserve)/100,useful=tripWh(daily,dayCount),minimum=minimumNominalWh(useful,usableFraction),target=recommendedWh(minimum,reserveFraction);
 const unknownPowerNames=items.filter((_,index)=>applianceDailyWh(values[index])>0&&parse(items[index].watts)<=0).map(item=>item.name.trim()||"Aparato sin nombre");
 const chosen=products.find(product=>product.id===selected),capacity=manual?parse(manualCapacity):chosen?.capacityWh??0,power=manual?parse(manualPower):chosen?.continuousOutputWatts??0,duration=estimatedDays(capacity,usableFraction,daily);
 const errors=useMemo(()=>items.flatMap(item=>{const list:string[]=[];if(!item.name.trim())list.push("Escribe un nombre para cada aparato.");if(parse(item.watts)<0||parse(item.quantity)<=0)list.push(`${item.name}: potencia y cantidad deben ser positivas.`);if(!item.measured&&(parse(item.hours)<0||parse(item.hours)>24))list.push(`${item.name}: las horas al día deben estar entre 0 y 24.`);if(item.measured&&parse(item.measuredWh)<0)list.push(`${item.name}: el consumo medido no puede ser negativo.`);return list}),[items]);
 const assumptionError=usableFraction<=0||usableFraction>1||reserveFraction<0||reserveFraction>1?"Usa porcentajes entre 1–100 % para energía utilizable y 0–100 % para margen.":"";
 const modeError=mode==="need"&&dayCount<1?"Introduce al menos un día sin recargar.":mode==="duration"&&capacity<=0?"Introduce una capacidad mayor que 0 Wh.":mode==="duration"&&manual&&parse(manualPower)<0?"La potencia continua no puede ser negativa.":"";
 const hasResult=items.length>0&&daily>0&&!errors.length&&!assumptionError&&!modeError;
 const update=(id:string,patch:Partial<Item>)=>setItems(current=>current.map(item=>item.id===id?{...item,...patch}:item));
 const add=(preset?:typeof presets[number])=>setItems(current=>[...current,makeItem(preset)]);
 const showResult=()=>{const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;resultRef.current?.scrollIntoView({behavior:reduced?"auto":"smooth",block:"start"});resultRef.current?.focus({preventScroll:true})};
 const selectedPowerInsufficient=mode==="duration"&&power>0&&simultaneous>power;

 return <section id="calculadora" className={styles.shell} aria-labelledby="calculator-title">
  <header className={styles.header}><div><p>Herramienta · Calculadora de autonomía</p><h2 id="calculator-title">Calcula la batería que realmente necesitas</h2><span>Añade tus aparatos y convierte tus consumos en una capacidad orientativa.</span></div><b>Estimación</b></header>
  <div className={styles.columns}><div className={styles.controls}>
   <fieldset className={styles.mode}><legend>¿Qué quieres saber?</legend><div><button type="button" aria-pressed={mode==="need"} onClick={()=>setMode("need")}>Qué capacidad necesito</button><button type="button" aria-pressed={mode==="duration"} onClick={()=>setMode("duration")}>Cuánto me durará una batería</button></div></fieldset>
   {mode==="need"?<div className={styles.days}><label htmlFor="calculator-days">Días sin recargar</label><div><button type="button" aria-label="Restar un día" onClick={()=>setDays(String(Math.max(1,dayCount-1)))}>−</button><input id="calculator-days" value={days} onChange={e=>setDays(e.target.value)} inputMode="decimal" aria-describedby="days-error"/><span>días</span><button type="button" aria-label="Añadir un día" onClick={()=>setDays(String(Math.max(1,dayCount+1)))}>+</button></div>{dayCount<1&&<p id="days-error" className={styles.error}>Introduce al menos un día.</p>}</div>:<fieldset className={styles.station}><legend>Elige tu power station</legend><label><span>Modelo</span><select value={selected} disabled={manual} onChange={e=>setSelected(e.target.value)}>{products.map(product=><option key={product.id} value={product.id}>{product.name} · {format(product.capacityWh)} Wh</option>)}</select></label><label className={styles.check}><input type="checkbox" checked={manual} onChange={e=>setManual(e.target.checked)}/><span>Introducir otra capacidad</span></label>{manual&&<div className={styles.manual}><NumberField id="manual-capacity" label="Capacidad" value={manualCapacity} onChange={setManualCapacity} unit="Wh"/><NumberField id="manual-power" label="Potencia continua (opcional)" value={manualPower} onChange={setManualPower} unit="W"/></div>}</fieldset>}
   <div className={styles.presets}><h3>Aparatos rápidos</h3><p>Referencias editoriales editables.</p><div>{presets.map(preset=><button type="button" key={preset.name} onClick={()=>add(preset)}>+ {preset.name}</button>)}<button type="button" onClick={()=>add()}>+ Otro</button></div></div>
   <div className={styles.items}>{items.map((item,index)=><article key={item.id} className={styles.item}><div className={styles.itemHead}><label><span>Aparato {index+1}</span><input value={item.name} onChange={e=>update(item.id,{name:e.target.value,preset:false})}/></label><div><button type="button" title="Duplicar aparato" aria-label={`Duplicar ${item.name}`} onClick={()=>setItems(current=>[...current,{...item,id:`item-${Date.now()}-${Math.random()}`}])}>Duplicar</button><button type="button" aria-label={`Eliminar ${item.name}`} onClick={()=>setItems(current=>current.filter(entry=>entry.id!==item.id))}>×</button></div></div>{item.preset&&<p className={styles.reference}>Referencia editable</p>}<label className={styles.check}><input type="checkbox" checked={item.measured} onChange={e=>update(item.id,{measured:e.target.checked})}/><span>Sé mi consumo diario en Wh</span></label><div className={styles.itemFields}><NumberField id={`${item.id}-watts`} label={item.measured?"Potencia para comparar":"Potencia"} value={item.watts} onChange={value=>update(item.id,{watts:value})} unit="W"/>{item.measured?<NumberField id={`${item.id}-measured`} label="Consumo medido" value={item.measuredWh} onChange={value=>update(item.id,{measuredWh:value})} unit="Wh/día"/>:<NumberField id={`${item.id}-hours`} label="Uso diario" value={item.hours} onChange={value=>update(item.id,{hours:value})} unit="h"/>}<NumberField id={`${item.id}-quantity`} label="Cantidad" value={item.quantity} onChange={value=>update(item.id,{quantity:value})}/></div><footer><span>Consumo diario</span><strong>{format(applianceDailyWh(values[index]),1)} Wh/día</strong></footer></article>)}</div>
   <button className={styles.add} type="button" onClick={()=>add()}>+ Añadir otro aparato</button>
   {(errors.length>0||assumptionError||modeError)&&<div className={styles.errors} role="alert">{errors.map((error,index)=><p key={`${error}-${index}`}>{error}</p>)}{assumptionError&&<p>{assumptionError}</p>}{modeError&&<p>{modeError}</p>}</div>}
   <details className={styles.assumptions}><summary>Supuestos del cálculo</summary><div><NumberField id="usable-energy" label="Energía utilizable" value={usable} onChange={setUsable} unit="%"/><NumberField id="reserve" label="Margen adicional" value={reserve} onChange={setReserve} unit="%"/></div><p>Son supuestos editoriales para obtener una referencia práctica. No representan una medición del rendimiento real de todos los productos.</p></details>
   <button className={styles.mobileResult} type="button" onClick={showResult}>Ver mi resultado</button>
   </div><aside className={styles.results}>{!hasResult?<div className={styles.empty}><span>Resultado transparente</span><h2 ref={resultRef} tabIndex={-1}>Tu resultado aparecerá aquí</h2><p>Añade al menos un aparato con consumo para empezar.</p></div>:<><p style={{position:"absolute",width:1,height:1,padding:0,margin:-1,overflow:"hidden",clip:"rect(0, 0, 0, 0)",whiteSpace:"nowrap",border:0}} aria-live="polite" aria-atomic="true">{mode==="need"?`Capacidad recomendada: aproximadamente ${format(target)} Wh.`:`Autonomía estimada: aproximadamente ${format(duration,1)} días.`}</p><div className={styles.resultTop}><p>Tu consumo</p><strong>{format(daily,1)} Wh/día</strong></div>{mode==="need"?<NeedResult resultRef={resultRef} days={dayCount} useful={useful} minimum={minimum} target={target} daily={daily} usable={usableFraction} reserve={reserveFraction}/>:<DurationResult resultRef={resultRef} days={duration} capacity={capacity} usableWh={capacity*usableFraction} daily={daily}/>}<div className={styles.power}><span>{powerState.status==="complete"?"Si todos coincidieran":"Potencia conocida si coincidieran"}</span>{powerState.status!=="unknown"&&<strong>{format(simultaneous)} W</strong>}<p>{powerState.status==="complete"?"Potencia completamente evaluada. Es un escenario conservador; neveras, bombas y herramientas pueden tener picos adicionales.":powerState.status==="partial"?`Evaluación de potencia parcial. Falta conocer la potencia de: ${unknownPowerNames.join(", ")}.`:`Potencia no evaluada. Falta conocer la potencia de: ${unknownPowerNames.join(", ")}.`}</p>{selectedPowerInsufficient&&<b>La potencia continua elegida quedaría por debajo del escenario conocido.</b>}</div>{mode==="need"&&<ProductMatches products={products} minimum={minimum} target={target} assessment={powerState}/>}</>}</aside></div>
 </section>
}

function NumberField({id,label,value,onChange,unit}:{id:string;label:string;value:string;onChange:(value:string)=>void;unit?:string}){return <label className={styles.number}><span>{label}</span><div><input id={id} value={value} onChange={e=>onChange(e.target.value)} inputMode="decimal" aria-label={`${label}${unit?` en ${unit}`:""}`}/>{unit&&<b>{unit}</b>}</div></label>}
function NeedResult({resultRef,days,useful,minimum,target,daily,usable,reserve}:{resultRef:React.RefObject<HTMLHeadingElement|null>;days:number;useful:number;minimum:number;target:number;daily:number;usable:number;reserve:number}){return <><div className={styles.mainResult}><span>Para {format(days,1)} días · {format(useful)} Wh útiles</span><h2 ref={resultRef} tabIndex={-1}>Capacidad recomendada</h2><strong>≈ {format(target)} Wh</strong><p>Con tus consumos y supuestos actuales, buscaría alrededor de {format(target)} Wh o más si quieres completar el periodo sin recargar.</p></div><details className={styles.math}><summary>¿Cómo sale este cálculo?</summary><code>{format(daily,1)} Wh/día × {format(days,1)} días<br/>= {format(useful)} Wh<br/><br/>{format(useful)} ÷ {usable.toLocaleString("es-ES")}<br/>= {format(minimum)} Wh nominales<br/><br/>{format(minimum)} × {(1+reserve).toLocaleString("es-ES")}<br/>≈ {format(target)} Wh recomendados</code></details></>}
function DurationResult({resultRef,days,capacity,usableWh,daily}:{resultRef:React.RefObject<HTMLHeadingElement|null>;days:number;capacity:number;usableWh:number;daily:number}){return <><div className={styles.mainResult}><span>{format(usableWh)} Wh utilizables estimados</span><h2 ref={resultRef} tabIndex={-1}>Autonomía estimada</h2><strong>≈ {format(days,1)} días</strong><p>Con {format(capacity)} Wh nominales y el consumo indicado, esta es una referencia antes de variaciones y pérdidas reales.</p></div><details className={styles.math}><summary>¿Cómo sale este cálculo?</summary><code>{format(capacity)} Wh × fracción utilizable<br/>= {format(usableWh)} Wh útiles<br/><br/>{format(usableWh)} ÷ {format(daily,1)} Wh/día<br/>≈ {format(days,1)} días</code></details></>}
function ProductMatches({products,minimum,target,assessment}:{products:CalculatorProduct[];minimum:number;target:number;assessment:PowerAssessment}){const powerLabel=(fit:ReturnType<typeof productFit>)=>fit.powerStatus==="unknown"?"no evaluada":fit.powerStatus==="partial"?"evaluación parcial":fit.powerPass?"cumple":"insuficiente";return <section className={styles.matches}><h3>Modelos que encajan</h3>{sortProductsByFit(products,minimum,target,assessment).map(product=>{const fit=productFit(product,minimum,target,assessment);return <article key={product.id} data-status={fit.status}>{product.image&&<Image src={product.image} alt={product.name} width={104} height={86} sizes="104px"/>}<div><span>{product.name}</span><strong>{format(product.capacityWh)} Wh · {format(product.continuousOutputWatts)} W</strong><b>{statusLabel[fit.status]}</b><p>Capacidad: {fit.capacityPass?"cumple":"insuficiente"}<br/>Potencia: {powerLabel(fit)}</p><small>{fit.explanation}</small>{product.reviewHref&&<Link href={product.reviewHref}>Ver review →</Link>}</div></article>})}</section>}
