import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { getProductById } from "@/content/products";
import styles from "../use-case.module.css";

const slug="caravana-autocaravana",publishedAt="2026-08-22",siteUrl=process.env.NEXT_PUBLIC_SITE_URL??"http://localhost:3000";
const title="Qué power station necesitas para una caravana o autocaravana";
const description="Calcula qué power station necesitas para caravana o autocaravana según aparatos, potencia simultánea, días, solar y recarga.";
export const metadata:Metadata={title:{absolute:"Power station para caravana y autocaravana | Carga Nómada"},description,alternates:{canonical:`/usos/${slug}`},openGraph:{type:"article",url:`/usos/${slug}`,title,description,siteName:"Carga Nómada",locale:"es_ES",publishedTime:publishedAt,modifiedTime:publishedAt},twitter:{card:"summary",title,description}};
const f1800=getProductById("fossibot-f1800")!,f2400=getProductById("fossibot-f2400")!,f3600=getProductById("fossibot-f3600-pro")!;const n=(v:number|undefined)=>v?.toLocaleString("es-ES")??"no declarado";

export default function CaravanPage(){const canonical=`${siteUrl}/usos/${slug}`;const schema={"@context":"https://schema.org","@graph":[{"@type":"BreadcrumbList","@id":`${canonical}#breadcrumb`,itemListElement:[{"@type":"ListItem",position:1,name:"Inicio",item:siteUrl},{"@type":"ListItem",position:2,name:"Usos",item:`${siteUrl}/usos`},{"@type":"ListItem",position:3,name:"Caravana y autocaravana",item:canonical}]},{"@type":"Article","@id":`${canonical}#article`,mainEntityOfPage:canonical,headline:title,description,datePublished:publishedAt,dateModified:publishedAt,inLanguage:"es",isAccessibleForFree:true,author:{"@id":`${siteUrl}#organization`},publisher:{"@id":`${siteUrl}#organization`},breadcrumb:{"@id":`${canonical}#breadcrumb`}}]};return <><main className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/>
<header className={styles.hero}><div className="container"><nav className={styles.breadcrumb} aria-label="Migas de pan"><Link href="/">Inicio</Link><span>/</span><Link href="/usos">Usos</Link><span>/</span><span>Caravana y autocaravana</span></nav><p className={styles.kicker}>Caso de uso 03 · Caravaning</p><h1>{title}</h1><p className={styles.lead}>Aquí suele importar más la energía diaria y la potencia que coincide que el peso para caminar. Nevera, luces, TV y móviles son manejables; cafetera, microondas, secador o calefacción eléctrica pueden cambiar por completo el dimensionado.</p><div className={styles.heroFacts}><span>AC + DC</span><span>Varios usuarios</span><span>Potencia simultánea</span></div><div className={styles.byline}><span>Equipo editorial de Carga Nómada</span><span>Publicado y revisado el 22 de agosto de 2026</span></div></div></header>
<div className="container"><section className={styles.quick}><div><p className={styles.kicker}>Respuesta rápida</p><h2>Dimensiona la convivencia, no un aparato aislado</h2></div><ol><li><span>01</span>Suma los Wh de un día</li><li><span>02</span>Cuenta días entre recargas</li><li><span>03</span>Simula qué aparatos coinciden</li><li><span>04</span>Separa salidas AC y DC</li><li><span>05</span>Define red, vehículo y solar</li></ol><p>Una estación de 2 kWh puede ser un apoyo razonable, pero no cubre por definición todos los servicios del vehículo. Depende de qué conectes directamente y de cuándo puedas recargar.</p></section></div>
<article>
<section className={styles.section}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>01 · Dos límites</p><h2>Primero Wh; después, los W que coinciden</h2><p>La capacidad determina cuánto dura la energía. La potencia continua determina si puedes encender una combinación concreta.</p></div><div className={styles.priorityGrid}><article><span>ENERGÍA</span><strong>Wh/día</strong><p>Nevera, luces, pantallas y cargas por días.</p></article><article><span>COINCIDENCIA</span><strong>W juntos</strong><p>Cafetera, TV, cargadores y compresores pueden solaparse.</p></article><article><span>SALIDAS</span><strong>AC + DC</strong><p>Cada conexión tiene tensión, corriente y límite propios.</p></article><article><span>RECARGA</span><strong>balance</strong><p>Red, solar y conducción deben reponer parte del gasto.</p></article></div><p className={styles.text}>No confundas una salida de 3.000 W con mucha autonomía. Revisa picos y suma de cargas en <Link href="/guias/que-puedo-conectar-power-station">qué puedes conectar a una power station</Link>.</p></div></section>
<section className={`${styles.section} ${styles.scenarios}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>02 · Tres niveles de convivencia</p><h2>Escenarios trazables para comparar</h2><p>Son hipótesis editoriales. El margen del 20 % ayuda a planificar variaciones; no es una pérdida fija del sistema.</p></div><div className={styles.scenarioGrid}>
<Scenario no="01" label="Escapada básica · 3 días" name="Frío, luz, TV y móviles" energy="2.115" margin="2.538" power="≈250 W + arranques" lines={["Nevera: 450 Wh/día × 3 = 1.350 Wh","Luces: 3 × 6 W × 5 h × 3 = 270 Wh","Móviles: 4 × 15 Wh × 3 = 180 Wh","TV: 45 W × 2 h × 3 = 270 Wh","Bomba: 60 W × 0,25 h × 3 = 45 Wh"]} total="Total 2.115 Wh; con 20 % = 2.538 Wh." note="Autonomía, 12 V compatible y recarga durante la estancia. 2.048 Wh nominales no cubren este ejemplo completo sin reposición."/>
<Scenario no="02" label="Viaje familiar · 2 días" name="Más pantallas y café" energy="2.276" margin="2.731" power="≈1.500 W + arranques" lines={["Nevera: 450 Wh/día × 2 = 900 Wh","TV: 60 W × 3 h × 2 = 360 Wh","Móviles: 4 × 15 Wh × 2 = 120 Wh","Tablet: 25 Wh × 2 cargas = 50 Wh","Portátil: 65 W × 3 h × 2 = 390 Wh","Luces: 3 × 6 W × 5 h × 2 = 180 Wh","Cafetera: 1.200 W × 6/60 h × 2 = 240 Wh","Bomba: 60 W × 0,3 h × 2 = 36 Wh"]} total="Total 2.276 Wh; con 20 % = 2.731,2 Wh." note="Más Wh, puertos y control de simultaneidad. La cafetera añade muchos W durante pocos minutos."/>
<Scenario wide no="03" label="Autocaravana de consumo alto · 2 días" name="Conectividad, microondas y café" energy="3.393" margin="4.071" power="≈1.600 W; ≈3.000 W si coinciden microondas y cafetera" lines={["Nevera: 500 Wh/día × 2 = 1.000 Wh","Router: 15 W × 12 h × 2 = 360 Wh","Portátil: 65 W × 5 h × 2 = 650 Wh","Cafetera: 1.400 W × 8/60 h × 2 ≈ 373,3 Wh","Microondas (entrada): 1.300 W × 10/60 h × 2 ≈ 433,3 Wh","TV: 70 W × 3 h × 2 = 420 Wh","Móviles: 4 × 15 Wh × 2 = 120 Wh","Bomba: 60 W × 0,3 h × 2 = 36 Wh"]} total="Total ≈3.392,6 Wh; con 20 % ≈4.071,1 Wh." note="Capacidad alta, recarga frecuente y gestión de cargas. Evitar que microondas y cafetera coincidan reduce los W necesarios."/>
</div><aside className={styles.notice}><strong>Haz tu propia cuenta</strong><p>Sustituye cada supuesto por etiquetas o mediciones. La <Link href="/guias/calcular-autonomia-power-station">guía de autonomía</Link> explica capacidad nominal y tiempo estimado.</p></aside></div></section>
<section className={`${styles.section} ${styles.models}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>03 · Cuadro de simultaneidad</p><h2>Un uso breve puede marcar la potencia</h2><p>TV, portátil, nevera y cargadores pueden estar activos cuando alguien enciende un aparato exigente.</p></div><div className={styles.modelGrid}><article><span>CAFETERA</span><h3>W altos, pocos minutos</h3><p>Consulta su entrada. En el escenario familiar, 1.200 W durante seis minutos diarios aportan 120 Wh/día: potencia alta y energía contenida.</p></article><article><span>MICROONDAS</span><h3>Mira la entrada eléctrica</h3><p>“700 W” u “800 W” pueden describir potencia de cocción. Para la estación importa la entrada eléctrica de etiqueta o manual.</p></article><article><span>CALEFACCIÓN</span><h3>Las horas dominan</h3><p>Un calefactor compatible en W puede agotar mucha capacidad durante horas. Calcula <Link href="/guias/calcular-autonomia-power-station">su coste energético</Link> antes de dimensionar.</p></article></div></div></section>
<section className={styles.section}><div className="container"><div className={styles.split}><div><p className={styles.index}>04 · Una URL, dos contextos</p><h2>Caravana frente a autocaravana</h2></div><div><p><strong>Una caravana</strong> puede permanecer más tiempo fija, con conexión de camping y solar trabajando durante la estancia. La estación puede moverse entre coche y habitáculo si procede.</p><p><strong>Una autocaravana</strong> suele hacer más relevante la recarga en ruta y puede tener mayor integración eléctrica. Espacio y fijación siguen importando.</p><p>No todos los vehículos funcionan igual: mandan tu patrón de paradas, los sistemas instalados y qué cargas dependerán de la estación.</p></div></div></div></section>
<section className={styles.section}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>05 · Recuperar energía</p><h2>Solar ayuda; no borra el consumo</h2><p>En estancias largas, compara gasto diario y recuperación posible sin suponer sol perfecto.</p></div><div className={styles.priorityGrid}><article><span>SOLAR</span><strong>entrada</strong><p>F1800/F2400: hasta 500 W; F3600 Pro: hasta 2.000 W.</p></article><article><span>VEHÍCULO</span><strong>parcial</strong><p>Depende de horas conduciendo, tensión y sistema del vehículo.</p></article><article><span>RED</span><strong>parada</strong><p>Recuperación previsible cuando existe toma compatible.</p></article><article><span>PLAN</span><strong>Wh</strong><p>La batería almacena; las entradas compensan el gasto.</p></article></div><p className={styles.text}>F1800 declara 12 V hasta 120 W; F2400, 100 W a 12 V o 200 W a 24 V. F3600 Pro declara 1.920 minutos a 12 V o 960 a 24 V para una carga completa: no implica completarla en un trayecto habitual. Consulta la <Link href="/guias/placas-solares-power-station">guía solar</Link>.</p></div></section>
<section className={`${styles.section} ${styles.models}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>06 · Modelos</p><h2>Tres escalones, tres compromisos</h2><p>Cada salto aporta capacidad o potencia, y exige más espacio, peso y presupuesto.</p></div><div className={styles.modelGrid}><Model p={f1800} tag="REFERENCIA INFERIOR" body="1.024 Wh, 1.800 W y 11,25 kg: apoyo con recarga frecuente, no batería suficiente para los tres ejemplos completos." limit="Más W que F1200 no añaden autonomía; conserva 1.024 Wh."/><Model p={f2400} tag="BASE DE 2 KWH" body="2.048 Wh, 2.400 W y salida RV regulada de 12 V/25 A, previa comprobación de compatibilidad." limit="22 kg y 2.048 Wh exigen ubicación y recarga; no cubre toda la instalación."/><Model p={f3600} tag="CAPACIDAD AMPLIABLE" body="3.840 Wh, 3.600 W, hasta 2.000 W solares y batería expandible: encaja con consumo alto y paradas largas." limit="42 kg reducen portabilidad. La expansión requiere baterías compatibles del fabricante."/></div></div></section>
<section className={styles.section}><div className="container"><div className={styles.split}><div><p className={styles.index}>07 · Apoyo portátil</p><h2>No sustituye automáticamente la instalación</h2></div><div><p>Puede ampliar capacidad, dar respaldo o alimentar aparatos concretos sin modificar demasiado el vehículo.</p><p>No conectes su salida AC a toda la instalación salvo un sistema diseñado para ello y conforme con fabricante y normativa. Valida tensión, corriente, regulación y conectores de 12 V carga por carga.</p><p>Para menos aparatos compara el uso en <Link href="/usos/camper">camper</Link>; para una escapada transportable, revisa <Link href="/usos/camping">camping</Link>.</p></div></div></div></section>
<section className={styles.section}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>08 · Peso y espacio</p><h2>Importan menos que caminando, pero no desaparecen</h2></div><div className={styles.weightBoard}><div><span>Modelo</span><span>Capacidad</span><span>Potencia</span><span>Peso</span></div>{[f1800,f2400,f3600].map(p=><div key={p.id}><strong>{p.model}</strong><span>{n(p.capacityWh)} Wh</span><span>{n(p.continuousOutputWatts)} W</span><span>{n(p.weightKg)} kg</span></div>)}</div><p className={styles.text}>Pasar de 11,25 a 42 kg cambia carga, fijación y ventilación. Mide el hueco con cables. F7200 queda fuera: su escala corresponde a otra decisión energética, no a una recomendación obligatoria aquí.</p></div></section>
<section className={`${styles.section} ${styles.dark}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>09 · Errores</p><h2>Lo que desajusta la elección</h2></div><div className={styles.checkGrid}>{[["Mirar solo Wh","La capacidad no garantiza la simultaneidad."],["Confundir W con autonomía","Una salida potente no añade horas."],["Calentar durante horas","El calor resistivo exige mucha energía."],["Leer solo la cocción","En microondas importa la entrada eléctrica."],["Confiar en sol perfecto","Sombra y límites reducen la recuperación."],["Sustituir la instalación","Una estación no reemplaza automáticamente sistemas auxiliares."],["Olvidar la noche","Nevera y router pueden seguir consumiendo."],["Comprar demasiado peso","Más capacidad exige hueco y manejo."]].map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,"0")}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
<section className={`${styles.section} ${styles.faq}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>10 · FAQ</p><h2>Dudas sobre energía en caravaning</h2></div><Faq q="¿Cuántos Wh necesito para una autocaravana?" a="Suma los Wh diarios y multiplícalos por días entre recargas. Estos ejemplos van de 2.115 a 3.393 Wh antes del margen."/><Faq q="¿Qué power station necesito para una caravana?" a="Depende de capacidad, simultaneidad y recarga. Una base de 2 kWh puede ayudar, pero varios días pueden exigir reposición."/><Faq q="¿Puedo usar microondas?" a="Solo si la salida soporta su entrada eléctrica y las demás cargas simultáneas. No uses solo la potencia de cocción."/><Faq q="¿Puedo usar cafetera?" a="Sí si potencia y salida son compatibles. Calcula minutos de uso para conocer sus Wh."/><Faq q="¿Necesito placas solares?" a="Son útiles en estancias largas, pero no eliminan consumo. Compara gasto y recuperación posible."/><Faq q="¿Power station o batería auxiliar?" a="La estación favorece portabilidad; una instalación auxiliar integra mejor cargas permanentes. Depende del sistema completo."/></div></section>
<section className={`${styles.section} ${styles.cta}`}><div className="container"><p className={styles.kicker}>Tu vehículo, tus aparatos</p><h2>¿Tu caravana consume distinto?</h2><p>Añade aparatos, horas y días. Después revisa qué cargas coinciden y cómo recuperarás energía.</p><Link href="/encontrar-power-station">Calcular mi power station →</Link></div></section>
<section className={styles.sources}><div className="container"><p className={styles.index}>11 · Metodología</p><h2>Datos frente a hipótesis</h2><p>Capacidad, potencia, peso, entradas, expansión y puertos proceden de <code>src/content/products.ts</code>, con fuentes de fabricante verificadas el 20 de agosto de 2026. Consumos, horas, días, simultaneidad y margen del 20 % son supuestos editoriales, no pruebas físicas.</p></div></section>
</article></main><SiteFooter/></>}
function Scenario({no,label,name,energy,margin,power,lines,total,note,wide=false}:{no:string;label:string;name:string;energy:string;margin:string;power:string;lines:string[];total:string;note:string;wide?:boolean}){return <article className={`${styles.scenarioCard} ${wide?styles.scenarioWide:""}`}><header><span>{no}</span><div><p>{label}</p><h3>{name}</h3></div></header><div className={styles.scenarioBody}><dl><div><dt>Energía calculada</dt><dd>≈{energy} Wh</dd></div><div><dt>Plan con margen</dt><dd>≈{margin} Wh</dd></div><div><dt>Potencia simultánea</dt><dd>{power}</dd></div></dl><div className={styles.math}>{lines.map(x=><code key={x}>{x}</code>)}<span>{total}</span></div><p><strong>Prioriza:</strong> {note}</p></div></article>}
function Model({p,tag,body,limit}:{p:typeof f1800;tag:string;body:string;limit:string}){return <article><span>{tag}</span><h3>{p.name}</h3><div className={styles.modelSpecs}><strong>{n(p.capacityWh)} Wh</strong><strong>{n(p.continuousOutputWatts)} W</strong><strong>{n(p.weightKg)} kg</strong></div><p>{body}</p><p className={styles.limit}><b>Límite:</b> {limit}</p><Link href={`/reviews/${p.slug}-review`}>Ver análisis de la {p.model} →</Link></article>}
function Faq({q,a}:{q:string;a:string}){return <details><summary>{q}</summary><p>{a}</p></details>}
