import { defineReview, type Review } from "@/domain/review";

export const reviews = [
  defineReview({
    id: "review-f1200-juan", slug: "fossibot-f1200-review", productId: "fossibot-f1200", personaId: "juan", status: "published", publishedAt: "2026-08-20", updatedAt: "2026-08-21",
    h1: "FOSSiBOT F1200 review: ¿encaja en un fin de semana de camping?", eyebrow: "Camping ligero · Análisis por especificaciones",
    excerpt: "Una lectura práctica de sus 1.024 Wh, 1.200 W y 11,5 kg para escapadas cortas con nevera, luces y electrónica.",
    seo: { title: "FOSSiBOT F1200 review para camping", description: "Analizamos capacidad, potencia, puertos, carga y peso de la FOSSiBOT F1200 para saber si encaja en un fin de semana de camping.", primaryKeyword: "FOSSiBOT F1200 review", semanticVariants: ["FOSSiBOT F1200 análisis", "power station para camping", "F1200 autonomía"], searchIntent: "informational-commercial" },
    quickAnswer: { summary: "Para un fin de semana de camping, yo empezaría mirando esta antes que una batería mucho más grande. Me da para lo que suelo llevar y sus 11,5 kg todavía son razonables para pasarla del coche a la parcela.", advantage: "No se dispara de tamaño ni de peso para ofrecer 1.024 Wh.", limitation: "Si quisiera cocinar con electricidad o pasar muchos días sin recargar, se me quedaría corta." },
    intro: ["Yo no necesito llevar media casa detrás. Para dos o tres noches quiero mantener fría la nevera, encender unas luces, cargar el móvil y, como mucho, abrir el portátil un rato.", "Por eso la F1200 me llama más la atención que los modelos grandes. Prefiero ahorrar peso y dinero antes que volver a casa con media batería sin usar."],
    focus: [{ title: "Prefiero acertar con el tamaño antes que comprar de más", body: "Para dos o tres noches, 1.024 Wh me parecen un punto razonable. Tengo energía para la nevera, las luces y la electrónica, pero sigo pudiendo mover 11,5 kg del coche a la parcela sin convertirlo en una faena.", evidence: "editorial-analysis" }, { title: "Un cargador menos también cuenta", body: "El USB-C de 100 W me permite conectar un portátil compatible directamente. En una mesa pequeña agradezco quitar un transformador, perder menos energía y dejar los dos enchufes libres para otra cosa.", evidence: "verified-fact" }],
    autonomy: ["Con mis consumos, la pregunta es muy sencilla: ¿puedo llegar al domingo sin buscar un enchufe? La estimación de unas 14,5 horas a 60 W no significa que todo funcione exactamente ese tiempo, pero sí me ayuda a ver que móvil, luces y nevera eficiente encajan en una escapada normal.", "Yo reservaría los consumos fuertes para momentos concretos. La nevera va entrando y saliendo; un hornillo, en cambio, puede comerse una parte grande de la batería en muy poco tiempo."],
    power: ["Para lo que llevo un fin de semana, 1.200 W me parecen suficientes. Móvil, luces, nevera y portátil no me preocupan. Donde tendría cuidado es con un hervidor o una placa, porque ahí empiezas a gastar potencia y batería muy rápido.", "Los 2.400 W de pico me sirven como margen de arranque, no como permiso para conectar cualquier cosa durante horas."],
    transport: ["Si tuviera que cargarla todos los días, 11,5 kg todavía me parecen razonables. La F2400 pesa 22 kg: para dos noches yo me quedo con la F1200 y me ahorro más de diez kilos que no necesito."],
    pros: ["Me da autonomía de fin de semana sin llenar el maletero", "Puedo cargar el portátil por USB-C y dejar libres los enchufes", "La movería sin pedir ayuda", "La carga AC encaja con una parada corta en casa"], cons: ["No crecerá si más adelante quiero otra batería", "Los 200 W solares piden paciencia", "No la compraría pensando en cocinar con electricidad", "Dos tomas AC pueden quedarse justas si llevo muchos cargadores"],
    forWhom: ["Escapadas de dos o tres días con consumos moderados", "Quien prioriza peso y sencillez", "Usuarios que cargan portátil por USB-C"], notForWhom: ["Quien quiere cocinar habitualmente con resistencias eléctricas", "Estancias largas sin recarga", "Sistemas que deban crecer con baterías adicionales"],
    conclusion: ["Para mis escapadas, yo me quedaría con la F1200 antes que con la F2400. Prefiero ahorrar peso y aceptar que tengo menos margen; para dos noches no necesito cargar con el doble de capacidad.", "Si empezara a cocinar con electricidad, llevar una nevera grande o salir una semana, entonces sí subiría a la F2400. Para móvil, luces, nevera portátil y un rato de portátil, esta es la que más sentido me hace."],
    faqs: [{ question: "¿La FOSSiBOT F1200 sirve para una nevera portátil?", answer: "Por potencia, muchas neveras portátiles encajan; la autonomía depende de su consumo real, ciclos del compresor y temperatura." }, { question: "¿Puede cargar un portátil por USB-C?", answer: "Sí, incluye un USB-C de hasta 100 W; el portátil debe aceptar esa potencia y protocolo." }, { question: "¿Se puede ampliar con otra batería?", answer: "No consta compatibilidad con una batería de expansión en la ficha oficial revisada." }, { question: "¿Puedo usar un hervidor o una placa eléctrica?", answer: "Solo si su potencia queda por debajo del límite y no coincide con otras cargas. Son consumos intensos que reducen mucho la autonomía." }],
    relatedReviewSlugs: ["fossibot-f1800-review", "fossibot-f2400-review"], estimateLoadWatts: 60, imagePaths: ["/images/products/fossibot-f1200/hero.webp", "/images/products/fossibot-f1200/ports.webp", "/images/products/fossibot-f1200/camping.jpg"]
  }),
  defineReview({
    id: "review-f1800-alex", slug: "fossibot-f1800-review", productId: "fossibot-f1800", personaId: "alex", status: "published", publishedAt: "2026-08-20", updatedAt: "2026-08-21",
    h1: "FOSSiBOT F1800 review: potencia y USB-C para trabajar en camper", eyebrow: "Trabajo remoto · Análisis por especificaciones",
    excerpt: "La misma capacidad base que la F1200, pero más potencia, entrada solar y dos USB-C de hasta 140 W para un puesto móvil.",
    seo: { title: "FOSSiBOT F1800 review para camper", description: "FOSSiBOT F1800 review para trabajar en camper: analizamos sus 1.024 Wh, 1.800 W, dos USB-C de 140 W, entrada solar y autonomía.", primaryKeyword: "FOSSiBOT F1800 review", semanticVariants: ["FOSSiBOT F1800 análisis", "power station para camper", "F1800 USB-C 140 W"], searchIntent: "commercial-investigation" },
    quickAnswer: { summary: "Para trabajar desde la camper, yo elegiría la F1800 antes que la F1200. No gana capacidad, pero sus dos USB-C de 140 W y los 500 W solares encajan mucho mejor con un escritorio móvil.", advantage: "Puedo alimentar dos equipos USB-C exigentes sin ocupar las tomas AC.", limitation: "Sigo teniendo 1.024 Wh: más potencia no me compra una segunda jornada." },
    intro: ["Lo primero que miraría aquí son los USB-C. Mi portátil, el monitor, el router y los discos tienen que convivir en una mesa pequeña, y no quiero llenar la camper de transformadores.", "Para mí, tener dos USB-C de 140 W vale más que una toma AC extra. Si conecto el portátil directamente, dejo los enchufes libres y simplifico el puesto de trabajo."],
    focus: [{ title: "Los USB-C deciden más que una toma extra", body: "Yo empezaría por los dos USB-C PD de 140 W. Puedo alimentar portátil y otro equipo exigente sin conversiones AC, dejo libres los enchufes y reduzco el lío de cargadores dentro de la camper.", evidence: "verified-fact" }, { title: "1.800 W no me dan una segunda jornada", body: "La potencia me permite asumir cargas puntuales más altas, pero sigo almacenando 1.024 Wh. Para mí la diferencia frente a la F1200 está en cómo entrega y recupera energía, no en esperar el doble de autonomía.", evidence: "editorial-analysis" }],
    autonomy: ["Mi problema no es llegar al final de una película: es terminar una jornada y poder empezar la siguiente. La estimación de unas 7,9 horas a 110 W representa un puesto bastante activo, pero mi consumo puede bajar mucho si apago el monitor o sube si entra Starlink.", "Por eso los 500 W solares me interesan más que el pico de potencia. Con buen sol tengo una vía de recuperación seria durante el día; con nubes, necesito bajar consumo o buscar otra fuente."],
    power: ["Los 1.800 W me dejan trabajar mientras preparo un café o conecto una herramienta puntual. Aun así, miro el total: no quiero que una cafetera coincida con una carga pesada y tire todo el puesto.", "El UPS me interesa para router y almacenamiento, pero no lo trataría como un SAI profesional sin conocer su tiempo de transferencia con el equipo concreto."],
    transport: ["Con 11,25 kg puedo sacarla para cargar con paneles y guardarla después sin convertirlo en una maniobra. Eso pesa en mi decisión: la F2400 me da el doble de capacidad, pero también casi duplica el peso."],
    pros: ["Los dos USB-C de 140 W encajan con mi portátil y periféricos", "Los 500 W solares ayudan a recuperar una jornada", "Tengo 1.800 W sin cargar con más de 20 kg", "La conectividad me permite vigilar el sistema desde la camper"], cons: ["La batería no dura más que la F1200 por tener más potencia", "No puedo añadir capacidad después", "Dos tomas AC obligan a organizar equipos antiguos", "El UPS necesita una comprobación específica antes de confiarle trabajo crítico"],
    forWhom: ["Profesionales con portátiles USB-C exigentes", "Camper con buena oportunidad de recarga solar", "Quien necesita más potencia sin saltar a 20 kg"], notForWhom: ["Puestos que deben aguantar varios días sin sol ni conducción", "Quien quiere ampliar capacidad después", "Instalaciones fijas de alta demanda"],
    conclusion: ["Entre la F1200 y la F1800, para trabajar me quedo con la F1800. Los USB-C de 140 W y la entrada solar de 500 W influyen todos los días; los 600 W extra de salida son un margen útil, pero no el motivo principal.", "Si necesitara dos jornadas completas sin sol, saltaría a la F2400 por sus 2.048 Wh. Si puedo recargar durante el día y quiero mantener el equipo manejable, elegiría la F1800."],
    faqs: [{ question: "¿La F1800 puede alimentar Starlink?", answer: "La potencia es suficiente para equipos Starlink habituales, pero la autonomía depende del modelo, consumo, clima y conversiones." }, { question: "¿Tiene dos USB-C de 140 W?", answer: "Sí, la información oficial indica dos puertos USB-C PD 3.0 de hasta 140 W." }, { question: "¿Admite paneles solares de 500 W?", answer: "Admite hasta 500 W de entrada solar; hay que comprobar tensión, corriente y conectores del conjunto de paneles." }, { question: "¿Puede funcionar como UPS para el router?", answer: "La función UPS figura entre sus características, pero conviene comprobar compatibilidad y tiempo de transferencia con el router o equipo concreto." }],
    relatedReviewSlugs: ["fossibot-f1200-review", "fossibot-f2400-review"], estimateLoadWatts: 110, imagePaths: ["/images/products/fossibot-f1800/hero.webp", "/images/products/fossibot-f1800/ports.webp", "/images/products/fossibot-f1800/solar-kit.webp"]
  }),
  defineReview({
    id: "review-f2400-laura", slug: "fossibot-f2400-review", productId: "fossibot-f2400", personaId: "laura", status: "published", publishedAt: "2026-08-20", updatedAt: "2026-08-21",
    h1: "FOSSiBOT F2400 review: capacidad para una caravana familiar", eyebrow: "Caravana familiar · Análisis por especificaciones",
    excerpt: "2.048 Wh, 2.400 W y un reparto amplio de conexiones para varios dispositivos, con 22 kg que exigen un lugar estable.",
    seo: { title: "FOSSiBOT F2400 review para caravana", description: "FOSSiBOT F2400 review para caravana familiar: analizamos 2.048 Wh, 2.400 W, puertos, autonomía estimada, recarga y sus 22 kg.", primaryKeyword: "FOSSiBOT F2400 review", semanticVariants: ["FOSSiBOT F2400 análisis", "power station para caravana", "F2400 autonomía"], searchIntent: "commercial-investigation" },
    quickAnswer: { summary: "Para una familia, la F2400 es la que más sentido me hace de esta gama. Sus 2.048 Wh me dan margen para nevera, luces, móviles y pantallas sin estar organizando turnos.", advantage: "Puedo repartir varios consumos y seguir teniendo reserva para el final del día.", limitation: "Con 22 kg tengo que buscarle un sitio fijo en la caravana." },
    intro: ["Viajar cuatro personas cambia bastante lo que le pido a una batería. Siempre hay dos móviles, una tablet o una cámara pidiendo carga, mientras la nevera y las luces siguen funcionando.", "Yo no quiero pasar las vacaciones diciendo quién puede enchufar qué. Busco margen, conexiones suficientes y una rutina sencilla para cargarla durante el viaje."],
    focus: [{ title: "Quiero margen para los despistes normales", body: "Con 2.048 Wh no tengo que llevar una contabilidad perfecta de cada móvil, cada luz y cada rato de televisión. Ese colchón familiar me importa más que presumir de una potencia que casi nunca voy a usar completa.", evidence: "editorial-analysis" }, { title: "La salida RV me ayuda a ordenar la caravana", body: "La salida regulada de 12 V y 25 A me interesa porque puedo concentrar consumos de corriente continua, siempre que compruebe conectores y compatibilidad. Menos adaptadores sueltos significa una rutina más sencilla para todos.", evidence: "verified-fact" }],
    autonomy: ["Lo que quiero saber es si al acostarnos seguirá quedando batería después de todo un día de nevera, luces y dispositivos. La estimación de unas 12,4 horas a 140 W me orienta, aunque en una familia el consumo sube y baja constantemente.", "La cafetera gasta mucho durante unos minutos; la nevera, menos pero durante todo el día. Los 2.048 Wh me gustan porque absorben mejor esos pequeños descuidos que una F1200 de 1.024 Wh."],
    power: ["Con 2.400 W no tendría que apagar la nevera para preparar un café. Sí evitaría juntar cafetera, secador y cualquier otro aparato de calor: tener margen no significa que todo pueda funcionar a la vez.", "Las tres tomas AC, los USB y las salidas de 12 V me permiten repartir mejor los equipos. Para mí eso vale más que una cifra enorme de pico."],
    transport: ["Con 22 kg, yo la trataría como equipo semi fijo dentro de la caravana. Antes de salir decidiría su ubicación, anclaje y acceso a ventilación, en lugar de moverla cada noche."],
    pros: ["Me da margen para varios consumos sin vigilar continuamente", "Puedo preparar café sin desmontar el resto de la rutina", "Hay conexiones suficientes para una familia", "La salida RV de 12 V encaja bien con la caravana"], cons: ["No quiero mover 22 kg cada día", "No podré añadir una batería si cambian mis viajes", "Recargar desde el vehículo exige planificación", "Para una pareja con pocos consumos puede ser más de lo necesario"],
    forWhom: ["Familias con nevera y varios dispositivos", "Caravanas con consumos DC", "Quien quiere margen sin entrar en sistemas expandibles"], notForWhom: ["Camping a pie o con cambios constantes de parcela", "Necesidades futuras por encima de 2 kWh sin recarga", "Quien solo carga electrónica ligera"],
    conclusion: ["Para una familia, la F2400 es la que más sentido me hace de esta gama. La F1200 se me queda justa cuando sumo cuatro personas; la F3600 Pro ya exige más espacio, peso y presupuesto de lo que quiero asumir.", "Yo la elegiría si puedo dejarla bien colocada dentro de la caravana. Si tuviera que sacarla y guardarla a diario, bajaría de tamaño y aceptaría organizar mejor los consumos."],
    faqs: [{ question: "¿Cuánto dura la FOSSiBOT F2400 con una nevera?", answer: "Depende del consumo real y del ciclo del compresor. Conviene sumar la nevera al resto de consumos diarios, no calcularla de forma aislada." }, { question: "¿Puede con una cafetera?", answer: "Muchas cafeteras quedan por debajo de 2.400 W, pero hay que comprobar su potencia y otros consumos simultáneos." }, { question: "¿Tiene salida para RV?", answer: "Sí, incluye una salida RV regulada de 12 V y hasta 25 A según la ficha oficial." }, { question: "¿Cómo se recarga durante un viaje?", answer: "Admite red AC, solar y vehículo. La carga de vehículo es la más lenta; solar y red ofrecen tiempos oficiales más cortos bajo condiciones adecuadas." }],
    relatedReviewSlugs: ["fossibot-f1800-review", "fossibot-f3600-pro-review"], estimateLoadWatts: 140, imagePaths: ["/images/products/fossibot-f2400/hero.webp", "/images/products/fossibot-f2400/ports.webp", "/images/products/fossibot-f2400/caravan.webp"]
  }),
  defineReview({
    id: "review-f3600-carmen", slug: "fossibot-f3600-pro-review", productId: "fossibot-f3600-pro", personaId: "carmen", expansionBatteryIds: ["fossibot-fb3840"], status: "published", publishedAt: "2026-08-20", updatedAt: "2026-08-21",
    h1: "FOSSiBOT F3600 Pro review: autonomía ampliable para autocaravana", eyebrow: "Viajes largos · Sistema ampliable",
    excerpt: "Una base de 3.840 Wh que puede crecer con la FB3840, pensada para estancias largas más que para moverla continuamente.",
    seo: { title: "FOSSiBOT F3600 Pro review + FB3840", description: "FOSSiBOT F3600 Pro review con batería FB3840: analizamos capacidad ampliable, 3.600 W, recarga, autonomía y peso para autocaravana.", primaryKeyword: "FOSSiBOT F3600 Pro review", semanticVariants: ["F3600 Pro análisis", "F3600 Pro FB3840", "power station ampliable autocaravana"], searchIntent: "commercial-investigation" },
    quickAnswer: { summary: "Si voy a viajar varias semanas, prefiero cargar menos veces aunque el equipo sea más pesado. La F3600 Pro me da ese margen y permite añadir una FB3840 si de verdad la necesito.", advantage: "Puedo dejar de mirar el porcentaje cada vez que enciendo la cafetera o la televisión.", limitation: "Con 42 kg no la compraría para moverla: necesita un sitio fijo." },
    intro: ["Yo quiero olvidarme de la batería durante el viaje. No busco hacer cálculos cada mañana, sino usar la nevera, preparar café, ver la televisión y cargar los móviles con normalidad.", "Para una salida corta elegiría algo más pequeño. La F3600 Pro empieza a interesarme cuando hablamos de varias semanas y de un equipo que va a quedarse colocado en la autocaravana."],
    focus: [{ title: "Ampliaría después, no por si acaso", body: "La FB3840 puede llevar el conjunto a 7.680 Wh nominales, pero yo no empezaría comprándola. Primero viajaría con la unidad base y solo añadiría capacidad si veo que sigo buscando un enchufe antes de lo que me resulta cómodo.", evidence: "estimate" }, { title: "Quiero colocarla una vez y olvidarme", body: "Con 42 kg para la estación, tengo claro que no va a entrar y salir de la autocaravana. Le reservaría un lugar ventilado y accesible; si añado un módulo de 37,8 kg, revisaría también la carga útil del vehículo.", evidence: "editorial-analysis" }],
    autonomy: ["Mi referencia es pasar el día sin decidir entre la nevera, la cafetera y la televisión. La estimación de unas 14,8 horas a 220 W me da una base cómoda, pero en la práctica unos aparatos funcionan minutos y otros permanecen conectados muchas horas.", "La batería extra me interesa si realmente necesito más autonomía, no por comprar capacidad porque sí. Primero viajaría con la unidad base y ampliaría solo si mi rutina demuestra que recargo demasiado a menudo."],
    power: ["No necesito hablar de 3.600 W todo el día. Lo que me importa es poder usar los aparatos habituales sin ir apagando unos para encender otros. Esta potencia me da tranquilidad para hacerlo con sentido común.", "También valoro que pueda cargar rápido cuando encuentro red o buenas condiciones solares. En un viaje largo, recuperar la batería sin perder un día cambia más mi experiencia que el pico de potencia."],
    transport: ["Con 42 kg no la compraría para moverla. Le buscaría un sitio fijo, ventilado y fácil de alcanzar. Si añado una FB3840 de 37,8 kg, revisaría también el espacio y el peso total antes de salir."],
    expansion: ["La FB3840 añade 3.840 Wh y pesa 37,8 kg. El fabricante declara hasta dos unidades compatibles con la F3600 Pro.", "El módulo dispone de BMS y algunas salidas/entrada solar propias según ficha, pero no sustituye por sí solo las salidas AC de la estación principal."],
    pros: ["Me permite viajar sin vigilar la batería constantemente", "Puedo ampliar solo si mis viajes lo terminan pidiendo", "Hay potencia para una rutina cómoda en autocaravana", "La recarga rápida reduce el tiempo pendiente de un enchufe"], cons: ["Necesito reservarle un sitio permanente", "Cada módulo ocupa espacio y añade mucho peso", "Comprar toda la expansión desde el principio puede ser innecesario", "Para escapadas cortas hay opciones mucho más cómodas"],
    forWhom: ["Autocaravanas con ubicación permanente para el equipo", "Viajes largos y consumos diarios variados", "Quien prevé ampliar capacidad"], notForWhom: ["Quien necesita cargar el equipo a mano cada día", "Escapadas con consumos ligeros", "Vehículos sin margen de carga útil o espacio"],
    conclusion: ["Para viajes largos, elegiría la F3600 Pro antes que la F2400. La F2400 es mucho más cómoda de mover, pero yo prefiero el margen de la F3600 Pro porque mi intención es dejarla instalada y olvidarme de ella.", "Empezaría sin la FB3840. Si después de varios viajes veo que sigo buscando recarga demasiado a menudo, añadiría un módulo; comprar dos desde el primer día me parece pagar y cargar peso sin saber si lo necesito."],
    faqs: [{ question: "¿Qué es la FB3840?", answer: "Es una batería de expansión compatible que añade capacidad a la F3600 Pro; no es una power station AC completa independiente." }, { question: "¿Cuánta capacidad tiene con una FB3840?", answer: "La suma nominal es 7.680 Wh. La energía realmente utilizable será menor por las pérdidas del sistema." }, { question: "¿Cuántas baterías admite?", answer: "La información oficial revisada indica hasta dos módulos FB3840." }, { question: "¿Cuánto pesa la F3600 Pro con una FB3840?", answer: "La suma de los pesos declarados es 79,8 kg: 42 kg de la estación y 37,8 kg del módulo." }],
    relatedReviewSlugs: ["fossibot-f2400-review", "fossibot-f7200-review"], estimateLoadWatts: 220, imagePaths: ["/images/products/fossibot-f3600-pro/hero.webp", "/images/products/fossibot-f3600-pro/ports.webp", "/images/products/fossibot-f3600-pro/fb3840-system.webp"]
  }),
  defineReview({
    id: "review-f7200-sergio", slug: "fossibot-f7200-review", productId: "fossibot-f7200", personaId: "sergio", expansionBatteryIds: ["fossibot-fb5222"], status: "published", publishedAt: "2026-08-20", updatedAt: "2026-08-21",
    h1: "FOSSiBOT F7200 review: potencia y expansión para uso off-grid", eyebrow: "Off-grid · Sistema de alta potencia",
    excerpt: "5.222,4 Wh, 7.200 W, carga solar de alta y baja tensión y expansión FB5222: una instalación, no una batería para pasear.",
    seo: { title: "FOSSiBOT F7200 review off-grid", description: "FOSSiBOT F7200 review con FB5222: analizamos 7.200 W, 5.222 Wh, entrada solar, expansión, peso, protecciones e instalación off-grid.", primaryKeyword: "FOSSiBOT F7200 review", semanticVariants: ["FOSSiBOT F7200 análisis", "F7200 FB5222", "power station off-grid 7200 W"], searchIntent: "commercial-investigation" },
    quickAnswer: { summary: "Yo no compraría la F7200 por ver 7.200 W en la portada. Solo la elegiría después de calcular mis Wh diarios, diseñar la parte solar y confirmar que voy a aprovechar su potencia y expansión.", advantage: "Puede ser el centro de un sistema off-grid serio y ampliable.", limitation: "Con 70 kg, terminal cableado y solar de alta tensión, exige instalación y protecciones bien resueltas." },
    intro: ["A mí 7.200 W por sí solos no me dicen demasiado. Antes quiero saber cuánto consumo al día, cuánto puedo meter por solar, qué cargas tienen picos y cómo se integra todo el sistema.", "Aquí ya estamos diseñando una instalación, no comprando una batería para un fin de semana. La F7200 juega a otra escala que la F2400 e incluso que la F3600 Pro."],
    focus: [{ title: "Primero diseño el sistema; después elijo la batería", body: "Con 70 kg, salida cableada y solar de alta tensión, yo no improvisaría. Necesito esquema, secciones, protecciones y un profesional cualificado para la parte fija antes de considerar cerrada la compra.", evidence: "editorial-analysis" }, { title: "Cada kWh adicional tiene un coste físico", body: "Una FB5222 lleva el conjunto a 10.444,8 Wh nominales y dos a 15.667,2 Wh. Yo pondría esos números junto a los 55 kg de cada módulo, el soporte, el cableado y el espacio: ampliar no es gratis aunque haya presupuesto.", evidence: "estimate" }],
    autonomy: ["Yo empezaría por mi balance energético: nevera, bombas, herramientas, electrónica y pérdidas durante 24 horas. La estimación de unas 8,9 horas a 500 W es una referencia, no el dato con el que dimensionaría una instalación completa.", "Después miraría el peor periodo solar razonable. Si gasto más Wh de los que recupero varios días seguidos, añadir una FB5222 solo retrasa el problema; no lo soluciona."],
    power: ["Los 7.200 W continuos permiten combinar cargas serias, pero también obligan a pensar en cableado, sección, protecciones y simultaneidad. No conectaría el terminal cableado sin un profesional cualificado.", "El pico de 9.000 W tampoco me basta para validar una bomba o una herramienta. Querría conocer su arranque real y dejar margen, no diseñar al límite de una cifra comercial."],
    transport: ["Con 70 kg, el término portátil es formal. Las ruedas ayudan a desplazarla sobre firme adecuado, pero no resuelven escalones, vehículo ni carga útil. Su sitio debe decidirse antes de comprar."],
    expansion: ["La FB5222 añade 5.222,4 Wh y pesa 55 kg. No debe confundirse con una estación completa: amplía el almacenamiento de la F7200.", "La ficha declara hasta dos módulos. El sistema máximo requiere revisar espacio, ventilación, soporte y presupuesto, no solo autonomía."],
    pros: ["Puedo plantear cargas que los modelos pequeños ni contemplan", "La capacidad crece si el balance energético lo justifica", "Las dos entradas solares dan opciones de integración", "El terminal cableado permite pensar en un sistema, no solo en enchufes frontales"], cons: ["Con 70 kg deja de ser portátil en la práctica", "Necesito presupuesto para cableado, protecciones e instalación", "La expansión puede ocultar un sistema solar mal dimensionado", "Sin curvas independientes no asumiría eficiencia ni potencia sostenida perfectas"],
    forWhom: ["Instalaciones off-grid con demanda calculada", "Taller o base móvil con cargas altas", "Usuarios con diseño solar y apoyo profesional"], notForWhom: ["Compra impulsiva para camping", "Quien necesita levantarla con frecuencia", "Usuarios sin experiencia eléctrica ni instalador"],
    conclusion: ["Yo instalaría la F7200 solo si mis cálculos demuestran que voy a aprovecharla. Para consumos moderados elegiría la F3600 Pro: pesa menos, sigue siendo ampliable y simplifica el proyecto.", "Si necesito cargas altas, una entrada solar potente y más de 10 kWh con expansión, entonces la F7200 sí entra en mi lista. Pero la compra vendría después del esquema eléctrico, no antes."],
    faqs: [{ question: "¿La F7200 necesita un electricista?", answer: "La conexión por terminal y una instalación fija deben realizarlas profesionales cualificados siguiendo normativa y manual del fabricante." }, { question: "¿Qué capacidad alcanza con una FB5222?", answer: "La suma nominal es 10.444,8 Wh; la energía AC utilizable será menor por las pérdidas del sistema." }, { question: "¿Qué paneles solares admite?", answer: "Dispone de entradas solares de alta y baja tensión. Hay que validar rangos eléctricos, conectores y protecciones con la documentación vigente." }, { question: "¿Cuánto pesa el sistema con una FB5222?", answer: "La suma declarada es 125 kg: 70 kg de la F7200 y 55 kg del módulo." }],
    relatedReviewSlugs: ["fossibot-f3600-pro-review", "fossibot-f2400-review"], estimateLoadWatts: 500, imagePaths: ["/images/products/fossibot-f7200/hero.webp", "/images/products/fossibot-f7200/terminals.webp", "/images/products/fossibot-f7200/fb5222-system.webp"]
  })
] as const satisfies readonly Review[];

export function getReviewBySlug(slug: string): Review | undefined { return reviews.find((review) => review.slug === slug); }
export function getReviewsForProduct(productId: string): readonly Review[] { return reviews.filter((review) => review.productId === productId); }
