import { defineReview, type Review } from "@/domain/review";

export const reviews = [
  defineReview({
    id: "review-f1200-juan", slug: "fossibot-f1200-review", productId: "fossibot-f1200", personaId: "juan", status: "published", publishedAt: "2026-08-20", updatedAt: "2026-08-20",
    h1: "FOSSiBOT F1200 review: ¿encaja en un fin de semana de camping?", eyebrow: "Camping ligero · Análisis por especificaciones",
    excerpt: "Una lectura práctica de sus 1.024 Wh, 1.200 W y 11,5 kg para escapadas cortas, sin fingir una prueba física.",
    seo: { title: "FOSSiBOT F1200 review para camping", description: "Analizamos capacidad, potencia, puertos, carga y peso de la FOSSiBOT F1200 para un fin de semana de camping, sin fingir pruebas.", primaryKeyword: "FOSSiBOT F1200 review", semanticVariants: ["FOSSiBOT F1200 análisis", "power station para camping", "F1200 autonomía"], searchIntent: "informational-commercial" },
    quickAnswer: { summary: "Por ficha técnica, la F1200 tiene una combinación sensata para un fin de semana: capacidad suficiente para electrónica, iluminación y una nevera eficiente, con un peso que todavía permite moverla sin convertir el equipaje en una mudanza.", advantage: "Su equilibrio entre 1.024 Wh, 1.200 W y 11,5 kg.", limitation: "No admite batería de expansión y los 1.200 W obligan a revisar aparatos de calor." },
    intro: ["Yo busco algo sencillo: cargar móviles, mantener luces y nevera, y quizá abrir el portátil un rato. No quiero pagar ni cargar con una instalación pensada para vivir semanas fuera.", "Esta reseña no nace de una unidad probada por Juan. Es una evaluación editorial en primera persona construida con datos oficiales verificados y estimaciones explícitas; por eso no atribuye ruido, eficiencia real o calidad de acabados que no hayamos medido."],
    focus: [{ title: "El punto dulce está en el conjunto, no en una cifra", body: "Para mi escenario, 1.024 Wh tienen más sentido que perseguir una capacidad enorme. Los 1.200 W continuos cubren electrónica y una nevera portátil, mientras 11,5 kg siguen siendo razonables entre coche y parcela.", evidence: "editorial-analysis" }, { title: "El USB-C de 100 W evita un cargador más", body: "Poder alimentar un portátil compatible desde USB-C reduce cables y pérdidas frente a usar su adaptador de corriente alterna. Es una ventaja concreta en una mesa de camping pequeña.", evidence: "verified-fact" }],
    autonomy: ["Tomando como supuesto editorial un 85 % de energía utilizable, hay unos 870 Wh orientativos. No es una medición: la conversión, temperatura, consumo en reposo y cada aparato cambian el resultado.", "Yo haría una lista de consumos diarios antes de comprar. Una nevera no consume su potencia nominal cada minuto, mientras un hornillo eléctrico sí puede agotar la batería muy deprisa."],
    power: ["Los 1.200 W continuos permiten combinar cargas pequeñas, pero no dan carta blanca a hervidores, secadores o placas potentes. Hay que sumar los vatios simultáneos y dejar margen.", "El pico de 2.400 W es una declaración de ficha para arranques breves, no una potencia que deba mantenerse."],
    transport: ["Con 11,5 kg y un cuerpo de 324 × 262 × 205 mm, es la más fácil de colocar de este grupo. Sigue siendo un equipo que conviene asegurar en el maletero y proteger de agua, arena y sol directo."],
    pros: ["Relación equilibrada entre capacidad, potencia y peso", "USB-C de hasta 100 W", "Química LiFePO4 declarada", "Carga AC rápida sobre el papel"], cons: ["Sin expansión de batería", "Entrada solar limitada a 200 W", "Dos tomas AC", "No hay mediciones propias de eficiencia o ruido"],
    forWhom: ["Escapadas de dos o tres días con consumos moderados", "Quien prioriza peso y sencillez", "Usuarios que cargan portátil por USB-C"], notForWhom: ["Quien quiere cocinar habitualmente con resistencias eléctricas", "Estancias largas sin recarga", "Sistemas que deban crecer con baterías adicionales"],
    conclusion: ["Para mi fin de semana, la F1200 es la opción que elegiría primero por equilibrio. No promete convertir una tienda en una casa: ofrece una reserva útil y transportable si controlo los consumos.", "Antes de comprar confirmaría conectores del panel, potencia de la nevera y precio actual. Falta una prueba física para juzgar ruido, rendimiento real y comportamiento térmico."],
    faqs: [{ question: "¿La FOSSiBOT F1200 sirve para una nevera portátil?", answer: "Por potencia, muchas neveras portátiles encajan; la autonomía depende de su consumo real, ciclos del compresor y temperatura." }, { question: "¿Puede cargar un portátil por USB-C?", answer: "Sí, la ficha incluye un USB-C de hasta 100 W; el portátil debe aceptar esa potencia y protocolo." }, { question: "¿Se puede ampliar con otra batería?", answer: "No consta compatibilidad con una batería de expansión en la ficha oficial revisada." }, { question: "¿Esta review incluye una prueba real?", answer: "No. Es análisis editorial basado en especificaciones oficiales y estimaciones identificadas." }],
    relatedReviewSlugs: ["fossibot-f1800-review", "fossibot-f2400-review"], estimateLoadWatts: 60, imagePaths: ["/images/products/fossibot-f1200/hero.webp", "/images/products/fossibot-f1200/ports.webp", "/images/products/fossibot-f1200/camping.webp"]
  }),
  defineReview({
    id: "review-f1800-alex", slug: "fossibot-f1800-review", productId: "fossibot-f1800", personaId: "alex", status: "published", publishedAt: "2026-08-20", updatedAt: "2026-08-20",
    h1: "FOSSiBOT F1800 review: potencia y USB-C para trabajar en camper", eyebrow: "Trabajo remoto · Análisis por especificaciones",
    excerpt: "La misma capacidad base que la F1200, pero más potencia, entrada solar y dos USB-C de hasta 140 W para un puesto móvil.",
    seo: { title: "FOSSiBOT F1800 review para trabajar en camper", description: "Análisis de la FOSSiBOT F1800 para trabajo remoto: 1.024 Wh, 1.800 W, USB-C de 140 W, solar, carga y límites reales.", primaryKeyword: "FOSSiBOT F1800 review", semanticVariants: ["FOSSiBOT F1800 análisis", "power station para camper", "F1800 USB-C 140 W"], searchIntent: "commercial-investigation" },
    quickAnswer: { summary: "La F1800 parece especialmente bien orientada a un escritorio móvil: mantiene 1.024 Wh en un cuerpo relativamente manejable, eleva la salida a 1.800 W y ofrece dos USB-C de hasta 140 W.", advantage: "Conectividad USB-C potente y entrada solar de hasta 500 W.", limitation: "La capacidad no crece respecto a la F1200 y no admite expansión." },
    intro: ["Cuando trabajo desde la camper, mi prioridad no es enchufar el aparato más grande: es mantener portátil, router, monitor, cámara y discos sin estar vigilando cada porcentaje.", "Analizo la F1800 desde esa carga de trabajo, no como si hubiera medido una unidad. La experiencia narrada es un escenario editorial ficticio; las cifras proceden de la ficha oficial y los cálculos están etiquetados."],
    focus: [{ title: "USB-C es aquí una especificación central", body: "Dos salidas USB-C de hasta 140 W pueden alimentar portátiles exigentes compatibles sin ocupar las tomas AC. En un espacio móvil, esa simplificación importa tanto como la potencia total.", evidence: "verified-fact" }, { title: "Más potencia no significa más horas", body: "La salida continua sube a 1.800 W, pero la batería conserva 1.024 Wh. Es mejor para admitir cargas intensas puntuales, no para duplicar la jornada respecto a la F1200.", evidence: "editorial-analysis" }],
    autonomy: ["Con el supuesto del 85 %, la reserva orientativa ronda 870 Wh. Un puesto medio de portátil, red y pantalla debe calcularse con su consumo combinado, no con la potencia de los cargadores.", "Para jornadas consecutivas, la entrada solar de 500 W es más relevante que perseguir el pico de salida: determina cuánto puede recuperarse durante buenas horas solares."],
    power: ["Los 1.800 W dan margen para una cafetera o herramienta puntual, siempre sumando lo que ya consume el puesto de trabajo. El pico declarado de 3.600 W solo describe tolerancia breve.", "La onda senoidal pura y el UPS aparecen en las características oficiales, pero aquí no se ha medido el tiempo de transferencia ni la calidad eléctrica."],
    transport: ["Sus 11,25 kg son llamativos para estas cifras y facilitan moverla entre mesa y vehículo. La forma real del asa, estabilidad y resistencia necesitan inspección física antes de valorarlas."],
    pros: ["Dos USB-C de hasta 140 W", "Entrada solar de hasta 500 W", "1.800 W continuos con 11,25 kg declarados", "Aplicación, Wi‑Fi y Bluetooth declarados"], cons: ["Capacidad de 1.024 Wh sin expansión", "Solo dos tomas AC", "No se ha verificado el UPS en laboratorio", "Autonomía real pendiente de medición"],
    forWhom: ["Profesionales con portátiles USB-C exigentes", "Camper con buena oportunidad de recarga solar", "Quien necesita más potencia sin saltar a 20 kg"], notForWhom: ["Puestos que deben aguantar varios días sin sol ni conducción", "Quien quiere ampliar capacidad después", "Instalaciones fijas de alta demanda"],
    conclusion: ["Yo escogería la F1800 sobre la F1200 si mi portátil admite 140 W o si los 500 W solares forman parte del plan. La mejora es conectividad y recuperación, no más capacidad.", "Quedan por medir eficiencia AC/DC, consumo en reposo, ventiladores y rendimiento solar. Hasta entonces, son límites editoriales, no detalles menores."],
    faqs: [{ question: "¿La F1800 puede alimentar Starlink?", answer: "La potencia es suficiente para equipos Starlink habituales, pero la autonomía depende del modelo, consumo, clima y conversiones." }, { question: "¿Tiene dos USB-C de 140 W?", answer: "La ficha oficial revisada declara dos puertos USB-C PD 3.0 de hasta 140 W." }, { question: "¿Admite paneles solares?", answer: "Sí; declara hasta 500 W de entrada solar. Hay que comprobar tensión, corriente y conectores del panel." }, { question: "¿Se ha probado trabajando una jornada?", answer: "No. El escenario de Álex es editorial y no sustituye una prueba de autonomía." }],
    relatedReviewSlugs: ["fossibot-f1200-review", "fossibot-f2400-review"], estimateLoadWatts: 110, imagePaths: ["/images/products/fossibot-f1800/hero.webp", "/images/products/fossibot-f1800/usb-c.webp", "/images/products/fossibot-f1800/camper-office.webp"]
  }),
  defineReview({
    id: "review-f2400-laura", slug: "fossibot-f2400-review", productId: "fossibot-f2400", personaId: "laura", status: "published", publishedAt: "2026-08-20", updatedAt: "2026-08-20",
    h1: "FOSSiBOT F2400 review: capacidad para una caravana familiar", eyebrow: "Caravana familiar · Análisis por especificaciones",
    excerpt: "2.048 Wh, 2.400 W y un reparto amplio de conexiones para varios dispositivos, con 22 kg que exigen un lugar estable.",
    seo: { title: "FOSSiBOT F2400 review para caravana familiar", description: "Review editorial de la FOSSiBOT F2400 para caravana: capacidad, 2.400 W, puertos, autonomía estimada, carga y peso.", primaryKeyword: "FOSSiBOT F2400 review", semanticVariants: ["FOSSiBOT F2400 análisis", "power station para caravana", "F2400 autonomía"], searchIntent: "commercial-investigation" },
    quickAnswer: { summary: "La F2400 es la opción más equilibrada del catálogo para una familia que combina nevera, luces, móviles y aparatos puntuales: dobla la capacidad de los modelos pequeños y añade conexiones DC útiles.", advantage: "2.048 Wh y un conjunto de puertos amplio, incluida salida RV de 12 V.", limitation: "Sus 22 kg reducen la espontaneidad y no puede ampliarse con otra batería." },
    intro: ["En familia siempre hay algo cargando. Mi pregunta no es si puedo conectar un móvil, sino si puedo mantener la nevera, las luces y varias pantallas sin organizar turnos todo el día.", "Esta voz representa ese caso de uso, pero Laura no es una compradora real ni ha probado la unidad. La valoración deriva de especificaciones oficiales y cálculos prudentes, no de testimonios inventados."],
    focus: [{ title: "La capacidad aporta margen familiar", body: "2.048 Wh permiten absorber más consumos simultáneos y errores de planificación que los modelos de 1.024 Wh. Ese colchón resulta más valioso que una potencia extrema para el día a día.", evidence: "editorial-analysis" }, { title: "La salida RV ordena la instalación de 12 V", body: "La ficha declara una salida RV regulada de 12 V y 25 A, además de toma de coche y DC5521. Puede simplificar consumos de corriente continua si los conectores son compatibles.", evidence: "verified-fact" }],
    autonomy: ["Aplicando el supuesto editorial del 85 %, quedarían alrededor de 1.741 Wh orientativos. Repartidos entre nevera, iluminación y electrónica, el resultado depende mucho del ciclo de la nevera.", "La autonomía debe calcularse por día completo. Una cafetera consume mucho durante minutos; una nevera consume menos, pero durante muchas horas."],
    power: ["2.400 W continuos permiten más combinaciones domésticas, aunque varios aparatos de calor pueden superar el límite juntos. El pico de 4.800 W no debe leerse como potencia sostenida.", "Tres tomas AC y varias salidas USB/DC reducen adaptadores, pero conviene repartir cables para evitar tropiezos y mantener ventilación."],
    transport: ["Con 22 kg, yo la trataría como equipo semi fijo dentro de la caravana. Antes de salir decidiría su ubicación, anclaje y acceso a ventilación, en lugar de moverla cada noche."],
    pros: ["Capacidad de 2.048 Wh", "2.400 W continuos", "Salida RV regulada de 12 V", "Amplia variedad de USB y DC"], cons: ["22 kg de peso", "Sin batería de expansión", "Carga de vehículo lenta según fabricante", "Sin datos propios de ruido o eficiencia"],
    forWhom: ["Familias con nevera y varios dispositivos", "Caravanas con consumos DC", "Quien quiere margen sin entrar en sistemas expandibles"], notForWhom: ["Camping a pie o con cambios constantes de parcela", "Necesidades futuras por encima de 2 kWh sin recarga", "Quien solo carga electrónica ligera"],
    conclusion: ["Para una caravana familiar, la F2400 me parece el centro lógico de esta gama. La capacidad adicional resuelve más problemas cotidianos que los vatios de escaparate.", "La compra debe acompañarse de un presupuesto energético y una ubicación segura. Una futura prueba física tendrá que confirmar ruido, eficiencia y comodidad de uso."],
    faqs: [{ question: "¿Cuánto dura la FOSSiBOT F2400?", answer: "No existe una cifra única: depende de los vatios y horas de cada aparato. Esta página muestra un cálculo orientativo con pérdidas asumidas." }, { question: "¿Puede con una cafetera?", answer: "Muchas cafeteras quedan por debajo de 2.400 W, pero hay que comprobar potencia de arranque y otros consumos simultáneos." }, { question: "¿Tiene salida para RV?", answer: "Sí, la ficha declara una salida RV regulada de 12 V y hasta 25 A." }, { question: "¿Es una prueba de larga duración?", answer: "No. Es una evaluación editorial sin unidad física probada." }],
    relatedReviewSlugs: ["fossibot-f1800-review", "fossibot-f3600-pro-review"], estimateLoadWatts: 140, imagePaths: ["/images/products/fossibot-f2400/hero.webp", "/images/products/fossibot-f2400/ports.webp", "/images/products/fossibot-f2400/caravan.webp"]
  }),
  defineReview({
    id: "review-f3600-carmen", slug: "fossibot-f3600-pro-review", productId: "fossibot-f3600-pro", personaId: "carmen", expansionBatteryIds: ["fossibot-fb3840"], status: "published", publishedAt: "2026-08-20", updatedAt: "2026-08-20",
    h1: "FOSSiBOT F3600 Pro review: autonomía ampliable para autocaravana", eyebrow: "Viajes largos · Sistema ampliable",
    excerpt: "Una base de 3.840 Wh que puede crecer con la FB3840, pensada para estancias largas más que para moverla continuamente.",
    seo: { title: "FOSSiBOT F3600 Pro review con batería FB3840", description: "Analizamos la FOSSiBOT F3600 Pro y su batería FB3840 para autocaravana: capacidad ampliable, potencia, carga, peso y límites.", primaryKeyword: "FOSSiBOT F3600 Pro review", semanticVariants: ["F3600 Pro análisis", "F3600 Pro FB3840", "power station ampliable autocaravana"], searchIntent: "commercial-investigation" },
    quickAnswer: { summary: "La F3600 Pro encaja cuando la prioridad es pasar más tiempo sin buscar enchufe: parte de 3.840 Wh y admite hasta dos FB3840, aunque el sistema crece también en peso, coste y espacio.", advantage: "Capacidad ampliable y hasta 4.200 W de entrada combinada declarada.", limitation: "42 kg en la unidad principal; con módulos deja de ser una solución portátil cotidiana." },
    intro: ["En viajes largos quiero dejar de hacer cuentas cada pocas horas. Prefiero que la energía sea una infraestructura tranquila, con margen para nevera, café, televisión y electrónica.", "Esa tranquilidad se evalúa aquí sobre el papel. Carmen es un perfil editorial ficticio; no afirmamos haber conducido, cargado ni convivido con este sistema."],
    focus: [{ title: "La expansión cambia la decisión", body: "La FB3840 no es otra power station: es un módulo de capacidad compatible. Una unidad elevaría el conjunto a 7.680 Wh nominales y dos a 11.520 Wh, según suma de capacidades declaradas.", evidence: "estimate" }, { title: "La movilidad pasa a segundo plano", body: "Con 42 kg para la estación y 37,8 kg por módulo, el planteamiento correcto es reservar un emplazamiento estable y revisar reparto de cargas del vehículo.", evidence: "editorial-analysis" }],
    autonomy: ["Con un supuesto de aprovechamiento del 85 %, la base ofrece unos 3.264 Wh orientativos. El cálculo no incorpora consumo en reposo ni curvas de inversor medidas.", "La expansión puede reducir la frecuencia de recarga, pero no sustituye una estrategia solar o de red en viajes prolongados."],
    power: ["3.600 W continuos dan margen para consumos domésticos, pero la suma simultánea sigue mandando. Los 7.200 W de pico declarados corresponden a eventos breves.", "El fabricante declara UPS y onda senoidal pura; falta una prueba independiente del tiempo de transferencia y estabilidad bajo carga."],
    transport: ["Yo no planearía subir y bajar 42 kg con frecuencia. La instalación debe contemplar ventilación, fijación, acceso a conexiones y el peso adicional de cada FB3840."],
    expansion: ["La FB3840 añade 3.840 Wh y pesa 37,8 kg. El fabricante declara hasta dos unidades compatibles con la F3600 Pro.", "El módulo dispone de BMS y algunas salidas/entrada solar propias según ficha, pero no sustituye por sí solo las salidas AC de la estación principal."],
    pros: ["3.840 Wh de base", "Hasta dos FB3840 compatibles", "3.600 W continuos", "Entrada combinada declarada de 4.200 W"], cons: ["42 kg antes de añadir módulos", "Coste y espacio del sistema expandido", "La expansión aumenta complejidad de instalación", "Rendimiento real sin medir"],
    forWhom: ["Autocaravanas con ubicación permanente para el equipo", "Viajes largos y consumos diarios variados", "Quien prevé ampliar capacidad"], notForWhom: ["Quien necesita cargar el equipo a mano cada día", "Escapadas con consumos ligeros", "Vehículos sin margen de carga útil o espacio"],
    conclusion: ["Para viajar largo, yo valoraría la F3600 Pro como sistema, no como caja portátil. La FB3840 permite crecer, pero cada paso debe justificarse con consumos y carga útil.", "Sin medidas propias no puedo prometer silencio, eficiencia o facilidad de instalación. Esas son las prioridades de una prueba física futura."],
    faqs: [{ question: "¿Qué es la FB3840?", answer: "Es una batería de expansión compatible que añade capacidad a la F3600 Pro; no es una power station AC completa independiente." }, { question: "¿Cuánta capacidad tiene con una FB3840?", answer: "La suma nominal es 7.680 Wh. La energía realmente utilizable será menor y depende del sistema." }, { question: "¿Cuántas baterías admite?", answer: "La información oficial revisada declara hasta dos módulos FB3840." }, { question: "¿Se ha probado el conjunto en autocaravana?", answer: "No. El encaje es análisis editorial por especificaciones." }],
    relatedReviewSlugs: ["fossibot-f2400-review", "fossibot-f7200-review"], estimateLoadWatts: 220, imagePaths: ["/images/products/fossibot-f3600-pro/hero.webp", "/images/products/fossibot-f3600-pro/ports.webp", "/images/products/fossibot-f3600-pro/fb3840-system.webp"]
  }),
  defineReview({
    id: "review-f7200-sergio", slug: "fossibot-f7200-review", productId: "fossibot-f7200", personaId: "sergio", expansionBatteryIds: ["fossibot-fb5222"], status: "published", publishedAt: "2026-08-20", updatedAt: "2026-08-20",
    h1: "FOSSiBOT F7200 review: potencia y expansión para uso off-grid", eyebrow: "Off-grid · Sistema de alta potencia",
    excerpt: "5.222,4 Wh, 7.200 W, carga solar de alta y baja tensión y expansión FB5222: una instalación, no una batería para pasear.",
    seo: { title: "FOSSiBOT F7200 review para uso off-grid", description: "Review técnica de la FOSSiBOT F7200 y FB5222: 7.200 W, 5.222 Wh, solar, expansión, instalación y límites sin pruebas falsas.", primaryKeyword: "FOSSiBOT F7200 review", semanticVariants: ["FOSSiBOT F7200 análisis", "F7200 FB5222", "power station off-grid 7200 W"], searchIntent: "commercial-investigation" },
    quickAnswer: { summary: "La F7200 tiene cifras de sistema estacionario: 7.200 W continuos, 5.222,4 Wh y expansión con FB5222. Solo tiene sentido con consumos calculados, espacio, solar compatible e instalación segura.", advantage: "Potencia alta, doble planteamiento solar y capacidad expandible.", limitation: "70 kg, complejidad eléctrica y necesidad de instalación profesional para el terminal cableado." },
    intro: ["En off-grid no me sirve una lista de cifras sin contexto. Quiero saber qué parte es útil, cómo se recarga, qué pesa el sistema y qué requiere un electricista.", "No he sometido esta F7200 a cargas ni paneles. Sergio es la perspectiva técnica de Carga Nómada, no un testimonio real; cualquier dato de rendimiento pendiente queda fuera del veredicto."],
    focus: [{ title: "Esto debe planificarse como instalación", body: "Setenta kilos, salida cableada y entradas solares de alta tensión exigen diseño, protecciones y profesional cualificado. No debe improvisarse a partir de una review.", evidence: "editorial-analysis" }, { title: "La expansión escala capacidad y masa", body: "Una FB5222 eleva la capacidad nominal conjunta a 10.444,8 Wh y dos a 15.667,2 Wh. Cada módulo añade 55 kg, antes de cableado y estructura.", evidence: "estimate" }],
    autonomy: ["Con el mismo supuesto editorial del 85 %, la unidad base representa unos 4.439 Wh orientativos. Una carga constante de 500 W no equivale a nueve horas garantizadas: faltan pérdidas, temperatura y consumo propio.", "Para dimensionar off-grid hay que trabajar con Wh diarios y el peor periodo solar razonable, no con la potencia máxima del inversor."],
    power: ["7.200 W continuos abren cargas simultáneas serias. También elevan requisitos de sección de cable, protecciones y seguridad; la salida por terminal debe tratarla un profesional.", "El pico declarado de 9.000 W es limitado y no reemplaza el dato de arranque real de bombas o herramientas."],
    transport: ["Con 70 kg, el término portátil es formal. Las ruedas ayudan a desplazarla sobre firme adecuado, pero no resuelven escalones, vehículo ni carga útil. Su sitio debe decidirse antes de comprar."],
    expansion: ["La FB5222 añade 5.222,4 Wh y pesa 55 kg. No debe confundirse con una estación completa: amplía el almacenamiento de la F7200.", "La ficha declara hasta dos módulos. El sistema máximo requiere revisar espacio, ventilación, soporte y presupuesto, no solo autonomía."],
    pros: ["7.200 W continuos declarados", "5.222,4 Wh de base", "Hasta dos FB5222", "Entradas solares de alta y baja tensión"], cons: ["70 kg en la estación", "Instalación técnica y protecciones", "Sistema expandido muy voluminoso", "Sin curva independiente de eficiencia ni carga"],
    forWhom: ["Instalaciones off-grid con demanda calculada", "Taller o base móvil con cargas altas", "Usuarios con diseño solar y apoyo profesional"], notForWhom: ["Compra impulsiva para camping", "Quien necesita levantarla con frecuencia", "Usuarios sin experiencia eléctrica ni instalador"],
    conclusion: ["Yo solo elegiría la F7200 después de cerrar un balance energético y un esquema de instalación. Sus cifras son atractivas, pero el valor depende de aprovecharlas con seguridad.", "La próxima fase debe ser una prueba instrumental: eficiencia a varias cargas, consumo en vacío, ruido, solar y arranques. Esta página no sustituye esos resultados."],
    faqs: [{ question: "¿La F7200 necesita un electricista?", answer: "La conexión por terminal y una instalación fija deben realizarlas profesionales cualificados siguiendo normativa y manual del fabricante." }, { question: "¿Qué capacidad alcanza con una FB5222?", answer: "La suma nominal es 10.444,8 Wh; no equivale a energía AC utilizable garantizada." }, { question: "¿Sirve para placas solares?", answer: "Declara entradas solares de alta y baja tensión. Hay que validar rangos eléctricos, conectores y protecciones con documentación vigente." }, { question: "¿Esta review mide los 7.200 W?", answer: "No. La potencia es una especificación del fabricante, no una medición de Carga Nómada." }],
    relatedReviewSlugs: ["fossibot-f3600-pro-review", "fossibot-f2400-review"], estimateLoadWatts: 500, imagePaths: ["/images/products/fossibot-f7200/hero.webp", "/images/products/fossibot-f7200/terminals.webp", "/images/products/fossibot-f7200/fb5222-system.webp"]
  })
] as const satisfies readonly Review[];

export function getReviewBySlug(slug: string): Review | undefined { return reviews.find((review) => review.slug === slug); }
export function getReviewsForProduct(productId: string): readonly Review[] { return reviews.filter((review) => review.productId === productId); }
