import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { getProductById } from "@/content/products";
import styles from "../guide.module.css";
import scale from "./scale.module.css";

const slug="wh-power-station",publishedAt="2026-08-21",siteUrl=process.env.NEXT_PUBLIC_SITE_URL||"https://carganomada.com";
const title="Qué son los Wh en una power station";
const seoTitle="Qué son los Wh de una power station | Carga Nómada";
const description="Aprende qué significan los Wh de una power station, cómo interpretar su capacidad y cómo calcular cuánta energía necesitas para tus aparatos.";
export const metadata:Metadata={title:{absolute:seoTitle},description,alternates:{canonical:`/guias/${slug}`},openGraph:{type:"article",url:`/guias/${slug}`,title:seoTitle,description,siteName:"Carga Nómada",locale:"es_ES",publishedTime:publishedAt,modifiedTime:publishedAt},twitter:{card:"summary",title:seoTitle,description}};
const f1200=getProductById("fossibot-f1200")!,f1800=getProductById("fossibot-f1800")!,f2400=getProductById("fossibot-f2400")!,f3600=getProductById("fossibot-f3600-pro")!;
const capacityFill=(capacityWh:number)=>`${capacityWh/f3600.capacityWh*100}%`;

export default function Guide(){const canonical=`${siteUrl}/guias/${slug}`;const schema={"@context":"https://schema.org","@graph":[{"@type":"BreadcrumbList","@id":`${canonical}#breadcrumb`,itemListElement:[{"@type":"ListItem",position:1,name:"Inicio",item:siteUrl},{"@type":"ListItem",position:2,name:"Guías",item:`${siteUrl}/guias`},{"@type":"ListItem",position:3,name:title,item:canonical}]},{"@type":"Article","@id":`${canonical}#article`,mainEntityOfPage:canonical,headline:title,description,datePublished:publishedAt,dateModified:publishedAt,inLanguage:"es",isAccessibleForFree:true,author:{"@id":`${siteUrl}#organization`},publisher:{"@id":`${siteUrl}#organization`},breadcrumb:{"@id":`${canonical}#breadcrumb`}}]};return <><main className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/>
<header className={styles.hero}><div className="container"><nav className={styles.breadcrumb} aria-label="Migas de pan"><Link href="/">Inicio</Link><span>/</span><Link href="/guias">Guías</Link><span>/</span><span>Wh en una power station</span></nav><p className={styles.kicker}>Guía básica · Capacidad</p><h1>Qué son los Wh en una power station</h1><p className={styles.lead}>Los Wh indican cuánta energía puede almacenar una power station. Cuantos más Wh tengas, más tiempo podrás alimentar tus aparatos, aunque la autonomía final depende de cuánto consuman y de las pérdidas del sistema.</p><div className={styles.byline}><span>Equipo editorial de Carga Nómada</span><span>Publicado y revisado el 21 de agosto de 2026</span></div></div></header>
<div className="container"><section className={styles.quick} aria-labelledby="resumen"><div><p className={styles.kicker}>En pocas palabras</p><h2 id="resumen">Los Wh son el tamaño del depósito</h2></div><div className={styles.formula} role="img" aria-label="Vatios multiplicados por horas es igual a vatios hora"><span>Potencia (W)</span><i/><span>Tiempo (h)</span><b>×</b><strong>energía (Wh)</strong></div><p>Un aparato de 100 W utilizado durante una hora consume idealmente 100 Wh. Pensar en un depósito ayuda a entender la capacidad, aunque es solo una analogía: la batería y sus conversiones tienen límites y pérdidas.</p></section><div className={styles.layout}><article className={styles.article}>
<section id="significado"><p className={styles.index}>01 · Definición sencilla</p><h2>Qué mide exactamente un Wh</h2><p>Un vatio hora es una unidad de energía. Describe la cantidad resultante de mantener una potencia de un vatio durante una hora. Por ejemplo, una luz que consume 10 W durante cinco horas utiliza 50 Wh; un portátil a 60 W durante dos horas utiliza 120 Wh.</p><p>En una power station, la cifra de Wh funciona como la capacidad nominal del depósito eléctrico. Una unidad de 2.048 Wh almacena, sobre el papel, el doble de energía que una de 1.024 Wh. Eso no significa que dure el doble en cualquier situación: la carga conectada, el tipo de salida, la temperatura y las pérdidas pueden cambiar la proporción real. Si aún necesitas contexto sobre el equipo completo, empieza por <Link href="/guias/que-es-una-power-station">qué es una power station y cómo funciona</Link>.</p></section>
<section id="escala"><p className={styles.index}>02 · Ver la diferencia</p><h2>Cómo cambia el depósito entre modelos</h2><div className={scale.scale} role="img" aria-label={`Comparación de capacidad: F1200 ${f1200.capacityWh} Wh, F2400 ${f2400.capacityWh} Wh y F3600 Pro ${f3600.capacityWh} Wh`}><article style={{"--fill":capacityFill(f1200.capacityWh)} as React.CSSProperties}><span>F1200</span><strong>{f1200.capacityWh.toLocaleString("es-ES")} Wh</strong><i/></article><article style={{"--fill":capacityFill(f2400.capacityWh)} as React.CSSProperties}><span>F2400</span><strong>{f2400.capacityWh.toLocaleString("es-ES")} Wh</strong><i/></article><article style={{"--fill":capacityFill(f3600.capacityWh)} as React.CSSProperties}><span>F3600 Pro</span><strong>{f3600.capacityWh.toLocaleString("es-ES")} Wh</strong><i/></article></div><p>La escala representa capacidad nominal, no autonomía garantizada. Una estación mayor suele pesar y costar más, y también tarda más en cargarse si la potencia de entrada no aumenta en la misma proporción.</p></section>
<section id="ejemplos"><p className={styles.index}>03 · Números cotidianos</p><h2>Ejemplos para entender los Wh</h2><div className={styles.exampleGrid}><article><span>Luz</span><strong>50 Wh</strong><code>10 W × 5 h</code><p>Una luz estable durante una tarde.</p></article><article><span>Portátil</span><strong>180 Wh</strong><code>60 W × 3 h</code><p>Supuesto constante de trabajo ligero.</p></article><article><span>Router</span><strong>240 Wh</strong><code>10 W × 24 h</code><p>Poca potencia, pero muchas horas.</p></article><article><span>Cafetera</span><strong>83 Wh</strong><code>1.000 W × 5/60 h</code><p>Mucha potencia durante pocos minutos.</p></article></div><p>Los consumos son ejemplos editoriales, no valores universales. La potencia de un portátil cambia con la carga de trabajo; una nevera funciona por ciclos; una cafetera puede tener otra resistencia. Mide tus aparatos cuando la decisión de compra dependa del resultado.</p></section>
<section id="nominal-util"><p className={styles.index}>04 · El matiz importante</p><h2>Capacidad nominal y energía utilizable</h2><p>La cifra anunciada describe la energía nominal almacenada por la batería. Tus aparatos reciben menos porque la electrónica, los cables y el inversor consumen parte durante la conversión. La propia estación también necesita energía para mantener pantalla, ventiladores y sistemas activos.</p><p>Para enseñar cálculos comparables, Carga Nómada utiliza a veces un supuesto simplificado del 85 % utilizable. Así, 1.024 Wh × 0,85 son unos 870 Wh orientativos. No afirmamos que todas las estaciones tengan exactamente esa eficiencia: el resultado real depende del producto, la carga y la salida.</p><div className={styles.equation}><small>Supuesto editorial</small><code>1.024 Wh × 0,85 ≈ 870 Wh útiles</code><code>870 Wh ÷ 60 W ≈ 14,5 horas</code><p>Estimación con una carga constante de 60 W; no es una prueba del producto ni una promesa de duración.</p></div><p>Puedes aplicar este supuesto a tus propios aparatos con la <Link href="/encontrar-power-station">calculadora de capacidad y autonomía</Link>.</p></section>
<section id="w"><p className={styles.index}>05 · No confundas unidades</p><h2>Los Wh no te dicen qué aparatos puedes conectar</h2><p>Los Wh hablan de energía almacenada. Los W de salida hablan de la potencia que la estación puede entregar en un momento dado. Una batería con muchos Wh puede durar bastante con cargas pequeñas y, aun así, no disponer del inversor necesario para una cafetera potente.</p><p>La F1200 y la F1800 lo muestran con datos del catálogo: ambas almacenan {f1200.capacityWh.toLocaleString("es-ES")} Wh, pero entregan {f1200.continuousOutputWatts.toLocaleString("es-ES")} W y {f1800.continuousOutputWatts.toLocaleString("es-ES")} W continuos, respectivamente. La F1800 admite más potencia sin almacenar más energía. La guía sobre la <Link href="/guias/w-vs-wh">diferencia entre W y Wh</Link> desarrolla esta comparación.</p></section>
<section id="necesitas"><p className={styles.index}>06 · Aplicarlo a tu caso</p><h2>Cuántos Wh necesitas</h2><p>No existe una capacidad universal. Primero suma la energía diaria de tus aparatos, después decide cuántos días quieres cubrir y, por último, contempla pérdidas y un margen razonable. La posibilidad de recargar durante el viaje también cambia la capacidad necesaria.</p><p>Esta guía se centra en entender la unidad. Para convertir tus consumos en una cifra de batería, sigue el método completo sobre <Link href="/guias/calcular-autonomia-power-station">cómo calcular la autonomía de una power station</Link>.</p></section>
<section id="comparar"><p className={styles.index}>07 · Modelos en contexto</p><h2>Qué significan los Wh al comparar</h2><p>Los {f1200.capacityWh.toLocaleString("es-ES")} Wh de la F1200 encajan en una escala de escapadas y consumos moderados; puedes verlo en la <Link href="/reviews/fossibot-f1200-review">review de la FOSSiBOT F1200 para camping</Link>. La F2400 duplica la capacidad hasta {f2400.capacityWh.toLocaleString("es-ES")} Wh y aporta más colchón para una familia, como explicamos en la <Link href="/reviews/fossibot-f2400-review">review de la FOSSiBOT F2400 para caravana</Link>.</p><p>La cifra mayor no es automáticamente la mejor compra. Compara también potencia, puertos, recarga, peso y posibilidad de expansión. Si vas a moverla a diario, una capacidad que apenas utilizas puede convertirse en lastre.</p></section>
<section id="errores"><p className={styles.index}>08 · Evita estas trampas</p><h2>Errores frecuentes con los Wh</h2><div className={styles.mistakes}><div><strong>Leer Wh como W</strong><p>Una cifra indica energía; la otra, potencia.</p></div><div><strong>Esperar el 100 %</strong><p>La capacidad nominal no llega íntegra a la carga.</p></div><div><strong>Olvidar las horas</strong><p>Un equipo pequeño conectado todo el día puede gastar bastante.</p></div><div><strong>Comprar el depósito mayor</strong><p>Más capacidad también suele añadir peso, coste y tiempo de carga.</p></div></div></section>
<section id="faq" className={styles.faq}><p className={styles.index}>09 · Preguntas frecuentes</p><h2>Dudas sobre Wh y capacidad</h2><details><summary>¿Qué significan 1.000 Wh?</summary><p>Representan energía suficiente, en condiciones ideales, para 1.000 W durante una hora o 100 W durante diez. En uso real tendrás pérdidas.</p></details><details><summary>¿Más Wh significan más potencia?</summary><p>No. Más Wh significan más energía almacenada. La potencia máxima depende de los W continuos y de pico de la salida.</p></details><details><summary>¿Cuántos Wh necesito para una nevera?</summary><p>Consulta o mide sus Wh en 24 horas y suma los demás aparatos. Los ciclos del compresor y la temperatura cambian el consumo; usa la <Link href="/guias/calcular-autonomia-power-station">guía de cálculo de autonomía</Link> para dimensionar el conjunto.</p></details><details><summary>¿Son iguales los Wh nominales y útiles?</summary><p>No necesariamente. Las conversiones y el consumo interno reducen la energía que finalmente reciben tus aparatos.</p></details></section>
<section id="siguiente"><p className={styles.index}>10 · Siguiente paso</p><h2>Distingue capacidad y potencia</h2><div className={styles.nextGrid}><div><h3>Sigue aprendiendo</h3><p>Separa lo que almacena la batería de lo que puede entregar.</p><Link href="/guias/w-vs-wh">Entender W frente a Wh →</Link></div><div><h3>Aplica los Wh</h3><p>Convierte tus consumos y días en una capacidad orientativa.</p><Link href="/guias/calcular-autonomia-power-station">Calcular autonomía →</Link></div></div></section>
<section className={styles.sources}><p className={styles.index}>11 · Metodología</p><h2>Cómo se han preparado los ejemplos</h2><p>Las capacidades proceden del catálogo verificado del proyecto. Los consumos y el 85 % utilizable son supuestos editoriales identificados como tales. Para una compra, mide tus equipos y consulta las fichas vigentes.</p></section>
</article><aside className={styles.aside} aria-label="Contenido"><span>En esta guía</span><a href="#significado">Qué mide</a><a href="#escala">Capacidades</a><a href="#ejemplos">Ejemplos</a><a href="#nominal-util">Energía útil</a><a href="#w">Wh y W</a><a href="#necesitas">Cuántos necesitas</a><a href="#errores">Errores</a><a href="#faq">Preguntas</a></aside></div></div></main><SiteFooter/></>}
