import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { getProductById } from "@/content/products";
import styles from "../use-case.module.css";

const publishedAt="2026-08-22";
const siteUrl=process.env.NEXT_PUBLIC_SITE_URL??"http://localhost:3000";
const title="Qué power station necesitas para una camper";
const description="Calcula qué power station necesitas para una camper según nevera 12 V, portátil, autonomía y recarga en ruta, solar o red.";
export const metadata:Metadata={title:{absolute:"Power station para camper: qué necesitas | Carga Nómada"},description,alternates:{canonical:"/usos/camper"},openGraph:{type:"article",url:"/usos/camper",title,description,siteName:"Carga Nómada",locale:"es_ES",publishedTime:publishedAt,modifiedTime:publishedAt},twitter:{card:"summary",title,description}};

const f1200=getProductById("fossibot-f1200")!;const f1800=getProductById("fossibot-f1800")!;const f2400=getProductById("fossibot-f2400")!;
const n=(v:number|undefined)=>v?.toLocaleString("es-ES")??"no declarado";
const size=(p:typeof f1200)=>p.dimensions?`${p.dimensions.widthMm} × ${p.dimensions.depthMm} × ${p.dimensions.heightMm} mm`:"no declaradas";

export default function CamperUsePage(){const canonical=`${siteUrl}/usos/camper`;const schema={"@context":"https://schema.org","@graph":[{"@type":"BreadcrumbList","@id":`${canonical}#breadcrumb`,itemListElement:[{"@type":"ListItem",position:1,name:"Inicio",item:siteUrl},{"@type":"ListItem",position:2,name:"Usos",item:`${siteUrl}/usos`},{"@type":"ListItem",position:3,name:"Camper",item:canonical}]},{"@type":"Article","@id":`${canonical}#article`,mainEntityOfPage:canonical,headline:title,description,datePublished:publishedAt,dateModified:publishedAt,inLanguage:"es",isAccessibleForFree:true,author:{"@id":`${siteUrl}#organization`},publisher:{"@id":`${siteUrl}#organization`},breadcrumb:{"@id":`${canonical}#breadcrumb`}}]};return <><main className={styles.page}>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/>
<header className={styles.hero}><div className="container"><nav className={styles.breadcrumb} aria-label="Migas de pan"><Link href="/">Inicio</Link><span>/</span><Link href="/usos">Usos</Link><span>/</span><span>Camper</span></nav><p className={styles.kicker}>Caso de uso 02 · Camper</p><h1>{title}</h1><p className={styles.lead}>En una camper no basta con cubrir una noche: la nevera trabaja cada día, el portátil y la conectividad se repiten, y la autonomía depende de cuánto recuperas al conducir, al sol o al llegar a la red.</p><div className={styles.heroFacts}><span>Nevera 12 V</span><span>Recarga en ruta</span><span>Autonomía por días</span></div><div className={styles.byline}><span>Equipo editorial de Carga Nómada</span><span>Publicado y revisado el 22 de agosto de 2026</span></div></div></header>
<div className="container"><section className={styles.quick}><div><p className={styles.kicker}>Respuesta rápida</p><h2>Calcula un día y diseña cómo reponerlo</h2></div><ol><li><span>01</span>Mide la nevera durante 24 h</li><li><span>02</span>Suma trabajo, luz y cargas</li><li><span>03</span>Multiplica por días sin recarga</li><li><span>04</span>Comprueba W y puertos</li><li><span>05</span>Define coche, solar o red</li></ol><p>Una camper sencilla puede rondar 1,4 kWh en tres días; una conectada supera 1,7 kWh en dos. Son ejemplos editoriales: tus mediciones mandan.</p></section></div>
<article>
<section className={styles.section}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>01 · La decisión camper</p><h2>Capacidad suficiente, pero también continuidad</h2><p>La estación debe caber, ventilar, ofrecer las salidas que usarás y recuperar una parte razonable del consumo diario.</p></div><div className={styles.priorityGrid}><article><span>BASE</span><strong>Wh/día</strong><p>Nevera, luces y cargas que se repiten.</p></article><article><span>TRABAJO</span><strong>W + h</strong><p>Portátil y conectividad durante horas.</p></article><article><span>EN RUTA</span><strong>Wh repuestos</strong><p>Entrada del vehículo por horas conduciendo.</p></article><article><span>EN MUEBLE</span><strong>mm + aire</strong><p>Medidas, cables, acceso y ventilación.</p></article></div><p className={styles.text}>Valida picos y simultaneidad en <Link href="/guias/que-puedo-conectar-power-station">qué puedes conectar a una power station</Link>.</p></div></section>
<section className={`${styles.section} ${styles.scenarios}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>02 · Tres rutinas camper</p><h2>De una base sencilla a una rutina de mayor consumo</h2><p>Los consumos son supuestos editoriales. El 20 % es un colchón de planificación coherente, no una pérdida fija del sistema.</p></div><div className={styles.scenarioGrid}>
<Scenario no="01" label="Camper sencilla · 3 días" name="Nevera, luz y pequeñas cargas" energy="1.377" margin="1.652" power="≈100 W + arranque" lines={["Nevera: 350 Wh/día × 3 = 1.050 Wh","Móviles: 2 × 15 Wh × 3 = 90 Wh","Luces: 2 × 8 W × 4 h × 3 = 192 Wh","Cámara: 15 Wh/día × 3 = 45 Wh"]} total="Total 1.377 Wh; con 20 % = 1.652,4 Wh." note="Prioriza salida 12 V estable y una recarga posible. Una estación de 1.024 Wh necesita reposición durante este escenario."/>
<Scenario no="02" label="Camper conectada · 2 días" name="Nevera, portátil y router" energy="1.730" margin="2.076" power="≈180 W + arranque" lines={["Nevera: 350 Wh/día × 2 = 700 Wh","Portátil: 65 W × 5 h × 2 = 650 Wh","Router: 12 W × 8 h × 2 = 192 Wh","Móviles: 2 × 15 Wh × 2 = 60 Wh","Luces: 2 × 8 W × 4 h × 2 = 128 Wh"]} total="Total 1.730 Wh; con 20 % = 2.076 Wh." note="Prioriza USB-C suficiente, buena entrada solar y recarga diaria. USB-C puede evitar ocupar una toma AC si ambos equipos son compatibles."/>
<Scenario wide no="03" label="Camper con más comodidad · 2 días" name="Starlink, monitor y café puntual" energy="2.505" margin="3.006" power="≈1.200 W" lines={["Nevera: 350 Wh/día × 2 = 700 Wh","Portátil: 65 W × 4 h × 2 = 520 Wh","Starlink: 60 W × 6 h × 2 = 720 Wh","Móviles + luces: 60 Wh + 128 Wh = 188 Wh","Monitor: 35 W × 3 h × 2 = 210 Wh","Cafetera: 1.000 W × 5/60 h × 2 ≈ 166,7 Wh"]} total="Total ≈2.504,7 Wh; con 20 % ≈3.005,6 Wh." note="Prioriza recarga estructural. Ni 2.048 Wh nominales cubren este plan de dos días sin reponer energía."/>
</div><aside className={styles.notice}><strong>Adáptalo a tu camper</strong><p>Suma W × horas y multiplica por días entre recargas. La <Link href="/guias/calcular-autonomia-power-station">guía de autonomía</Link> explica cómo estimar la energía utilizable.</p></aside></div></section>
<section className={styles.section}><div className="container"><div className={styles.split}><div><p className={styles.index}>03 · La carga base</p><h2>La nevera se calcula en 24 horas</h2></div><div><p>Una nevera de compresor alterna trabajo y descanso. Temperatura, consigna, ventilación y aperturas cambian el resultado.</p><p>Mide Wh durante 24 horas en condiciones parecidas al viaje. Comprueba también tensión, conector, arranque y límite DC. En los ejemplos usamos <strong>350 Wh/día</strong> solo como hipótesis trazable.</p></div></div></div></section>
<section className={`${styles.section} ${styles.models}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>04 · Ruta energética</p><h2>Conducir, aparcar, enchufar</h2><p>La potencia máxima de entrada no equivale a producción constante.</p></div><div className={styles.modelGrid}><article><span>01 · EN MARCHA</span><h3>Vehículo</h3><p>F1200 y F1800 admiten 12 V hasta 120 W; los tiempos declarados usan 96 W durante 640 min y 120 W durante 540 min. F2400 admite 100 W a 12 V o 200 W a 24 V, con 1.020 o 510 min declarados.</p><b>No descargues la batería de arranque con el motor parado. Valida toma, fusible y manual.</b></article><article><span>02 · APARCADA</span><h3>Solar</h3><p>Máximos de catálogo: 200 W en F1200 y 500 W en F1800/F2400. Un panel plegable se orienta; uno instalado evita montaje, pero queda fijo.</p><b>Comprueba electricidad y sombra en la <Link href="/guias/placas-solares-power-station">guía solar</Link>.</b></article><article><span>03 · PARADA</span><h3>Red</h3><p>Camping o vivienda permiten recuperar energía con más previsibilidad antes de otra etapa.</p><b>Respeta los límites del punto, cableado y cargador.</b></article></div></div></section>
<section className={styles.section}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>05 · Integración</p><h2>Puertos, espacio y ventilación deciden el encaje</h2><p>No dejes la estación encerrada, suelta ni expuesta a humedad o calor. Reserva espacio según el manual.</p></div><div className={styles.weightBoard}><div><span>Modelo</span><span>Medidas (an. × prof. × al.)</span><span>Peso</span><span>Puertos camper</span></div><div><strong>F1200</strong><span>{size(f1200)}</span><span>{n(f1200.weightKg)} kg</span><span>12 V/120 W · USB-C 100 W</span></div><div><strong>F1800</strong><span>{size(f1800)}</span><span>{n(f1800.weightKg)} kg</span><span>12 V/120 W · 2 USB-C 140 W</span></div><div><strong>F2400</strong><span>{size(f2400)}</span><span>{n(f2400.weightKg)} kg</span><span>RV 12 V/25 A · USB-C 100 W</span></div></div></div></section>
<section className={`${styles.section} ${styles.models}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>06 · Tres encajes</p><h2>El modelo cambia con tu recarga</h2></div><div className={styles.modelGrid}><Model p={f1200} tag="RECARGA FRECUENTE" body="Formato contenido y USB-C de 100 W para una base moderada con conducción o red frecuente." limit="1.024 Wh y 200 W solares máximos exigen controlar varios días de nevera."/><Model p={f1800} tag="TRABAJO Y SOLAR" body="1.800 W, solar hasta 500 W y dos USB-C de 140 W para una rutina conectada." limit="Más potencia no aumenta la energía: almacena los mismos 1.024 Wh que F1200."/><Model p={f2400} tag="MÁS DÍAS" body="2.048 Wh y salida RV regulada de 12 V/25 A aportan margen a frío y trabajo." limit="22 kg requieren un hueco estable; el escenario confort aún necesita recarga."/></div></div></section>
<section className={styles.section}><div className="container"><div className={styles.split}><div><p className={styles.index}>07 · Portátil o integrada</p><h2>Power station frente a instalación fija</h2></div><div><p><strong>Una power station</strong> concentra batería, cargador, inversor y salidas en un equipo movible: útil si buscas sencillez y uso fuera de la furgoneta.</p><p><strong>Una instalación fija</strong> puede integrarse mejor con alternador y cargas permanentes, pero exige dimensionado, protecciones y montaje especializado. No son sustitutos automáticos.</p></div></div></div></section>
<section className={`${styles.section} ${styles.dark}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>08 · Lista corta</p><h2>Antes de comprar</h2></div><div className={styles.checkGrid}>{[["Wh reales al día","Mide nevera y conectividad."],["Días entre recargas","Cuenta el peor tramo razonable."],["Ruta de recarga","Estima horas reales en coche y al sol."],["12 V y USB-C","Valida tensión, amperios y protocolo."],["Hueco ventilado","Mide equipo, conectores y separación."],["Sujeción y acceso","Evita movimiento y conserva controles."]].map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,"0")}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
<section className={`${styles.section} ${styles.faq}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>09 · FAQ</p><h2>Dudas sobre power stations para camper</h2></div><Faq q="¿Cuántos Wh necesito para una camper?" a="Calcula un día y multiplícalo por los días entre recargas. Aquí, tres días sencillos suman 1.377 Wh antes del colchón."/><Faq q="¿Puedo alimentar una nevera 12 V?" a="Sí, si tensión, conector, potencia y arranque son compatibles. Mide su consumo durante 24 horas."/><Faq q="¿Puedo cargar mientras conduzco?" a="Los tres modelos admiten entrada desde vehículo, con límites distintos. Usa el cable previsto y revisa el manual."/><Faq q="¿Necesito placa solar?" a="No siempre. Aporta más en paradas largas con nevera; depende de paneles, sol, orientación y sombra."/><Faq q="¿Sustituye a la batería auxiliar?" a="Puede cubrir un sistema portátil, pero no sustituye automáticamente una instalación fija integrada."/><Faq q="¿Qué cambia si uso Starlink?" a="Añade una carga sostenida. El ejemplo usa 60 W durante seis horas, no una cifra universal."/></div></section>
<section className={`${styles.section} ${styles.cta}`}><div className="container"><p className={styles.kicker}>Tu ruta, tus consumos</p><h2>Calcula la estación para tu camper</h2><p>Añade tu nevera, trabajo, cargas y días; contrasta el resultado con el espacio y la recarga disponible.</p><Link href="/encontrar-power-station">Calcular mi power station para camper →</Link></div></section>
<section className={styles.sources}><div className="container"><p className={styles.index}>10 · Metodología</p><h2>Datos frente a supuestos</h2><p>Capacidad, potencia, peso, dimensiones, entradas y puertos proceden de <code>src/content/products.ts</code>, con fuentes de fabricante verificadas el 20 de agosto de 2026. Consumos, horas, días, simultaneidad y margen del 20 % son supuestos editoriales, no pruebas físicas.</p></div></section>
</article></main><SiteFooter/></>}

function Scenario({no,label,name,energy,margin,power,lines,total,note,wide=false}:{no:string;label:string;name:string;energy:string;margin:string;power:string;lines:string[];total:string;note:string;wide?:boolean}){return <article className={`${styles.scenarioCard} ${wide?styles.scenarioWide:""}`}><header><span>{no}</span><div><p>{label}</p><h3>{name}</h3></div></header><div className={styles.scenarioBody}><dl><div><dt>Energía calculada</dt><dd>≈{energy} Wh</dd></div><div><dt>Plan con margen</dt><dd>≈{margin} Wh</dd></div><div><dt>Potencia simultánea</dt><dd>{power}</dd></div></dl><div className={styles.math}>{lines.map(x=><code key={x}>{x}</code>)}<span>{total}</span></div><p><strong>Prioriza:</strong> {note}</p></div></article>}
function Model({p,tag,body,limit}:{p:typeof f1200;tag:string;body:string;limit:string}){return <article><span>{tag}</span><h3>{p.name}</h3><div className={styles.modelSpecs}><strong>{n(p.capacityWh)} Wh</strong><strong>{n(p.continuousOutputWatts)} W</strong><strong>{n(p.weightKg)} kg</strong></div><p>{body}</p><p className={styles.limit}><b>Límite:</b> {limit}</p><Link href={`/reviews/${p.slug}-review`}>Ver análisis de la {p.model} →</Link></article>}
function Faq({q,a}:{q:string;a:string}){return <details><summary>{q}</summary><p>{a}</p></details>}
