import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { getProductById } from "@/content/products";
import styles from "../use-case.module.css";

const slug="off-grid",publishedAt="2026-08-22",siteUrl=process.env.NEXT_PUBLIC_SITE_URL??"https://carganomada.com";
const title="Qué power station necesitas para varios días off-grid";
const description="Dimensiona una power station off-grid equilibrando consumo diario, batería, recuperación solar, potencia y días de reserva sin red.";
export const metadata:Metadata={title:{absolute:"Power station off-grid: consumo, solar y reserva | Carga Nómada"},description,alternates:{canonical:`/usos/${slug}`},openGraph:{type:"article",url:`/usos/${slug}`,title,description,siteName:"Carga Nómada",locale:"es_ES",publishedTime:publishedAt,modifiedTime:publishedAt},twitter:{card:"summary",title,description}};
const f2400=getProductById("fossibot-f2400")!,f3600=getProductById("fossibot-f3600-pro")!,f7200=getProductById("fossibot-f7200")!;const n=(v:number|undefined)=>v?.toLocaleString("es-ES")??"no declarado";

export default function OffGridPage(){const canonical=`${siteUrl}/usos/${slug}`;const schema={"@context":"https://schema.org","@graph":[{"@type":"BreadcrumbList","@id":`${canonical}#breadcrumb`,itemListElement:[{"@type":"ListItem",position:1,name:"Inicio",item:siteUrl},{"@type":"ListItem",position:2,name:"Usos",item:`${siteUrl}/usos`},{"@type":"ListItem",position:3,name:"Off-grid",item:canonical}]},{"@type":"Article","@id":`${canonical}#article`,mainEntityOfPage:canonical,headline:title,description,datePublished:publishedAt,dateModified:publishedAt,inLanguage:"es",isAccessibleForFree:true,author:{"@id":`${siteUrl}#organization`},publisher:{"@id":`${siteUrl}#organization`},breadcrumb:{"@id":`${canonical}#breadcrumb`}}]};return <><main className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/>
<header className={styles.hero}><div className="container"><nav className={styles.breadcrumb} aria-label="Migas de pan"><Link href="/">Inicio</Link><span>/</span><Link href="/usos">Usos</Link><span>/</span><span>Off-grid</span></nav><p className={styles.kicker}>Caso de uso 05 · Off-grid</p><h1>{title}</h1><p className={styles.lead}>Para varios días sin red necesitas dimensionar tres cosas por separado: cuánto consumes, cuánta energía almacenas y cuánto puedes reponer. Una batería enorme acaba agotándose si el balance diario sigue siendo negativo.</p><div className={styles.heroFacts}><span>Wh/día</span><span>Balance energético</span><span>Días de reserva</span></div><div className={styles.byline}><span>Equipo editorial de Carga Nómada</span><span>Publicado y revisado el 22 de agosto de 2026</span></div></div></header>
<div className="container"><section className={styles.quick}><div><p className={styles.kicker}>Respuesta rápida</p><h2>Off-grid no es solo comprar más batería</h2></div><ol><li><span>01</span>Calcula Wh consumidos al día</li><li><span>02</span>Define días sin generación</li><li><span>03</span>Dimensiona la reserva</li><li><span>04</span>Estima Wh recuperados al día</li><li><span>05</span>Comprueba W y expansión</li></ol><p>La pregunta útil no es solo cuánto dura la batería, sino si puedes reponer aproximadamente lo que gastas y cuánto déficit debe absorber la reserva.</p></section></div>
<article>
<section className={styles.section}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>01 · Dos presupuestos</p><h2>Consumo y generación producen un balance</h2><p>El consumo suma todos los Wh usados en un día. La generación estima los Wh que realmente entran durante ese mismo periodo. Resta ambos para saber si la reserva sube, se mantiene o baja.</p></div><div className={styles.priorityGrid}><article><span>CONSUMO</span><strong>Wh/día</strong><p>Aparatos × potencia media × horas reales.</p></article><article><span>GENERACIÓN</span><strong>Wh/día</strong><p>Energía recuperada, no vatios nominales de panel.</p></article><article><span>BALANCE</span><strong>gen. − cons.</strong><p>Positivo, neutral o negativo como estimación editorial.</p></article><article><span>RESERVA</span><strong>Wh</strong><p>Energía almacenada para noche, nubes y variaciones.</p></article></div><aside className={styles.notice}><strong>Ejemplo de déficit acumulado</strong><p>Si consumes 1.400 Wh/día y recuperas 1.000 Wh/día, el balance teórico es −400 Wh/día. Tras tres días, la reserva habrá aportado aproximadamente 1.200 Wh, antes de conversiones y otras variaciones.</p></aside></div></section>
<section className={`${styles.section} ${styles.scenarios}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>02 · Tres bases energéticas</p><h2>Escenarios con consumo, recuperación y reserva</h2><p>Los consumos, horas y recuperación solar son hipótesis editoriales, no pruebas ni producción garantizada. El margen del 20 % y los días sin sol son decisiones distintas.</p></div><div className={styles.scenarioGrid}>
<Scenario no="01" label="Base ligera · varios días" name="Frío, conexión y cargas pequeñas" consumption="540" margin="648" recovery="700" balance="+160" reserve="2.048 Wh nominales" days="≈3,8 días teóricos sin generar" power="≈150 W + arranque" lines={["Nevera: 350 Wh/día","Luces: 2 × 6 W × 5 h = 60 Wh/día","Móviles: 2 × 15 Wh = 30 Wh/día","Router: 10 W × 8 h = 80 Wh/día","Tablet: 1 carga × 20 Wh = 20 Wh/día"]} total="Consumo 540 Wh/día; con margen = 648 Wh. Recuperación editorial: 700 Wh/día." note="Balance teórico +160 Wh/día sobre el consumo calculado. No garantiza acumularlos: batería llena, límites y momento de producción pueden impedirlo."/>
<Scenario no="02" label="Estancia completa · varias personas" name="Nevera, trabajo, TV y bomba" consumption="1.273" margin="1.528" recovery="1.000" balance="−273" reserve="3.840 Wh nominales" days="≈3,0 días teóricos sin generar" power="≈400 W + arranques" lines={["Nevera: 500 Wh/día","Luces: 4 × 6 W × 5 h = 120 Wh/día","Portátil: 55 W × 5 h = 275 Wh/día","Router: 12 W × 12 h = 144 Wh/día","TV: 50 W × 3 h = 150 Wh/día","Bomba: 60 W × 0,4 h = 24 Wh/día","Móviles: 4 × 15 Wh = 60 Wh/día"]} total="Consumo 1.273 Wh/día; con margen ≈1.528 Wh. Recuperación editorial: 1.000 Wh/día." note="Balance teórico −273 Wh/día. El déficit se acumula incluso con solar; días de menor producción lo amplían."/>
<Scenario wide no="03" label="Consumo alto · varios días" name="Electrónica, cocina y herramienta puntual" consumption="2.273" margin="2.728" recovery="1.800" balance="−473" reserve="5.222,4 Wh nominales" days="≈2,3 días teóricos sin generar" power="≈1.800 W + picos" lines={["Nevera: 600 Wh/día","Router: 15 W × 16 h = 240 Wh/día","Portátil: 65 W × 6 h = 390 Wh/día","TV: 70 W × 4 h = 280 Wh/día","Móviles: 4 × 15 Wh = 60 Wh/día","Bomba: 100 W × 0,5 h = 50 Wh/día","Microondas: 1.300 W × 10/60 h ≈216,7 Wh/día","Cafetera: 1.400 W × 8/60 h ≈186,7 Wh/día","Herramienta: 1.500 W × 10/60 h = 250 Wh/día"]} total="Consumo ≈2.273,4 Wh/día; con margen ≈2.728,1 Wh. Recuperación editorial: 1.800 Wh/día." note="Balance teórico ≈−473,4 Wh/día. Gestionar para que cocina y herramienta no coincidan reduce W, pero no elimina sus Wh."/>
</div><p className={styles.text}>Los días teóricos dividen capacidad nominal entre consumo calculado, antes de energía utilizable, reserva mínima, conversiones, standby, temperatura y otras cargas. No son una promesa de autonomía. Adapta el cálculo con la <Link href="/guias/calcular-autonomia-power-station">guía de autonomía</Link>.</p></div></section>
<section className={`${styles.section} ${styles.models}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>03 · Wp no son Wh diarios</p><h2>La placa indica potencia; el balance necesita energía</h2><p>500 W de paneles no significan 500 W durante 24 horas. Irradiación, orientación, sombras, temperatura, época del año, límites de entrada y pérdidas cambian la producción.</p></div><div className={styles.modelGrid}><article><span>PANEL</span><h3>W nominales</h3><p>Describen una potencia bajo condiciones definidas, no una cosecha diaria garantizada.</p></article><article><span>RECUPERACIÓN</span><h3>Wh del día</h3><p>Es la energía que llegó a la estación durante el periodo y la cifra comparable con tu consumo.</p></article><article><span>COMPATIBILIDAD</span><h3>Límites eléctricos</h3><p>Voltaje, corriente, conectores y configuración se revisan en la <Link href="/guias/placas-solares-power-station">guía solar</Link>, no aquí.</p></article></div></div></section>
<section className={styles.section}><div className="container"><div className={styles.split}><div><p className={styles.index}>04 · El día malo</p><h2>La batería también compra tiempo</h2></div><div><p>La reserva cubre noche y horas sin producción, pero también nubes, sombras, menor irradiación o un día de consumo superior. No existe un número universal de días: elige según consecuencias de quedarte sin energía y alternativas disponibles.</p><p>Un margen del 20 % absorbe variaciones dentro del presupuesto. Pedir dos días sin generación es otra decisión: multiplica el consumo diario por esos días y compáralo con la energía realmente utilizable.</p><p>Un balance positivo tampoco garantiza acumular todo el excedente: puede coincidir con una batería llena, superar límites de entrada o producirse cuando no puede aprovecharse.</p></div></div></div></section>
<section className={styles.section}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>05 · Energía y potencia</p><h2>Muchos Wh no implican necesariamente muchos W</h2><p>Una herramienta de 1.500 W durante diez minutos usa 250 Wh; una carga de 100 W durante quince horas usa 1.500 Wh. La primera marca la potencia y sus posibles picos; la segunda domina la energía diaria.</p></div><p className={styles.text}>Valida potencia continua, picos y simultaneidad en <Link href="/guias/que-puedo-conectar-power-station">qué puedes conectar</Link>. Calefacción resistiva, placas eléctricas y hervidores pueden ser compatibles en W y aun así resultar difíciles de sostener durante horas.</p></div></section>
<section className={`${styles.section} ${styles.models}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>06 · Tres reservas posibles</p><h2>Modelos según balance y días malos</h2><p>Esta progresión prioriza capacidad, entrada solar y expansión; no convierte el modelo mayor en la opción adecuada para todos.</p></div><div className={styles.modelGrid}><Model p={f2400} tag="BASE LIGERA" body="2.048 Wh, 2.400 W, 22 kg y hasta 500 W solares. Puede sostener una base moderada si la recuperación diaria se acerca al consumo." limit="Poca reserva ante varios días malos; no es expandible según el catálogo actual."/><Model p={f3600} tag="RESERVA AMPLIABLE" body="3.840 Wh, 3.600 W, 42 kg, hasta 2.000 W solares y capacidad expandible para aumentar los Wh disponibles." limit="Expandir reserva no aumenta automáticamente potencia AC, entrada solar ni velocidad de carga; verifica el sistema concreto."/><Model p={f7200} tag="ALTA CAPACIDAD Y POTENCIA" body="5.222,4 Wh, 7.200 W, pico de 9.000 W, hasta 3.700 W solares y expansión compatible según catálogo." limit="70 kg, volumen y potencia posiblemente innecesaria para consumos modestos: es un sistema pesado, no una estación ligera."/></div></div></section>
<section className={styles.section}><div className="container"><div className={styles.split}><div><p className={styles.index}>07 · Expansión</p><h2>Más batería añade reserva, no sostenibilidad por sí sola</h2></div><div><p>F3600 Pro y F7200 declaran batería expandible. Las expansiones compatibles FB3840 y FB5222 aumentan los Wh almacenados y, por tanto, el colchón ante déficits o días sin producción.</p><p>La base seguirá perdiendo energía si el balance diario es negativo. Comprueba además si la configuración cambia —o no— potencia, entrada y tiempos; no lo supongas por añadir capacidad.</p></div></div></div></section>
<section className={styles.section}><div className="container"><div className={styles.split}><div><p className={styles.index}>08 · Portátil o permanente</p><h2>Power station frente a sistema fijo</h2></div><div><p>Una power station encaja en una base temporal, estacional, movible o de respaldo donde importa la simplicidad y no modificar una instalación.</p><p>Para vivienda permanente, consumos elevados, grandes campos solares o integración continua, un sistema fijo puede resultar más apropiado. Debe diseñarse conforme a normativa y por profesionales cualificados cuando corresponda.</p><p>Red ocasional, vehículo o un generador externo compatible pueden servir como recarga de respaldo. No damos instrucciones de combustible ni instalación: sigue fabricante y requisitos de seguridad.</p></div></div></div></section>
<section className={`${styles.section} ${styles.dark}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>09 · Errores frecuentes</p><h2>Lo que rompe el balance</h2></div><div className={styles.checkGrid}>{[["Comprar solo batería","Sin reposición, cualquier reserva termina agotándose."],["Confundir Wp y Wh","La potencia del panel no es producción diaria."],["Planificar con sol perfecto","Los días malos deben caber en la reserva."],["Ignorar el déficit","Una pequeña resta negativa se acumula cada día."],["Mezclar margen y autonomía","20 % de colchón no equivale a dos días sin sol."],["Mirar solo Wh","Herramientas y motores también exigen W y picos."],["Expandir sin revisar límites","Más capacidad no cambia necesariamente entrada o potencia."],["Sostener calor durante horas","Una carga resistiva puede dominar todo el presupuesto."],["Usar cifras universales","Producción y consumo deben medirse en tu contexto."],["Tratarlo como vivienda fija","Una solución portátil no sustituye siempre una instalación permanente."]].map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,"0")}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
<section className={`${styles.section} ${styles.faq}`}><div className="container"><div className={styles.sectionHead}><p className={styles.index}>10 · Preguntas frecuentes</p><h2>Dudas sobre energía off-grid</h2></div><Faq q="¿Cuántos Wh necesito para varios días off-grid?" a="Calcula consumo diario, aplica un margen separado y multiplícalo por los días de reserva sin generación que quieres cubrir. Después resta la recuperación prevista."/><Faq q="¿Cuántas placas solares necesito?" a="Depende del consumo, producción local y límites de entrada. Esta página trabaja con Wh recuperados; la compatibilidad de paneles se calcula aparte."/><Faq q="¿Cuántos días dura una power station?" a="Como primera referencia, divide energía utilizable entre Wh diarios. No uses capacidad nominal completa ni ignores reserva, pérdidas y cambios de consumo."/><Faq q="¿Qué pasa si no hay sol?" a="La batería cubre el déficit hasta agotarse. Define días de reserva y una vía alternativa de recarga si quedarse sin energía tiene consecuencias importantes."/><Faq q="¿Necesito una batería expandible?" a="Puede ayudar cuando necesitas más días de reserva, pero no corrige un balance negativo permanente ni aumenta automáticamente otros límites."/><Faq q="¿Power station o instalación solar fija?" a="La estación favorece simplicidad y movilidad; una instalación fija puede encajar mejor en vivienda permanente o consumos altos y continuos."/></div></section>
<section className={`${styles.section} ${styles.cta}`}><div className="container"><p className={styles.kicker}>Empieza por el gasto</p><h2>Calcula tu consumo diario</h2><p>La calculadora suma aparatos, horas y capacidad orientativa. Evalúa después la producción solar y los días de reserva por separado.</p><Link href="/encontrar-power-station">Calcular mi base off-grid →</Link></div></section>
<section className={styles.sources}><div className="container"><p className={styles.index}>11 · Metodología</p><h2>Datos frente a hipótesis</h2><p>Capacidad, potencia, peso, solar y expansión proceden de <code>src/content/products.ts</code>, con fuentes de fabricante verificadas el 20 de agosto de 2026. Consumos, horas, recuperación diaria, balances y margen del 20 % son hipótesis editoriales; no proceden de pruebas ni predicen producción solar.</p></div></section>
</article></main><SiteFooter/></>}
function Scenario({no,label,name,consumption,margin,recovery,balance,reserve,days,power,lines,total,note,wide=false}:{no:string;label:string;name:string;consumption:string;margin:string;recovery:string;balance:string;reserve:string;days:string;power:string;lines:string[];total:string;note:string;wide?:boolean}){return <article className={`${styles.scenarioCard} ${wide?styles.scenarioWide:""}`}><header><span>{no}</span><div><p>{label}</p><h3>{name}</h3></div></header><div className={styles.scenarioBody}><dl><div><dt>Consumo diario</dt><dd>≈{consumption} Wh</dd></div><div><dt>Con margen editorial</dt><dd>≈{margin} Wh</dd></div><div><dt>Recuperación estimada</dt><dd>≈{recovery} Wh/día</dd></div><div><dt>Balance diario</dt><dd>{balance} Wh</dd></div><div><dt>Reserva</dt><dd>{reserve}</dd></div><div><dt>Sin generar</dt><dd>{days}</dd></div><div><dt>Potencia simultánea</dt><dd>{power}</dd></div></dl><div className={styles.math}>{lines.map(x=><code key={x}>{x}</code>)}<span>{total}</span></div><p><strong>Interpretación:</strong> {note}</p></div></article>}
function Model({p,tag,body,limit}:{p:typeof f2400;tag:string;body:string;limit:string}){return <article><span>{tag}</span><h3>{p.name}</h3><div className={styles.modelSpecs}><strong>{n(p.capacityWh)} Wh</strong><strong>{n(p.continuousOutputWatts)} W</strong><strong>{n(p.weightKg)} kg</strong></div><p>{body}</p><p className={styles.limit}><b>Límite:</b> {limit}</p><Link href={`/reviews/${p.slug}-review`}>Ver análisis de la {p.model} →</Link></article>}
function Faq({q,a}:{q:string;a:string}){return <details><summary>{q}</summary><p>{a}</p></details>}
